/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const youtubeChannelGetInputSchema =
  /* youtubeChannelGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      query: v.array(v.string()),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type YoutubeChannelGetInput = v.InferInput<typeof youtubeChannelGetInputSchema>
