/* Generated by openApiCatalogGenerate. Do not edit. */
export const youtubeChannelGetDefinition = {
  description: "Returns data from YouTube channels.",
  folder: "get-youtube-channel",
  method: "GET",
  operationId: "getYoutube-Channel",
  parameters: [
    {
      description:
        "The parameter defines the way you want to submit your task to Outscraper. It can be set to `false` to open an HTTP connection and keep it open until you get your results, or `true` (default) to just submit your requests to Outscraper and retrieve them later (usually within 1-3 minutes) with the [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.\n\nA good practice is to send async requests and start checking the results after the estimated execution time. Check out [this](https://github.com/outscraper/outscraper-python/blob/master/examples/Run%20Async%20Requests.md) Python implementation as an example.\n\nAs most of the requests take some time to be executed the `async=true` option is preferred to avoid HTTP request timeouts.",
      example: false,
      in: "query",
      location: "query",
      name: "async",
      required: true,
      schema: {
        default: true,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines which fields you want to include with each item returned in the response. By default, it returns all fields. Use `&fields=query,name` to return only the specific ones.",
      in: "query",
      location: "query",
      name: "fields",
      required: false,
      schema: {
        type: "string",
      },
    },
    {
      description:
        "The parameter defines the format of the output data. Using this parameter overwrites the `ui` parameter to `true`.",
      in: "query",
      location: "query",
      name: "format",
      required: false,
      schema: {
        collectionFormat: "csv",
        items: {
          default: "xlsx",
          enum: ["xlsx", "csv", "json", "parquet"],
          type: "string",
        },
        type: "array",
      },
    },
    {
      description:
        "YouTube handles or YouTube channel URLs (e.g., `https://www.youtube.com/@outscraper`, `outscraper`). \n\nIt supports batching by sending arrays with up to `1000` queries (e.g., `query=text1&query=text2&query=text3`). It allows multiple queries to be sent in one request and to save on network latency time.",
      in: "query",
      location: "query",
      name: "query",
      required: true,
      schema: {
        collectionFormat: "csv",
        items: {
          type: "string",
        },
        type: "array",
      },
    },
    {
      description:
        "The parameter defines whether a task will be executed as a UI task. This is commonly used when you want to create a regular platform task with API.\n\nUsing this parameter overwrites the `async` parameter to `true`.",
      in: "query",
      location: "query",
      name: "ui",
      required: false,
      schema: {
        default: false,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines the URL address (callback) to which Outscraper will create a POST request with a JSON body once a task/request is finished.\n\nUsing this parameter overwrites the webhook from integrations.",
      in: "query",
      location: "query",
      name: "webhook",
      required: false,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/youtube-channel",
  responses: [
    {
      content: [
        {
          example: {
            data: [
              {
                channel_id: "UCDYOuXSEenLpt5tKNq-0l9Q",
                channel_url: "https://www.youtube.com/channel/UCDYOuXSEenLpt5tKNq-0l9Q",
                country: null,
                description:
                  "Solutions for accessing public information from the internet for lead generation, marketing, and data science.",
                is_family_safe: true,
                joined: null,
                keywords: 'Outscraper outscraper.com "data scraping" "web scraping" "b2b lead generation"',
                primary_links: [],
                query: "outscraper",
                rss_url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCDYOuXSEenLpt5tKNq-0l9Q",
                secondary_links: [],
                subscribers_count: "849 subscribers",
                subscribers_count_parsed: 849,
                thumbnail:
                  "https://yt3.googleusercontent.com/gWnPr_jKVFS5TV4vYlvlWOhjzaZrx_d8EPfgY_i_j4aVVyRBs_W09Y6fkFw_J7x57dcnNspo=s900-c-k-c0x00ffffff-no-rj",
                title: "Outscraper",
                vanity_channel_url: "http://www.youtube.com/@outscraper",
                videos_count: "48",
                videos_count_parsed: 48,
                views_count: null,
                views_count_parsed: null,
              },
            ],
            id: "your-request-id",
            status: "Success",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: {},
      status: "200",
    },
    {
      content: [
        {
          example: {
            id: "your-request-id",
            results_location: "https://api.outscraper.cloud/requests/your-request-id",
            status: "Pending",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description:
        "The response contains a request ID that can be used to fetch results by using [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.",
      status: "202",
    },
    {
      content: [
        {
          example: {
            id: "your-request-id",
            status: "Failure",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "The request was finished with failure and has no results.",
      status: "204",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage: "Please close past due invoices or verify your card information is correct.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Past due invoices or a payment method not connected.",
      status: "402",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Invalid query URL parameters.",
      status: "422",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "YouTube Channels",
  tags: ["YouTube"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source:
        'curl -X GET "https://api.outscraper.cloud/youtube-channel?query=outscraper&async=false" -H  "X-API-KEY: YOUR-API-KEY"',
    },
    {
      lang: "cURL (async)",
      source:
        'curl -X GET "https://api.outscraper.cloud/youtube-channel?query=outscraper" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
