/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const youtubeChannelGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          channel_id: v.optional(v.nullable(v.string())),
          channel_url: v.optional(v.nullable(v.string())),
          country: v.optional(v.unknown()),
          description: v.optional(v.nullable(v.string())),
          is_family_safe: v.optional(v.nullable(v.boolean())),
          joined: v.optional(v.unknown()),
          keywords: v.optional(v.nullable(v.string())),
          primary_links: v.optional(v.array(v.unknown())),
          query: v.optional(v.nullable(v.string())),
          rss_url: v.optional(v.nullable(v.string())),
          secondary_links: v.optional(v.array(v.unknown())),
          subscribers_count: v.optional(v.nullable(v.string())),
          subscribers_count_parsed: v.optional(v.nullable(v.number())),
          thumbnail: v.optional(v.nullable(v.string())),
          title: v.optional(v.nullable(v.string())),
          vanity_channel_url: v.optional(v.nullable(v.string())),
          videos_count: v.optional(v.nullable(v.string())),
          videos_count_parsed: v.optional(v.nullable(v.number())),
          views_count: v.optional(v.unknown()),
          views_count_parsed: v.optional(v.unknown()),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type YoutubeChannelGetResponse = v.InferOutput<typeof youtubeChannelGetResponseSchema>
