/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type YoutubeChannelGetInput, youtubeChannelGetInputSchema } from "./youtubeChannelGetInputSchema.js"
import { type YoutubeChannelGetResponse, youtubeChannelGetResponseSchema } from "./youtubeChannelGetResponseSchema.js"

export async function youtubeChannelGet(
  client: OutscraperClient,
  input: YoutubeChannelGetInput,
): Promise<Result<YoutubeChannelGetResponse>> {
  const op = "youtubeChannelGet"
  const parsed = v.safeParse(youtubeChannelGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid youtubeChannelGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/youtube-channel",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: youtubeChannelGetResponseSchema,
  })
}
