/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type LinkedinProfilesGetInput, linkedinProfilesGetInputSchema } from "./linkedinProfilesGetInputSchema.js"
import {
  type LinkedinProfilesGetResponse,
  linkedinProfilesGetResponseSchema,
} from "./linkedinProfilesGetResponseSchema.js"

export async function linkedinProfilesGet(
  client: OutscraperClient,
  input: LinkedinProfilesGetInput,
): Promise<Result<LinkedinProfilesGetResponse>> {
  const op = "linkedinProfilesGet"
  const parsed = v.safeParse(linkedinProfilesGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid linkedinProfilesGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/linkedin-profiles",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: linkedinProfilesGetResponseSchema,
  })
}
