/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type WhataspCheckerGetInput, whataspCheckerGetInputSchema } from "./whataspCheckerGetInputSchema.js"
import { type WhataspCheckerGetResponse, whataspCheckerGetResponseSchema } from "./whataspCheckerGetResponseSchema.js"

export async function whataspCheckerGet(
  client: OutscraperClient,
  input: WhataspCheckerGetInput,
): Promise<Result<WhataspCheckerGetResponse>> {
  const op = "whataspCheckerGet"
  const parsed = v.safeParse(whataspCheckerGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid whataspCheckerGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/whatasp-checker",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: whataspCheckerGetResponseSchema,
  })
}
