/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleSearchShoppingGetInput,
  googleSearchShoppingGetInputSchema,
} from "./googleSearchShoppingGetInputSchema.js"
import {
  type GoogleSearchShoppingGetResponse,
  googleSearchShoppingGetResponseSchema,
} from "./googleSearchShoppingGetResponseSchema.js"

export async function googleSearchShoppingGet(
  client: OutscraperClient,
  input: GoogleSearchShoppingGetInput,
): Promise<Result<GoogleSearchShoppingGetResponse>> {
  const op = "googleSearchShoppingGet"
  const parsed = v.safeParse(googleSearchShoppingGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleSearchShoppingGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-search-shopping",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleSearchShoppingGetResponseSchema,
  })
}
