/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googleSearchShoppingGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            delivery: v.optional(v.unknown()),
            id: v.optional(v.unknown()),
            image: v.optional(v.unknown()),
            link: v.optional(v.unknown()),
            options: v.optional(v.unknown()),
            parsed_price: v.optional(v.unknown()),
            position: v.optional(v.unknown()),
            price: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            source: v.optional(v.unknown()),
            source_link: v.optional(v.unknown()),
            title: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type GoogleSearchShoppingGetResponse = v.InferOutput<typeof googleSearchShoppingGetResponseSchema>
