/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TasksGetInput, tasksGetInputSchema } from "./tasksGetInputSchema.js"
import { type TasksGetResponse, tasksGetResponseSchema } from "./tasksGetResponseSchema.js"

export async function tasksGet(client: OutscraperClient, input: TasksGetInput = {}): Promise<Result<TasksGetResponse>> {
  const op = "tasksGet"
  const parsed = v.safeParse(tasksGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid tasksGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/tasks",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: tasksGetResponseSchema,
  })
}
