/* Generated by openApiCatalogGenerate. Do not edit. */
export const tasksGetDefinition = {
  description: "Fetch user tasks.",
  folder: "get-tasks",
  method: "GET",
  operationId: "getTasks",
  parameters: [
    {
      description: "The parameter specifies the last task ID. Used for pagination.",
      in: "query",
      location: "query",
      name: "lastId",
      required: false,
      schema: {
        type: "string",
      },
    },
    {
      description: "The parameter specifies the number of items to return.",
      in: "query",
      location: "query",
      name: "pageSize",
      required: false,
      schema: {
        default: 10,
        type: "integer",
      },
    },
    {
      description: "The parameter specifies the tag to search among the tasks.",
      in: "query",
      location: "query",
      name: "query",
      required: false,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/tasks",
  responses: [
    {
      content: [
        {
          example: {
            has_more: true,
            tasks: [
              {
                created: "2022-02-08T20:49:06.879078",
                id: "YOUR_TASK_ID",
                metadata: {
                  queries: ["bars ny usa", "restaurants ny usa"],
                  service_name: "google_maps_service_v2",
                },
                queue_task_id: "2b9aa187-281a-4d4e-a4c6-fbe941aaac34",
                results: [
                  {
                    file_url: "LINK_TO_RESULTS",
                    product_name: "Google Maps Data",
                    quantity: 509,
                  },
                  {
                    product_name: "Domains",
                    quantity: 509,
                  },
                ],
                status: "SUCCESS",
                updated: "2022-02-08T20:51:17.402668",
                user_id: "YOUR_USER_ID",
              },
            ],
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "User tasks.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Get Tasks",
  tags: ["Platform & Dashboard"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X GET "https://api.outscraper.cloud/tasks" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
