/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksGetInputSchema =
  /* tasksGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.optional(
      v.looseObject({
        lastId: v.optional(v.string()),
        pageSize: v.optional(v.pipe(v.number(), v.integer()), 10),
        query: v.optional(v.string()),
      }),
      {},
    ),
    headers: v.optional(v.looseObject({}), {}),
  })

export type TasksGetInput = v.InferInput<typeof tasksGetInputSchema>
