/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksGetResponseSchema = v.looseObject({
  has_more: v.optional(v.nullable(v.boolean())),
  tasks: v.optional(
    v.array(
      v.looseObject({
        created: v.optional(v.nullable(v.string())),
        id: v.optional(v.nullable(v.string())),
        metadata: v.optional(
          v.looseObject({ queries: v.optional(v.unknown()), service_name: v.optional(v.unknown()) }),
        ),
        queue_task_id: v.optional(v.nullable(v.string())),
        results: v.optional(v.array(v.unknown())),
        status: v.optional(v.nullable(v.string())),
        updated: v.optional(v.nullable(v.string())),
        user_id: v.optional(v.nullable(v.string())),
      }),
    ),
  ),
})

export type TasksGetResponse = v.InferOutput<typeof tasksGetResponseSchema>
