/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleMapsDirectionsGetInput,
  googleMapsDirectionsGetInputSchema,
} from "./googleMapsDirectionsGetInputSchema.js"
import {
  type GoogleMapsDirectionsGetResponse,
  googleMapsDirectionsGetResponseSchema,
} from "./googleMapsDirectionsGetResponseSchema.js"

export async function googleMapsDirectionsGet(
  client: OutscraperClient,
  input: GoogleMapsDirectionsGetInput,
): Promise<Result<GoogleMapsDirectionsGetResponse>> {
  const op = "googleMapsDirectionsGet"
  const parsed = v.safeParse(googleMapsDirectionsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleMapsDirectionsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-maps-directions",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleMapsDirectionsGetResponseSchema,
  })
}
