/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googleMapsDirectionsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            datetime_utc: v.optional(v.unknown()),
            destination: v.optional(v.unknown()),
            destination_coordinates: v.optional(v.unknown()),
            "distance(meters)": v.optional(v.unknown()),
            distance_label: v.optional(v.unknown()),
            "duration(minutes)": v.optional(v.unknown()),
            "duration_max(minutes)": v.optional(v.unknown()),
            "duration_min(minutes)": v.optional(v.unknown()),
            origin: v.optional(v.unknown()),
            origin_coordinates: v.optional(v.unknown()),
            query_destination: v.optional(v.unknown()),
            query_origin: v.optional(v.unknown()),
            road: v.optional(v.unknown()),
            "road_distance_timing(meters:seconds)": v.optional(v.unknown()),
            timestamp: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type GoogleMapsDirectionsGetResponse = v.InferOutput<typeof googleMapsDirectionsGetResponseSchema>
