/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type AiScraperGetInput, aiScraperGetInputSchema } from "./aiScraperGetInputSchema.js"
import { type AiScraperGetResponse, aiScraperGetResponseSchema } from "./aiScraperGetResponseSchema.js"

export async function aiScraperGet(
  client: OutscraperClient,
  input: AiScraperGetInput,
): Promise<Result<AiScraperGetResponse>> {
  const op = "aiScraperGet"
  const parsed = v.safeParse(aiScraperGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid aiScraperGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/ai-scraper",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: aiScraperGetResponseSchema,
  })
}
