/* Generated by openApiCatalogGenerate. Do not edit. */
export const aiScraperGetDefinition = {
  description:
    "Extracts the data you need from any web page by using AI. You can provide either a `prompt` for natural language instructions or a `schema` for structured JSON output, or both.",
  folder: "get-ai-scraper",
  method: "GET",
  operationId: "getAi-Scraper",
  parameters: [
    {
      description:
        "The parameter defines the way you want to submit your task to Outscraper. It can be set to `false` to open an HTTP connection and keep it open until you get your results, or `true` (default) to just submit your requests to Outscraper and retrieve them later (usually within 1-3 minutes) with the [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.\n\nA good practice is to send async requests and start checking the results after the estimated execution time. Check out [this](https://github.com/outscraper/outscraper-python/blob/master/examples/Run%20Async%20Requests.md) Python implementation as an example.\n\nAs most of the requests take some time to be executed the `async=true` option is preferred to avoid HTTP request timeouts.",
      example: false,
      in: "query",
      location: "query",
      name: "async",
      required: true,
      schema: {
        default: true,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines which fields you want to include with each item returned in the response. By default, it returns all fields. Use `&fields=query,name` to return only the specific ones.",
      in: "query",
      location: "query",
      name: "fields",
      required: false,
      schema: {
        type: "string",
      },
    },
    {
      description:
        "The parameter defines the format of the output data. Using this parameter overwrites the `ui` parameter to `true`.",
      in: "query",
      location: "query",
      name: "format",
      required: false,
      schema: {
        collectionFormat: "csv",
        items: {
          default: "xlsx",
          enum: ["xlsx", "csv", "json", "parquet"],
          type: "string",
        },
        type: "array",
      },
    },
    {
      description: "The parameter specifies the limit of pages to get from one query.",
      in: "query",
      location: "query",
      name: "limit",
      required: false,
      schema: {
        default: 1,
        type: "integer",
      },
    },
    {
      description:
        "A plain text description of what data you want to extract from the page (e.g., `Extract company_name, company_description, and people.`).\n\nYou must provide either `prompt` or `schema` (or both). Maximum length: `2024` characters.",
      in: "query",
      location: "query",
      name: "prompt",
      required: false,
      schema: {
        example: "Extract company_name, company_description, and people.",
        maxLength: 2024,
        type: "string",
      },
    },
    {
      description:
        "Links to web pages (e.g., `https://www.apple.com/iphone/`).\n\nIt supports batching by sending arrays with up to `1000` queries (e.g., `query=text1&query=text2&query=text3`). It allows multiple queries to be sent in one request and to save on network latency time.",
      in: "query",
      location: "query",
      name: "query",
      required: true,
      schema: {
        collectionFormat: "csv",
        items: {
          type: "string",
        },
        type: "array",
      },
    },
    {
      description:
        'A JSON Schema object that defines the structure of data to extract from the page (e.g., `{"type":"object","required":[],"properties":{"company_name":{"type":"string"},"company_description":{"type":"string"},"people":{"type":"array","items":{"type":"string"}}}}`).\n\nYou must provide either `prompt` or `schema` (or both). When passing the schema, send it as a JSON string and URL-encode the value.',
      in: "query",
      location: "query",
      name: "schema",
      required: false,
      schema: {
        example:
          '{"type":"object","required":[],"properties":{"company_name":{"type":"string"},"company_description":{"type":"string"},"people":{"type":"array","items":{"type":"string"}}}}',
        type: "string",
      },
    },
    {
      description:
        "The parameter defines whether a task will be executed as a UI task. This is commonly used when you want to create a regular platform task with API.\n\nUsing this parameter overwrites the `async` parameter to `true`.",
      in: "query",
      location: "query",
      name: "ui",
      required: false,
      schema: {
        default: false,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines the URL address (callback) to which Outscraper will create a POST request with a JSON body once a task/request is finished.\n\nUsing this parameter overwrites the webhook from integrations.",
      in: "query",
      location: "query",
      name: "webhook",
      required: false,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/ai-scraper",
  responses: [
    {
      content: [
        {
          example: {
            data: [
              {
                company_description: "Apple designs consumer electronics, software, and online services.",
                company_name: "Apple",
                people: ["Tim Cook", "John Ternus"],
                query: "https://www.apple.com/",
              },
            ],
            id: "your-request-id",
            status: "Success",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: {},
      status: "200",
    },
    {
      content: [
        {
          example: {
            id: "your-request-id",
            results_location: "https://api.outscraper.cloud/requests/your-request-id",
            status: "Pending",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description:
        "The response contains a request ID that can be used to fetch results by using [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.",
      status: "202",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage: "Please close past due invoices or verify your card information is correct.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Past due invoices or a payment method not connected.",
      status: "402",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Invalid query URL parameters.",
      status: "422",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Universal AI-Powered Scraper",
  tags: ["Other Services"],
  "x-codeSamples": [
    {
      lang: "cURL (prompt)",
      source:
        'curl -G "https://api.outscraper.cloud/ai-scraper" --data-urlencode "query=https://www.apple.com/" --data-urlencode "prompt=Extract company_name, company_description, and people." --data-urlencode "async=false" -H "X-API-KEY: YOUR-API-KEY"',
    },
    {
      lang: "cURL (schema-guided)",
      source:
        'curl -G "https://api.outscraper.cloud/ai-scraper" --data-urlencode "query=https://www.apple.com/" --data-urlencode "schema={\\"type\\":\\"object\\",\\"required\\":[],\\"properties\\":{\\"company_name\\":{\\"type\\":\\"string\\"},\\"company_description\\":{\\"type\\":\\"string\\"},\\"people\\":{\\"type\\":\\"array\\",\\"items\\":{\\"type\\":\\"string\\"}}}}" --data-urlencode "async=false" -H "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
