/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const aiScraperGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          company_description: v.optional(v.nullable(v.string())),
          company_name: v.optional(v.nullable(v.string())),
          people: v.optional(v.array(v.unknown())),
          query: v.optional(v.nullable(v.string())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type AiScraperGetResponse = v.InferOutput<typeof aiScraperGetResponseSchema>
