/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const aiScraperGetInputSchema =
  /* aiScraperGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      limit: v.optional(v.pipe(v.number(), v.integer()), 1),
      prompt: v.optional(v.pipe(v.string(), v.maxLength(2024))),
      query: v.array(v.string()),
      schema: v.optional(v.string()),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type AiScraperGetInput = v.InferInput<typeof aiScraperGetInputSchema>
