/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GoogleTrendsGetInput, googleTrendsGetInputSchema } from "./googleTrendsGetInputSchema.js"
import { type GoogleTrendsGetResponse, googleTrendsGetResponseSchema } from "./googleTrendsGetResponseSchema.js"

export async function googleTrendsGet(
  client: OutscraperClient,
  input: GoogleTrendsGetInput,
): Promise<Result<GoogleTrendsGetResponse>> {
  const op = "googleTrendsGet"
  const parsed = v.safeParse(googleTrendsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleTrendsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-trends",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleTrendsGetResponseSchema,
  })
}
