/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TiktokProfilesGetInput, tiktokProfilesGetInputSchema } from "./tiktokProfilesGetInputSchema.js"
import { type TiktokProfilesGetResponse, tiktokProfilesGetResponseSchema } from "./tiktokProfilesGetResponseSchema.js"

export async function tiktokProfilesGet(
  client: OutscraperClient,
  input: TiktokProfilesGetInput,
): Promise<Result<TiktokProfilesGetResponse>> {
  const op = "tiktokProfilesGet"
  const parsed = v.safeParse(tiktokProfilesGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid tiktokProfilesGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/tiktok-profiles",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: tiktokProfilesGetResponseSchema,
  })
}
