/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type YellowpagesSearchGetInput, yellowpagesSearchGetInputSchema } from "./yellowpagesSearchGetInputSchema.js"
import {
  type YellowpagesSearchGetResponse,
  yellowpagesSearchGetResponseSchema,
} from "./yellowpagesSearchGetResponseSchema.js"

export async function yellowpagesSearchGet(
  client: OutscraperClient,
  input: YellowpagesSearchGetInput,
): Promise<Result<YellowpagesSearchGetResponse>> {
  const op = "yellowpagesSearchGet"
  const parsed = v.safeParse(yellowpagesSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid yellowpagesSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/yellowpages-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: yellowpagesSearchGetResponseSchema,
  })
}
