/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const yellowpagesSearchGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            amenities: v.optional(v.unknown()),
            business_link: v.optional(v.unknown()),
            categories: v.optional(v.unknown()),
            locality: v.optional(v.unknown()),
            name: v.optional(v.unknown()),
            phone: v.optional(v.unknown()),
            position: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            range: v.optional(v.unknown()),
            site: v.optional(v.unknown()),
            snippet: v.optional(v.unknown()),
            street: v.optional(v.unknown()),
            thumbnail: v.optional(v.unknown()),
            years_in_business: v.optional(v.unknown()),
            years_with_yp: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type YellowpagesSearchGetResponse = v.InferOutput<typeof yellowpagesSearchGetResponseSchema>
