/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const whitepagesAddressesGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(v.array(v.looseObject({ query: v.optional(v.nullable(v.string())) }))),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type WhitepagesAddressesGetResponse = v.InferOutput<typeof whitepagesAddressesGetResponseSchema>
