/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googleSearchJobsGetResponseSchema = v.union([
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type GoogleSearchJobsGetResponse = v.InferOutput<typeof googleSearchJobsGetResponseSchema>
