/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GoogleSearchJobsGetInput, googleSearchJobsGetInputSchema } from "./googleSearchJobsGetInputSchema.js"
import {
  type GoogleSearchJobsGetResponse,
  googleSearchJobsGetResponseSchema,
} from "./googleSearchJobsGetResponseSchema.js"

export async function googleSearchJobsGet(
  client: OutscraperClient,
  input: GoogleSearchJobsGetInput,
): Promise<Result<GoogleSearchJobsGetResponse>> {
  const op = "googleSearchJobsGet"
  const parsed = v.safeParse(googleSearchJobsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleSearchJobsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-search-jobs",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleSearchJobsGetResponseSchema,
  })
}
