/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type YoutubeCommentsGetInput, youtubeCommentsGetInputSchema } from "./youtubeCommentsGetInputSchema.js"
import {
  type YoutubeCommentsGetResponse,
  youtubeCommentsGetResponseSchema,
} from "./youtubeCommentsGetResponseSchema.js"

export async function youtubeCommentsGet(
  client: OutscraperClient,
  input: YoutubeCommentsGetInput,
): Promise<Result<YoutubeCommentsGetResponse>> {
  const op = "youtubeCommentsGet"
  const parsed = v.safeParse(youtubeCommentsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid youtubeCommentsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/youtube-comments",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: youtubeCommentsGetResponseSchema,
  })
}
