/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const youtubeCommentsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            author_chanel: v.optional(v.unknown()),
            author_image: v.optional(v.unknown()),
            author_title: v.optional(v.unknown()),
            content: v.optional(v.unknown()),
            id: v.optional(v.unknown()),
            is_channel_owner: v.optional(v.unknown()),
            published: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            replies: v.optional(v.unknown()),
            votes: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type YoutubeCommentsGetResponse = v.InferOutput<typeof youtubeCommentsGetResponseSchema>
