/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type WhitepagesPhonesGetInput, whitepagesPhonesGetInputSchema } from "./whitepagesPhonesGetInputSchema.js"
import {
  type WhitepagesPhonesGetResponse,
  whitepagesPhonesGetResponseSchema,
} from "./whitepagesPhonesGetResponseSchema.js"

export async function whitepagesPhonesGet(
  client: OutscraperClient,
  input: WhitepagesPhonesGetInput,
): Promise<Result<WhitepagesPhonesGetResponse>> {
  const op = "whitepagesPhonesGet"
  const parsed = v.safeParse(whitepagesPhonesGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid whitepagesPhonesGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/whitepages-phones",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: whitepagesPhonesGetResponseSchema,
  })
}
