/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const reverseGeocodingGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          address: v.optional(v.nullable(v.string())),
          city: v.optional(v.nullable(v.string())),
          country_code: v.optional(v.nullable(v.string())),
          county: v.optional(v.nullable(v.string())),
          photo: v.optional(v.nullable(v.string())),
          plus_code: v.optional(v.nullable(v.string())),
          postal_code: v.optional(v.nullable(v.string())),
          query: v.optional(v.nullable(v.string())),
          state: v.optional(v.nullable(v.string())),
          street: v.optional(v.nullable(v.string())),
          time_zone: v.optional(v.nullable(v.string())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type ReverseGeocodingGetResponse = v.InferOutput<typeof reverseGeocodingGetResponseSchema>
