/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type ReverseGeocodingGetInput, reverseGeocodingGetInputSchema } from "./reverseGeocodingGetInputSchema.js"
import {
  type ReverseGeocodingGetResponse,
  reverseGeocodingGetResponseSchema,
} from "./reverseGeocodingGetResponseSchema.js"

export async function reverseGeocodingGet(
  client: OutscraperClient,
  input: ReverseGeocodingGetInput,
): Promise<Result<ReverseGeocodingGetResponse>> {
  const op = "reverseGeocodingGet"
  const parsed = v.safeParse(reverseGeocodingGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid reverseGeocodingGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/reverse-geocoding",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: reverseGeocodingGetResponseSchema,
  })
}
