/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type PhonesEnricherGetInput, phonesEnricherGetInputSchema } from "./phonesEnricherGetInputSchema.js"
import { type PhonesEnricherGetResponse, phonesEnricherGetResponseSchema } from "./phonesEnricherGetResponseSchema.js"

export async function phonesEnricherGet(
  client: OutscraperClient,
  input: PhonesEnricherGetInput,
): Promise<Result<PhonesEnricherGetResponse>> {
  const op = "phonesEnricherGet"
  const parsed = v.safeParse(phonesEnricherGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid phonesEnricherGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/phones-enricher",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: phonesEnricherGetResponseSchema,
  })
}
