/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const phonesEnricherGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          carrier_name: v.optional(v.nullable(v.string())),
          carrier_type: v.optional(v.nullable(v.string())),
          query: v.optional(v.nullable(v.string())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type PhonesEnricherGetResponse = v.InferOutput<typeof phonesEnricherGetResponseSchema>
