/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type MapsSearchGetInput, mapsSearchGetInputSchema } from "./mapsSearchGetInputSchema.js"
import { type MapsSearchGetResponse, mapsSearchGetResponseSchema } from "./mapsSearchGetResponseSchema.js"

export async function mapsSearchGet(
  client: OutscraperClient,
  input: MapsSearchGetInput,
): Promise<Result<MapsSearchGetResponse>> {
  const op = "mapsSearchGet"
  const parsed = v.safeParse(mapsSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid mapsSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/maps/search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: mapsSearchGetResponseSchema,
  })
}
