/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type DisposableEmailCheckerGetInput,
  disposableEmailCheckerGetInputSchema,
} from "./disposableEmailCheckerGetInputSchema.js"
import {
  type DisposableEmailCheckerGetResponse,
  disposableEmailCheckerGetResponseSchema,
} from "./disposableEmailCheckerGetResponseSchema.js"

export async function disposableEmailCheckerGet(
  client: OutscraperClient,
  input: DisposableEmailCheckerGetInput,
): Promise<Result<DisposableEmailCheckerGetResponse>> {
  const op = "disposableEmailCheckerGet"
  const parsed = v.safeParse(disposableEmailCheckerGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid disposableEmailCheckerGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/disposable-email-checker",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: disposableEmailCheckerGetResponseSchema,
  })
}
