/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const disposableEmailCheckerGetResponseSchema = v.looseObject({
  id: v.optional(v.nullable(v.string())),
  results_location: v.optional(v.nullable(v.string())),
  status: v.optional(v.nullable(v.string())),
})

export type DisposableEmailCheckerGetResponse = v.InferOutput<typeof disposableEmailCheckerGetResponseSchema>
