/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type EmailsFinderGetInput, emailsFinderGetInputSchema } from "./emailsFinderGetInputSchema.js"
import { type EmailsFinderGetResponse, emailsFinderGetResponseSchema } from "./emailsFinderGetResponseSchema.js"

export async function emailsFinderGet(
  client: OutscraperClient,
  input: EmailsFinderGetInput,
): Promise<Result<EmailsFinderGetResponse>> {
  const op = "emailsFinderGet"
  const parsed = v.safeParse(emailsFinderGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid emailsFinderGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/emails-finder",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: emailsFinderGetResponseSchema,
  })
}
