/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const emailsFinderGetResponseSchema = v.union([
  v.looseObject({}),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type EmailsFinderGetResponse = v.InferOutput<typeof emailsFinderGetResponseSchema>
