/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleShoppingReviewsGetInput,
  googleShoppingReviewsGetInputSchema,
} from "./googleShoppingReviewsGetInputSchema.js"
import {
  type GoogleShoppingReviewsGetResponse,
  googleShoppingReviewsGetResponseSchema,
} from "./googleShoppingReviewsGetResponseSchema.js"

export async function googleShoppingReviewsGet(
  client: OutscraperClient,
  input: GoogleShoppingReviewsGetInput,
): Promise<Result<GoogleShoppingReviewsGetResponse>> {
  const op = "googleShoppingReviewsGet"
  const parsed = v.safeParse(googleShoppingReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleShoppingReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-shopping-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleShoppingReviewsGetResponseSchema,
  })
}
