/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TiktokCommentsGetInput, tiktokCommentsGetInputSchema } from "./tiktokCommentsGetInputSchema.js"
import { type TiktokCommentsGetResponse, tiktokCommentsGetResponseSchema } from "./tiktokCommentsGetResponseSchema.js"

export async function tiktokCommentsGet(
  client: OutscraperClient,
  input: TiktokCommentsGetInput,
): Promise<Result<TiktokCommentsGetResponse>> {
  const op = "tiktokCommentsGet"
  const parsed = v.safeParse(tiktokCommentsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid tiktokCommentsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/tiktok-comments",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: tiktokCommentsGetResponseSchema,
  })
}
