/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GoogleMapsSearchPostInput, googleMapsSearchPostInputSchema } from "./googleMapsSearchPostInputSchema.js"
import {
  type GoogleMapsSearchPostResponse,
  googleMapsSearchPostResponseSchema,
} from "./googleMapsSearchPostResponseSchema.js"

export async function googleMapsSearchPost(
  client: OutscraperClient,
  input: GoogleMapsSearchPostInput,
): Promise<Result<GoogleMapsSearchPostResponse>> {
  const op = "googleMapsSearchPost"
  const parsed = v.safeParse(googleMapsSearchPostInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleMapsSearchPost input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-maps-search",
    method: "POST",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleMapsSearchPostResponseSchema,
  })
}
