/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleSearchAutocompleteGetInput,
  googleSearchAutocompleteGetInputSchema,
} from "./googleSearchAutocompleteGetInputSchema.js"
import {
  type GoogleSearchAutocompleteGetResponse,
  googleSearchAutocompleteGetResponseSchema,
} from "./googleSearchAutocompleteGetResponseSchema.js"

export async function googleSearchAutocompleteGet(
  client: OutscraperClient,
  input: GoogleSearchAutocompleteGetInput,
): Promise<Result<GoogleSearchAutocompleteGetResponse>> {
  const op = "googleSearchAutocompleteGet"
  const parsed = v.safeParse(googleSearchAutocompleteGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleSearchAutocompleteGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-search-autocomplete",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleSearchAutocompleteGetResponseSchema,
  })
}
