/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type DeliverooGetInput, deliverooGetInputSchema } from "./deliverooGetInputSchema.js"
import { type DeliverooGetResponse, deliverooGetResponseSchema } from "./deliverooGetResponseSchema.js"

export async function deliverooGet(
  client: OutscraperClient,
  input: DeliverooGetInput,
): Promise<Result<DeliverooGetResponse>> {
  const op = "deliverooGet"
  const parsed = v.safeParse(deliverooGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid deliverooGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/deliveroo",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: deliverooGetResponseSchema,
  })
}
