/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleSearchFlightsGetInput,
  googleSearchFlightsGetInputSchema,
} from "./googleSearchFlightsGetInputSchema.js"
import {
  type GoogleSearchFlightsGetResponse,
  googleSearchFlightsGetResponseSchema,
} from "./googleSearchFlightsGetResponseSchema.js"

export async function googleSearchFlightsGet(
  client: OutscraperClient,
  input: GoogleSearchFlightsGetInput,
): Promise<Result<GoogleSearchFlightsGetResponse>> {
  const op = "googleSearchFlightsGet"
  const parsed = v.safeParse(googleSearchFlightsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleSearchFlightsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-search-flights",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleSearchFlightsGetResponseSchema,
  })
}
