/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TrustpilotSearchGetInput, trustpilotSearchGetInputSchema } from "./trustpilotSearchGetInputSchema.js"
import {
  type TrustpilotSearchGetResponse,
  trustpilotSearchGetResponseSchema,
} from "./trustpilotSearchGetResponseSchema.js"

export async function trustpilotSearchGet(
  client: OutscraperClient,
  input: TrustpilotSearchGetInput,
): Promise<Result<TrustpilotSearchGetResponse>> {
  const op = "trustpilotSearchGet"
  const parsed = v.safeParse(trustpilotSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid trustpilotSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/trustpilot-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: trustpilotSearchGetResponseSchema,
  })
}
