/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const companyWebsiteFinderGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          company_name: v.optional(v.nullable(v.string())),
          confidence_score: v.optional(v.nullable(v.number())),
          domain: v.optional(v.nullable(v.string())),
          query: v.optional(v.nullable(v.string())),
          website: v.optional(v.nullable(v.string())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type CompanyWebsiteFinderGetResponse = v.InferOutput<typeof companyWebsiteFinderGetResponseSchema>
