/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type DeliverooReviewsGetInput, deliverooReviewsGetInputSchema } from "./deliverooReviewsGetInputSchema.js"
import {
  type DeliverooReviewsGetResponse,
  deliverooReviewsGetResponseSchema,
} from "./deliverooReviewsGetResponseSchema.js"

export async function deliverooReviewsGet(
  client: OutscraperClient,
  input: DeliverooReviewsGetInput,
): Promise<Result<DeliverooReviewsGetResponse>> {
  const op = "deliverooReviewsGet"
  const parsed = v.safeParse(deliverooReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid deliverooReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/deliveroo-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: deliverooReviewsGetResponseSchema,
  })
}
