/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type ProducthuntReviewsGetInput,
  producthuntReviewsGetInputSchema,
} from "./producthuntReviewsGetInputSchema.js"
import {
  type ProducthuntReviewsGetResponse,
  producthuntReviewsGetResponseSchema,
} from "./producthuntReviewsGetResponseSchema.js"

export async function producthuntReviewsGet(
  client: OutscraperClient,
  input: ProducthuntReviewsGetInput,
): Promise<Result<ProducthuntReviewsGetResponse>> {
  const op = "producthuntReviewsGet"
  const parsed = v.safeParse(producthuntReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid producthuntReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/producthunt-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: producthuntReviewsGetResponseSchema,
  })
}
