/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const producthuntReviewsGetResponseSchema = v.union([
  v.looseObject({ $ref: v.optional(v.nullable(v.string())) }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type ProducthuntReviewsGetResponse = v.InferOutput<typeof producthuntReviewsGetResponseSchema>
