/* Generated by openApiCatalogGenerate. Do not edit. */
export const webhookCallsGetDefinition = {
  description: "Fetch the latest 100 failed webhook calls during the last 24 hours",
  folder: "get-webhook-calls",
  method: "GET",
  operationId: "getWebhook-Calls",
  parameters: [],
  path: "/webhook-calls",
  responses: [
    {
      content: [
        {
          example: [
            {
              date: 1722949581,
              status: "Status code: 404",
            },
          ],
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Failed Webhooks.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Failed Webhook Calls",
  tags: ["Platform & Dashboard"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X GET "https://api.outscraper.cloud/webhook-calls" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
