/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const webhookCallsGetResponseSchema = v.array(
  v.looseObject({ date: v.optional(v.nullable(v.number())), status: v.optional(v.nullable(v.string())) }),
)

export type WebhookCallsGetResponse = v.InferOutput<typeof webhookCallsGetResponseSchema>
