/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type WebhookCallsGetInput, webhookCallsGetInputSchema } from "./webhookCallsGetInputSchema.js"
import { type WebhookCallsGetResponse, webhookCallsGetResponseSchema } from "./webhookCallsGetResponseSchema.js"

export async function webhookCallsGet(
  client: OutscraperClient,
  input: WebhookCallsGetInput = {},
): Promise<Result<WebhookCallsGetResponse>> {
  const op = "webhookCallsGet"
  const parsed = v.safeParse(webhookCallsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid webhookCallsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/webhook-calls",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: webhookCallsGetResponseSchema,
  })
}
