/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const businessesBusinessIdGetResponseSchema = v.looseObject({})

export type BusinessesBusinessIdGetResponse = v.InferOutput<typeof businessesBusinessIdGetResponseSchema>
