/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const businessesBusinessIdGetInputSchema =
  /* businessesBusinessIdGet input is grouped by HTTP argument location. */
  v.object({
    path: v.looseObject({ business_id: v.string() }),
    query: v.optional(v.looseObject({ fields: v.optional(v.string()) }), {}),
    headers: v.optional(v.looseObject({}), {}),
  })

export type BusinessesBusinessIdGetInput = v.InferInput<typeof businessesBusinessIdGetInputSchema>
