/* Generated by openApiCatalogGenerate. Do not edit. */
export const similarwebGetDefinition = {
  description:
    "Returns website analytics data including traffic, rankings, audience insights, and competitive intelligence from SimilarWeb.",
  folder: "get-similarweb",
  method: "GET",
  operationId: "getSimilarweb",
  parameters: [
    {
      description:
        "The parameter defines the way you want to submit your task to Outscraper. It can be set to `false` to open an HTTP connection and keep it open until you get your results, or `true` (default) to just submit your requests to Outscraper and retrieve them later (usually within 1-3 minutes) with the [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.\n\nA good practice is to send async requests and start checking the results after the estimated execution time. Check out [this](https://github.com/outscraper/outscraper-python/blob/master/examples/Run%20Async%20Requests.md) Python implementation as an example.\n\nAs most of the requests take some time to be executed the `async=true` option is preferred to avoid HTTP request timeouts.",
      example: false,
      in: "query",
      location: "query",
      name: "async",
      required: true,
      schema: {
        default: true,
        type: "boolean",
      },
    },
    {
      description:
        "Domains or websites (e.g., `apple.com`, `https://www.google.com/`). \n\nIt supports batching by sending arrays with up to `1000` queries (e.g., `query=text1&query=text2&query=text3`). It allows multiple queries to be sent in one request and to save on network latency time.",
      in: "query",
      location: "query",
      name: "domain",
      required: true,
      schema: {
        collectionFormat: "csv",
        items: {
          type: "string",
        },
        type: "array",
      },
    },
    {
      description:
        "The parameter defines which fields you want to include with each item returned in the response. By default, it returns all fields. Use `&fields=query,name` to return only the specific ones.",
      in: "query",
      location: "query",
      name: "fields",
      required: false,
      schema: {
        type: "string",
      },
    },
    {
      description:
        "The parameter defines the format of the output data. Using this parameter overwrites the `ui` parameter to `true`.",
      in: "query",
      location: "query",
      name: "format",
      required: false,
      schema: {
        collectionFormat: "csv",
        items: {
          default: "xlsx",
          enum: ["xlsx", "csv", "json", "parquet"],
          type: "string",
        },
        type: "array",
      },
    },
    {
      description:
        "The parameter defines whether a task will be executed as a UI task. This is commonly used when you want to create a regular platform task with API.\n\nUsing this parameter overwrites the `async` parameter to `true`.",
      in: "query",
      location: "query",
      name: "ui",
      required: false,
      schema: {
        default: false,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines the URL address (callback) to which Outscraper will create a POST request with a JSON body once a task/request is finished.\n\nUsing this parameter overwrites the webhook from integrations.",
      in: "query",
      location: "query",
      name: "webhook",
      required: false,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/similarweb",
  responses: [
    {
      content: [
        {
          example: {
            data: [
              {
                overview: {
                  bounce_rate: 0.5243936157809659,
                  category_rank: 1,
                  category_rank_change: 0,
                  company_employees_min: 10001,
                  company_name: "Apple",
                  company_revenue_min: 1000000000,
                  company_year_founded: 1976,
                  country_alpha2_code: "US",
                  country_rank: 66,
                  country_rank_change: 3,
                  global_rank: 87,
                  global_rank_change: 1,
                  pages_per_visit: 3.117111176387203,
                  visits_avg_duration_formatted: "00:02:27",
                },
                query: "apple.com",
              },
            ],
            id: "your-request-id",
            status: "Success",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: {},
      status: "200",
    },
    {
      content: [
        {
          example: {
            id: "your-request-id",
            results_location: "https://api.outscraper.cloud/requests/your-request-id",
            status: "Pending",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description:
        "The response contains a request ID that can be used to fetch results by using [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.",
      status: "202",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage: "Please close past due invoices or verify your card information is correct.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Past due invoices or a payment method not connected.",
      status: "402",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Invalid query URL parameters.",
      status: "422",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "SimilarWeb Scraper",
  tags: ["Domain Related"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source:
        'curl -X GET "https://api.outscraper.cloud/similarweb?query=apple.com&country=US&async=false" -H  "X-API-KEY: YOUR-API-KEY"',
    },
    {
      lang: "cURL (async)",
      source:
        'curl -X GET "https://api.outscraper.cloud/similarweb?query=apple.com&country=US" -H  "X-API-KEY: YOUR-API-KEY"',
    },
    {
      lang: "Python",
      source:
        "from outscraper import OutscraperClient\n\napi_client = OutscraperClient(api_key='YOUR-API-KEY')\nresults = api_client.similarweb(['apple.com'], country='US')",
    },
    {
      lang: "Ruby",
      source:
        "require 'Outscraper'\n\nclient = Outscraper::Client.new('SECRET_API_KEY')\nresults = client.similarweb('apple.com', country: 'US')",
    },
    {
      lang: "PHP",
      source:
        "$client = new OutscraperClient('YOUR-API-KEY');\n$results = $client->similarweb(['apple.com'], $country='US');",
    },
    {
      lang: "Node.js",
      source:
        "const Outscraper = require('outscraper');\n\nlet client = new Outscraper('YOUR-API-KEY');\nclient.similarweb(['apple.com'], {country: 'US'}).then(response => {\n   console.log(response);\n});",
    },
    {
      lang: "Go",
      source:
        'import "github.com/outscraper/outscraper-go"\n\nclient := outscraper.Client{ApiKey: "SECRET_API_KEY"}\nresults, _ := client.SimilarWeb(map[string]string {\n    "query": "apple.com",\n    "country": "US",\n})',
    },
    {
      lang: "Java",
      source:
        'OutscraperClient client = new OutscraperClient("SECRET_API_KEY");\nJSONArray results = client.similarweb(new HashMap<String, Object>() {{\n    put("query", "apple.com");\n    put("country", "US");\n}});',
    },
  ],
} as const
