/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const similarwebGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          overview: v.optional(
            v.looseObject({
              bounce_rate: v.optional(v.unknown()),
              category_rank: v.optional(v.unknown()),
              category_rank_change: v.optional(v.unknown()),
              company_employees_min: v.optional(v.unknown()),
              company_name: v.optional(v.unknown()),
              company_revenue_min: v.optional(v.unknown()),
              company_year_founded: v.optional(v.unknown()),
              country_alpha2_code: v.optional(v.unknown()),
              country_rank: v.optional(v.unknown()),
              country_rank_change: v.optional(v.unknown()),
              global_rank: v.optional(v.unknown()),
              global_rank_change: v.optional(v.unknown()),
              pages_per_visit: v.optional(v.unknown()),
              visits_avg_duration_formatted: v.optional(v.unknown()),
            }),
          ),
          query: v.optional(v.nullable(v.string())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type SimilarwebGetResponse = v.InferOutput<typeof similarwebGetResponseSchema>
