/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type SimilarwebGetInput, similarwebGetInputSchema } from "./similarwebGetInputSchema.js"
import { type SimilarwebGetResponse, similarwebGetResponseSchema } from "./similarwebGetResponseSchema.js"

export async function similarwebGet(
  client: OutscraperClient,
  input: SimilarwebGetInput,
): Promise<Result<SimilarwebGetResponse>> {
  const op = "similarwebGet"
  const parsed = v.safeParse(similarwebGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid similarwebGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/similarweb",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: similarwebGetResponseSchema,
  })
}
