/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GlassdoorReviewsGetInput, glassdoorReviewsGetInputSchema } from "./glassdoorReviewsGetInputSchema.js"
import {
  type GlassdoorReviewsGetResponse,
  glassdoorReviewsGetResponseSchema,
} from "./glassdoorReviewsGetResponseSchema.js"

export async function glassdoorReviewsGet(
  client: OutscraperClient,
  input: GlassdoorReviewsGetInput,
): Promise<Result<GlassdoorReviewsGetResponse>> {
  const op = "glassdoorReviewsGet"
  const parsed = v.safeParse(glassdoorReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid glassdoorReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/glassdoor-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: glassdoorReviewsGetResponseSchema,
  })
}
