/* Generated by openApiCatalogGenerate. Do not edit. */
export const tasksTaskIdPutDefinition = {
  description: "Allows you to recreate tasks.",
  folder: "put-tasks-task-id",
  method: "PUT",
  operationId: "putTasks-TaskId",
  parameters: [
    {
      description: "Task ID. Example: `20211211132758c8e9`",
      in: "path",
      location: "path",
      name: "taskId",
      required: true,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/tasks/{taskId}",
  responses: [
    {
      content: [
        {
          example: "Task restarted",
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Task restarted.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Restart Task",
  tags: ["Platform & Dashboard"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X PUT "https://api.outscraper.cloud/tasks/your-task-id"',
    },
  ],
} as const
