/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TasksTaskIdPutInput, tasksTaskIdPutInputSchema } from "./tasksTaskIdPutInputSchema.js"
import { type TasksTaskIdPutResponse, tasksTaskIdPutResponseSchema } from "./tasksTaskIdPutResponseSchema.js"

export async function tasksTaskIdPut(
  client: OutscraperClient,
  input: TasksTaskIdPutInput,
): Promise<Result<TasksTaskIdPutResponse>> {
  const op = "tasksTaskIdPut"
  const parsed = v.safeParse(tasksTaskIdPutInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid tasksTaskIdPut input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/tasks/{taskId}",
    method: "PUT",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: tasksTaskIdPutResponseSchema,
  })
}
