/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksTaskIdPutResponseSchema = v.string()

export type TasksTaskIdPutResponse = v.InferOutput<typeof tasksTaskIdPutResponseSchema>
