/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type YahooSearchGetInput, yahooSearchGetInputSchema } from "./yahooSearchGetInputSchema.js"
import { type YahooSearchGetResponse, yahooSearchGetResponseSchema } from "./yahooSearchGetResponseSchema.js"

export async function yahooSearchGet(
  client: OutscraperClient,
  input: YahooSearchGetInput,
): Promise<Result<YahooSearchGetResponse>> {
  const op = "yahooSearchGet"
  const parsed = v.safeParse(yahooSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid yahooSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/yahoo-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: yahooSearchGetResponseSchema,
  })
}
