/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const capterraReviewsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            completenessScore: v.optional(v.unknown()),
            cons: v.optional(v.unknown()),
            easeOfUseRating: v.optional(v.unknown()),
            functionalityRating: v.optional(v.unknown()),
            id: v.optional(v.unknown()),
            overallRating: v.optional(v.unknown()),
            profilePictureUrl: v.optional(v.unknown()),
            pros: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            recommendationRating: v.optional(v.unknown()),
            reviewerCompanySize: v.optional(v.unknown()),
            reviewerFirstName: v.optional(v.unknown()),
            reviewerIndustry: v.optional(v.unknown()),
            reviewerJobTitle: v.optional(v.unknown()),
            reviewerLastName: v.optional(v.unknown()),
            timeUsedProduct: v.optional(v.unknown()),
            title: v.optional(v.unknown()),
            valueForMoneyRating: v.optional(v.unknown()),
            writtenOn: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type CapterraReviewsGetResponse = v.InferOutput<typeof capterraReviewsGetResponseSchema>
