/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type CapterraReviewsGetInput, capterraReviewsGetInputSchema } from "./capterraReviewsGetInputSchema.js"
import {
  type CapterraReviewsGetResponse,
  capterraReviewsGetResponseSchema,
} from "./capterraReviewsGetResponseSchema.js"

export async function capterraReviewsGet(
  client: OutscraperClient,
  input: CapterraReviewsGetInput,
): Promise<Result<CapterraReviewsGetResponse>> {
  const op = "capterraReviewsGet"
  const parsed = v.safeParse(capterraReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid capterraReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/capterra-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: capterraReviewsGetResponseSchema,
  })
}
