/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googlePlayReviewsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            author_id: v.optional(v.unknown()),
            author_image: v.optional(v.unknown()),
            author_title: v.optional(v.unknown()),
            owner_answer: v.optional(v.unknown()),
            owner_answer_timestamp: v.optional(v.unknown()),
            owner_answer_timestamp_datetime_utc: v.optional(v.unknown()),
            review_datetime_utc: v.optional(v.unknown()),
            review_likes: v.optional(v.unknown()),
            review_rating: v.optional(v.unknown()),
            review_text: v.optional(v.unknown()),
            review_timestamp: v.optional(v.unknown()),
            version: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type GooglePlayReviewsGetResponse = v.InferOutput<typeof googlePlayReviewsGetResponseSchema>
