/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleMapsAutocompleteGetInput,
  googleMapsAutocompleteGetInputSchema,
} from "./googleMapsAutocompleteGetInputSchema.js"
import {
  type GoogleMapsAutocompleteGetResponse,
  googleMapsAutocompleteGetResponseSchema,
} from "./googleMapsAutocompleteGetResponseSchema.js"

export async function googleMapsAutocompleteGet(
  client: OutscraperClient,
  input: GoogleMapsAutocompleteGetInput,
): Promise<Result<GoogleMapsAutocompleteGetResponse>> {
  const op = "googleMapsAutocompleteGet"
  const parsed = v.safeParse(googleMapsAutocompleteGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleMapsAutocompleteGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-maps-autocomplete",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleMapsAutocompleteGetResponseSchema,
  })
}
