/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googleMapsAutocompleteGetResponseSchema = v.looseObject({
  id: v.optional(v.nullable(v.string())),
  results_location: v.optional(v.nullable(v.string())),
  status: v.optional(v.nullable(v.string())),
})

export type GoogleMapsAutocompleteGetResponse = v.InferOutput<typeof googleMapsAutocompleteGetResponseSchema>
