/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googleSearchGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          ads: v.optional(v.array(v.unknown())),
          organic_results: v.optional(v.array(v.unknown())),
          query: v.optional(v.nullable(v.string())),
          related_questions: v.optional(v.array(v.unknown())),
          shopping_results: v.optional(v.array(v.unknown())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type GoogleSearchGetResponse = v.InferOutput<typeof googleSearchGetResponseSchema>
