/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GoogleSearchGetInput, googleSearchGetInputSchema } from "./googleSearchGetInputSchema.js"
import { type GoogleSearchGetResponse, googleSearchGetResponseSchema } from "./googleSearchGetResponseSchema.js"

export async function googleSearchGet(
  client: OutscraperClient,
  input: GoogleSearchGetInput,
): Promise<Result<GoogleSearchGetResponse>> {
  const op = "googleSearchGet"
  const parsed = v.safeParse(googleSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleSearchGetResponseSchema,
  })
}
