/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const expediaSearchGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(v.array(v.unknown())),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type ExpediaSearchGetResponse = v.InferOutput<typeof expediaSearchGetResponseSchema>
