/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type ExpediaSearchGetInput, expediaSearchGetInputSchema } from "./expediaSearchGetInputSchema.js"
import { type ExpediaSearchGetResponse, expediaSearchGetResponseSchema } from "./expediaSearchGetResponseSchema.js"

export async function expediaSearchGet(
  client: OutscraperClient,
  input: ExpediaSearchGetInput,
): Promise<Result<ExpediaSearchGetResponse>> {
  const op = "expediaSearchGet"
  const parsed = v.safeParse(expediaSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid expediaSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/expedia-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: expediaSearchGetResponseSchema,
  })
}
