/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GoogleSearchNewsGetInput, googleSearchNewsGetInputSchema } from "./googleSearchNewsGetInputSchema.js"
import {
  type GoogleSearchNewsGetResponse,
  googleSearchNewsGetResponseSchema,
} from "./googleSearchNewsGetResponseSchema.js"

export async function googleSearchNewsGet(
  client: OutscraperClient,
  input: GoogleSearchNewsGetInput,
): Promise<Result<GoogleSearchNewsGetResponse>> {
  const op = "googleSearchNewsGet"
  const parsed = v.safeParse(googleSearchNewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleSearchNewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-search-news",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleSearchNewsGetResponseSchema,
  })
}
