/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type RequestsRequestIdGetInput, requestsRequestIdGetInputSchema } from "./requestsRequestIdGetInputSchema.js"
import {
  type RequestsRequestIdGetResponse,
  requestsRequestIdGetResponseSchema,
} from "./requestsRequestIdGetResponseSchema.js"

export async function requestsRequestIdGet(
  client: OutscraperClient,
  input: RequestsRequestIdGetInput,
): Promise<Result<RequestsRequestIdGetResponse>> {
  const op = "requestsRequestIdGet"
  const parsed = v.safeParse(requestsRequestIdGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid requestsRequestIdGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/requests/{requestId}",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: requestsRequestIdGetResponseSchema,
  })
}
