/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const requestsRequestIdGetInputSchema =
  /* requestsRequestIdGet input is grouped by HTTP argument location. */
  v.object({
    path: v.looseObject({ requestId: v.string() }),
    query: v.optional(
      v.looseObject({ convertFileResult: v.optional(v.boolean(), true), flat: v.optional(v.boolean(), false) }),
      {},
    ),
    headers: v.optional(v.looseObject({}), {}),
  })

export type RequestsRequestIdGetInput = v.InferInput<typeof requestsRequestIdGetInputSchema>
