/* Generated by openApiCatalogGenerate. Do not edit. */
export const locationsGetDefinition = {
  description: "Fetch country locations that you can use to search on Google Maps.",
  folder: "get-locations",
  method: "GET",
  operationId: "getLocations",
  parameters: [],
  path: "/locations",
  responses: [
    {
      content: [
        {
          example: {
            items: [
              {
                children: [],
                title: "Abruzzi",
                value: "IT>Abruzzi",
              },
            ],
            supports_zip_codes: true,
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Country Locations.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Get Country Locations",
  tags: ["Platform & Dashboard"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X GET "https://api.outscraper.cloud/locations?country=IT" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
