/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type LocationsGetInput, locationsGetInputSchema } from "./locationsGetInputSchema.js"
import { type LocationsGetResponse, locationsGetResponseSchema } from "./locationsGetResponseSchema.js"

export async function locationsGet(
  client: OutscraperClient,
  input: LocationsGetInput = {},
): Promise<Result<LocationsGetResponse>> {
  const op = "locationsGet"
  const parsed = v.safeParse(locationsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid locationsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/locations",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: locationsGetResponseSchema,
  })
}
