/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const locationsGetResponseSchema = v.looseObject({
  items: v.optional(
    v.array(
      v.looseObject({
        children: v.optional(v.array(v.unknown())),
        title: v.optional(v.nullable(v.string())),
        value: v.optional(v.nullable(v.string())),
      }),
    ),
  ),
  supports_zip_codes: v.optional(v.nullable(v.boolean())),
})

export type LocationsGetResponse = v.InferOutput<typeof locationsGetResponseSchema>
