/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GetappReviewsGetInput, getappReviewsGetInputSchema } from "./getappReviewsGetInputSchema.js"
import { type GetappReviewsGetResponse, getappReviewsGetResponseSchema } from "./getappReviewsGetResponseSchema.js"

export async function getappReviewsGet(
  client: OutscraperClient,
  input: GetappReviewsGetInput,
): Promise<Result<GetappReviewsGetResponse>> {
  const op = "getappReviewsGet"
  const parsed = v.safeParse(getappReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid getappReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/getapp-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: getappReviewsGetResponseSchema,
  })
}
