/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type HotelsSearchGetInput, hotelsSearchGetInputSchema } from "./hotelsSearchGetInputSchema.js"
import { type HotelsSearchGetResponse, hotelsSearchGetResponseSchema } from "./hotelsSearchGetResponseSchema.js"

export async function hotelsSearchGet(
  client: OutscraperClient,
  input: HotelsSearchGetInput,
): Promise<Result<HotelsSearchGetResponse>> {
  const op = "hotelsSearchGet"
  const parsed = v.safeParse(hotelsSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid hotelsSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/hotels-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: hotelsSearchGetResponseSchema,
  })
}
