/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type AirbnbReviewsGetInput, airbnbReviewsGetInputSchema } from "./airbnbReviewsGetInputSchema.js"
import { type AirbnbReviewsGetResponse, airbnbReviewsGetResponseSchema } from "./airbnbReviewsGetResponseSchema.js"

export async function airbnbReviewsGet(
  client: OutscraperClient,
  input: AirbnbReviewsGetInput,
): Promise<Result<AirbnbReviewsGetResponse>> {
  const op = "airbnbReviewsGet"
  const parsed = v.safeParse(airbnbReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid airbnbReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/airbnb-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: airbnbReviewsGetResponseSchema,
  })
}
