/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const trustpilotReviewsGetInputSchema =
  /* trustpilotReviewsGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      cutoff: v.optional(v.pipe(v.number(), v.integer())),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      languages: v.optional(
        v.union([v.literal("default"), v.literal("all"), v.literal("en"), v.literal("es"), v.literal("de")]),
        "default",
      ),
      limit: v.optional(v.pipe(v.number(), v.integer()), 100),
      query: v.array(v.string()),
      skip: v.optional(v.pipe(v.number(), v.integer()), 0),
      sort: v.optional(v.literal("recency")),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type TrustpilotReviewsGetInput = v.InferInput<typeof trustpilotReviewsGetInputSchema>
