/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const trustpilotReviewsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            author_country_code: v.optional(v.unknown()),
            author_id: v.optional(v.unknown()),
            author_reviews_number: v.optional(v.unknown()),
            author_reviews_number_same_domain: v.optional(v.unknown()),
            author_title: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            review_date: v.optional(v.unknown()),
            review_id: v.optional(v.unknown()),
            review_likes: v.optional(v.unknown()),
            review_rating: v.optional(v.unknown()),
            review_text: v.optional(v.unknown()),
            review_title: v.optional(v.unknown()),
            total_reviews: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type TrustpilotReviewsGetResponse = v.InferOutput<typeof trustpilotReviewsGetResponseSchema>
