/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TrustpilotReviewsGetInput, trustpilotReviewsGetInputSchema } from "./trustpilotReviewsGetInputSchema.js"
import {
  type TrustpilotReviewsGetResponse,
  trustpilotReviewsGetResponseSchema,
} from "./trustpilotReviewsGetResponseSchema.js"

export async function trustpilotReviewsGet(
  client: OutscraperClient,
  input: TrustpilotReviewsGetInput,
): Promise<Result<TrustpilotReviewsGetResponse>> {
  const op = "trustpilotReviewsGet"
  const parsed = v.safeParse(trustpilotReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid trustpilotReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/trustpilot-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: trustpilotReviewsGetResponseSchema,
  })
}
