/* Generated by openApiCatalogGenerate. Do not edit. */
export const trustpilotReviewsGetDefinition = {
  description:
    "Returns reviews from Trustpilot businesses.\n\nIn case no reviews were found by your search criteria, your search request will consume the usage of one review.",
  folder: "get-trustpilot-reviews",
  method: "GET",
  operationId: "getTrustpilot-Reviews",
  parameters: [
    {
      description:
        "The parameter defines the way you want to submit your task to Outscraper. It can be set to `false` to open an HTTP connection and keep it open until you get your results, or `true` (default) to just submit your requests to Outscraper and retrieve them later (usually within 1-3 minutes) with the [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.\n\nA good practice is to send async requests and start checking the results after the estimated execution time. Check out [this](https://github.com/outscraper/outscraper-python/blob/master/examples/Run%20Async%20Requests.md) Python implementation as an example.\n\nAs most of the requests take some time to be executed the `async=true` option is preferred to avoid HTTP request timeouts.",
      example: false,
      in: "query",
      location: "query",
      name: "async",
      required: true,
      schema: {
        default: true,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter specifies the oldest timestamp value for items. \n\nUsing the `cutoff` parameter overwrites `sort` parameter`. Therefore, the latest records will be at the beginning (newest first).",
      in: "query",
      location: "query",
      name: "cutoff",
      required: false,
      schema: {
        type: "integer",
      },
    },
    {
      description:
        "The parameter defines which fields you want to include with each item returned in the response. By default, it returns all fields. Use `&fields=query,name` to return only the specific ones.",
      in: "query",
      location: "query",
      name: "fields",
      required: false,
      schema: {
        type: "string",
      },
    },
    {
      description:
        "The parameter defines the format of the output data. Using this parameter overwrites the `ui` parameter to `true`.",
      in: "query",
      location: "query",
      name: "format",
      required: false,
      schema: {
        collectionFormat: "csv",
        items: {
          default: "xlsx",
          enum: ["xlsx", "csv", "json", "parquet"],
          type: "string",
        },
        type: "array",
      },
    },
    {
      description: "The parameter specifies one of the language filters.",
      in: "query",
      location: "query",
      name: "languages",
      required: false,
      schema: {
        default: "default",
        enum: ["default", "all", "en", "es", "de"],
        type: "string",
      },
    },
    {
      description: "The parameter specifies the limit of reviews to get from one query.",
      in: "query",
      location: "query",
      name: "limit",
      required: false,
      schema: {
        default: 100,
        type: "integer",
      },
    },
    {
      description:
        "Links to Trustpilot pages or domain names (e.g., `outscraper.com`, `https://www.trustpilot.com/review/outscraper.com`). \n\nIt supports batching by sending arrays with up to `1000` queries (e.g., `query=text1&query=text2&query=text3`). It allows multiple queries to be sent in one request and to save on network latency time.",
      in: "query",
      location: "query",
      name: "query",
      required: true,
      schema: {
        collectionFormat: "csv",
        items: {
          type: "string",
        },
        type: "array",
      },
    },
    {
      description: "Number of items to skip. Must be a multiple of 20 (e.g., 0, 20, 40). Used for pagination.",
      in: "query",
      location: "query",
      name: "skip",
      required: false,
      schema: {
        default: 0,
        type: "integer",
      },
    },
    {
      description: "The parameter specifies one of the sorting types.",
      in: "query",
      location: "query",
      name: "sort",
      required: false,
      schema: {
        default: "",
        enum: ["recency"],
        type: "string",
      },
    },
    {
      description:
        "The parameter defines whether a task will be executed as a UI task. This is commonly used when you want to create a regular platform task with API.\n\nUsing this parameter overwrites the `async` parameter to `true`.",
      in: "query",
      location: "query",
      name: "ui",
      required: false,
      schema: {
        default: false,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines the URL address (callback) to which Outscraper will create a POST request with a JSON body once a task/request is finished.\n\nUsing this parameter overwrites the webhook from integrations.",
      in: "query",
      location: "query",
      name: "webhook",
      required: false,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/trustpilot-reviews",
  responses: [
    {
      content: [
        {
          example: {
            data: [
              [
                {
                  author_country_code: "GB",
                  author_id: "570fd83f0000ff000a17730a",
                  author_reviews_number: 7,
                  author_reviews_number_same_domain: 1,
                  author_title: "James Morton",
                  query: "outscraper.com",
                  review_date: 1675562103,
                  review_id: "63def0579b64b1bdaf4d4895",
                  review_likes: 0,
                  review_rating: 5,
                  review_text:
                    "Extremely easy to use API and very well documented - I've been using Outscraper for Google My Business review scraping to display reviews on our customers websites for the past two years with no issues whatsoever. Hope Facebook Page and Trustpilot reviews are added so that I can have everything within one place!",
                  review_title: "Extremely easy to use API and very well documented",
                  total_reviews: 16,
                },
                {
                  author_country_code: "US",
                  author_id: "63cacc929e3a180012b87a70",
                  author_reviews_number: 1,
                  author_reviews_number_same_domain: 1,
                  author_title: "John Kofax",
                  query: "outscraper.com",
                  review_date: 1674242416,
                  review_id: "63cacd504b01fb3f5488166f",
                  review_likes: 0,
                  review_rating: 5,
                  review_text:
                    "Powerful tool, and a very responsive team. If used properly it produces excellent results. I have been using this service for 2 weeks since then their team has responded to all of my questions within 24 hours or faster.",
                  review_title: "Powerful tool",
                  total_reviews: 16,
                },
              ],
            ],
            id: "your-request-id",
            status: "Success",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: {},
      status: "200",
    },
    {
      content: [
        {
          example: {
            id: "your-request-id",
            results_location: "https://api.outscraper.cloud/requests/your-request-id",
            status: "Pending",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description:
        "The response contains a request ID that can be used to fetch results by using [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.",
      status: "202",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage: "Please close past due invoices or verify your card information is correct.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Past due invoices or a payment method not connected.",
      status: "402",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Invalid query URL parameters.",
      status: "422",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Trustpilot Reviews",
  tags: ["Trustpilot", "Reviews & Comments"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source:
        'curl -X GET "https://api.outscraper.cloud/trustpilot-reviews?query=outscraper.com&limit=3&async=false" -H  "X-API-KEY: YOUR-API-KEY"',
    },
    {
      lang: "cURL (async)",
      source:
        'curl -X GET "https://api.outscraper.cloud/trustpilot-reviews?query=outscraper.com&limit=3" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
