/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const requestsGetResponseSchema = v.array(
  v.looseObject({ id: v.optional(v.nullable(v.string())), usage: v.optional(v.nullable(v.string())) }),
)

export type RequestsGetResponse = v.InferOutput<typeof requestsGetResponseSchema>
