/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const requestsGetInputSchema =
  /* requestsGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.optional(
      v.looseObject({
        pageSize: v.optional(v.pipe(v.number(), v.integer()), 20),
        skip: v.optional(v.pipe(v.number(), v.integer()), 0),
        type: v.optional(v.union([v.literal("running"), v.literal("finished")]), "running"),
      }),
      {},
    ),
    headers: v.optional(v.looseObject({}), {}),
  })

export type RequestsGetInput = v.InferInput<typeof requestsGetInputSchema>
