/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type RequestsGetInput, requestsGetInputSchema } from "./requestsGetInputSchema.js"
import { type RequestsGetResponse, requestsGetResponseSchema } from "./requestsGetResponseSchema.js"

export async function requestsGet(
  client: OutscraperClient,
  input: RequestsGetInput = {},
): Promise<Result<RequestsGetResponse>> {
  const op = "requestsGet"
  const parsed = v.safeParse(requestsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid requestsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/requests",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: requestsGetResponseSchema,
  })
}
