/* Generated by openApiCatalogGenerate. Do not edit. */
export const requestsGetDefinition = {
  description: "Fetch up to `100` latest requests during the last `24` hours.",
  folder: "get-requests",
  method: "GET",
  operationId: "getRequests",
  parameters: [
    {
      description: "The parameter specifies the number of requests to return.",
      in: "query",
      location: "query",
      name: "pageSize",
      required: false,
      schema: {
        default: 20,
        type: "integer",
      },
    },
    {
      description: "The parameter specifies the number of items to skip. Used for pagination.",
      in: "query",
      location: "query",
      name: "skip",
      required: false,
      schema: {
        default: 0,
        type: "integer",
      },
    },
    {
      description: "The parameter allows you to filter requests by type (running/finished).",
      in: "query",
      location: "query",
      name: "type",
      required: false,
      schema: {
        default: "running",
        enum: ["running", "finished"],
        type: "string",
      },
    },
  ],
  path: "/requests",
  responses: [
    {
      content: [
        {
          example: [
            {
              id: "79e6d350-c6c9-449c-a890-7fe14f821ebe",
              usage: "3",
            },
            {
              id: "15188338-029a-4d0c-afdd-318e8808d8fe",
              usage: "10",
            },
            {
              id: "fd96b82c-6b37-49f0-b69f-b5c793d28284",
              usage: "12",
            },
          ],
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Your latest request.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Requests History",
  tags: ["Requests"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X GET "https://api.outscraper.cloud/requests?type=finished" -H  "X-API-KEY: YOUR-API-KEY"',
    },
    {
      lang: "Python",
      source:
        "from outscraper import OutscraperClient\n\napi_client = OutscraperClient(api_key='YOUR-API-KEY')\nresults = api_client.get_requests_history('finished')",
    },
    {
      lang: "Node.js",
      source:
        "const Outscraper = require('outscraper');\n\nlet client = new Outscraper('YOUR-API-KEY');\nclient.getRequestsHistory('finished').then(response => {\n   console.log(response);\n});",
    },
  ],
} as const
