/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TargetReviewsGetInput, targetReviewsGetInputSchema } from "./targetReviewsGetInputSchema.js"
import { type TargetReviewsGetResponse, targetReviewsGetResponseSchema } from "./targetReviewsGetResponseSchema.js"

export async function targetReviewsGet(
  client: OutscraperClient,
  input: TargetReviewsGetInput,
): Promise<Result<TargetReviewsGetResponse>> {
  const op = "targetReviewsGet"
  const parsed = v.safeParse(targetReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid targetReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/target-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: targetReviewsGetResponseSchema,
  })
}
