/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const targetReviewsGetInputSchema =
  /* targetReviewsGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      cutoff: v.optional(v.pipe(v.number(), v.integer())),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      limit: v.optional(v.pipe(v.number(), v.integer()), 100),
      query: v.array(v.string()),
      sort: v.optional(
        v.union([
          v.literal("most_recent"),
          v.literal("highest_rating"),
          v.literal("lowest_rating"),
          v.literal("helpfulness_desc"),
        ]),
        "most_recent",
      ),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type TargetReviewsGetInput = v.InferInput<typeof targetReviewsGetInputSchema>
