/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TasksPostInput, tasksPostInputSchema } from "./tasksPostInputSchema.js"
import { type TasksPostResponse, tasksPostResponseSchema } from "./tasksPostResponseSchema.js"

export async function tasksPost(
  client: OutscraperClient,
  input: TasksPostInput = {},
): Promise<Result<TasksPostResponse>> {
  const op = "tasksPost"
  const parsed = v.safeParse(tasksPostInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid tasksPost input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/tasks",
    method: "POST",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,
    body: value.body,
    contentType: "application/json",
    schema: tasksPostResponseSchema,
  })
}
