/* Generated by openApiCatalogGenerate. Do not edit. */
export const tasksPostDefinition = {
  description: "Allows you to create UI tasks.",
  folder: "post-tasks",
  method: "POST",
  operationId: "postTasks",
  parameters: [],
  path: "/tasks",
  requestBody: {
    content: [
      {
        mediaType: "application/json",
        schema: {
          example: {
            UISettings: {
              isCustomCategories: false,
              isCustomLocations: false,
              isCustomQueries: false,
            },
            categories: ["restaurant", "dentist"],
            dropDuplicates: true,
            dropEmailDuplicates: false,
            enrich: false,
            enrichLocations: true,
            enrichments: ["domains_service", "company_insights_service"],
            exactMatch: false,
            filters: [],
            ignoreWithoutEmails: false,
            language: "en",
            limit: 0,
            locations: ["SE>Stockholm"],
            organizationsPerQueryLimit: 500,
            queries: [],
            region: "SE",
            service_name: "google_maps_service_v2",
            settings: {
              output_columns: [],
              output_extension: "xlsx",
            },
            tags: ["restaurant +1"],
            useZipCodes: true,
          },
          properties: {
            enrichments: {
              collectionFormat: "csv",
              description:
                "The parameter defines an enrichment or enrichments (e.g., `enrichment=enrichment1&enrichment=enrichment2&enrichment=enrichment3`) you want to apply to the results.\n\nAvailable values: `domains_service`, `emails_validator_service`, `disposable_email_checker`, `whatsapp_checker`, `imessage_checker`, `phones_enricher_service`, `trustpilot_service`, `company_insights_service`, etc.\n\nUse `&enrichment=domains_service&enrichment=emails_validator_service` to enrich data with Emails & Contacts Scraper (domains_service), and Email Address Verifier (emails_validator_service).\n\nIt increases the time of the response.",
              items: {
                type: "string",
              },
              type: "array",
            },
            queries: {
              collectionFormat: "csv",
              description: "Queries to search for (e.g., `restaurants ny usa`, `bars ny usa`).",
              items: {
                type: "string",
              },
              type: "array",
            },
            service_name: {
              description:
                "ID of the service you want to use (e.g., `google_maps_service_v2`, `google_maps_reviews_service_v3`).",
              type: "string",
            },
            tags: {
              collectionFormat: "csv",
              items: {
                type: "string",
              },
              type: "array",
            },
          },
          type: "object",
        },
      },
    ],
    required: false,
  },
  responses: [
    {
      content: [
        {
          example: {
            id: "your-task-id",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Task created.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Create Task",
  tags: ["Platform & Dashboard"],
} as const
