/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksPostResponseSchema = v.looseObject({ id: v.optional(v.nullable(v.string())) })

export type TasksPostResponse = v.InferOutput<typeof tasksPostResponseSchema>
