/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type WalmartReviewsGetInput, walmartReviewsGetInputSchema } from "./walmartReviewsGetInputSchema.js"
import { type WalmartReviewsGetResponse, walmartReviewsGetResponseSchema } from "./walmartReviewsGetResponseSchema.js"

export async function walmartReviewsGet(
  client: OutscraperClient,
  input: WalmartReviewsGetInput,
): Promise<Result<WalmartReviewsGetResponse>> {
  const op = "walmartReviewsGet"
  const parsed = v.safeParse(walmartReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid walmartReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/walmart-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: walmartReviewsGetResponseSchema,
  })
}
