/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksTaskIdDeleteResponseSchema = v.string()

export type TasksTaskIdDeleteResponse = v.InferOutput<typeof tasksTaskIdDeleteResponseSchema>
