/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksTaskIdDeleteInputSchema =
  /* tasksTaskIdDelete input is grouped by HTTP argument location. */
  v.object({
    path: v.looseObject({ taskId: v.string() }),
    query: v.optional(v.looseObject({}), {}),
    headers: v.optional(v.looseObject({}), {}),
  })

export type TasksTaskIdDeleteInput = v.InferInput<typeof tasksTaskIdDeleteInputSchema>
