/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TasksTaskIdDeleteInput, tasksTaskIdDeleteInputSchema } from "./tasksTaskIdDeleteInputSchema.js"
import { type TasksTaskIdDeleteResponse, tasksTaskIdDeleteResponseSchema } from "./tasksTaskIdDeleteResponseSchema.js"

export async function tasksTaskIdDelete(
  client: OutscraperClient,
  input: TasksTaskIdDeleteInput,
): Promise<Result<TasksTaskIdDeleteResponse>> {
  const op = "tasksTaskIdDelete"
  const parsed = v.safeParse(tasksTaskIdDeleteInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid tasksTaskIdDelete input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/tasks/{taskId}",
    method: "DELETE",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: tasksTaskIdDeleteResponseSchema,
  })
}
