/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type LeadsAndContactsGetInput, leadsAndContactsGetInputSchema } from "./leadsAndContactsGetInputSchema.js"
import {
  type LeadsAndContactsGetResponse,
  leadsAndContactsGetResponseSchema,
} from "./leadsAndContactsGetResponseSchema.js"

export async function leadsAndContactsGet(
  client: OutscraperClient,
  input: LeadsAndContactsGetInput,
): Promise<Result<LeadsAndContactsGetResponse>> {
  const op = "leadsAndContactsGet"
  const parsed = v.safeParse(leadsAndContactsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid leadsAndContactsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/leads-and-contacts",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: leadsAndContactsGetResponseSchema,
  })
}
