/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const leadsAndContactsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          contacts: v.optional(v.array(v.unknown())),
          details: v.optional(
            v.looseObject({
              address: v.optional(v.unknown()),
              city: v.optional(v.unknown()),
              country: v.optional(v.unknown()),
              employees: v.optional(v.unknown()),
              founded: v.optional(v.unknown()),
              industry: v.optional(v.unknown()),
              name: v.optional(v.unknown()),
              postal_code: v.optional(v.unknown()),
              sales: v.optional(v.unknown()),
              size: v.optional(v.unknown()),
              state: v.optional(v.unknown()),
              type: v.optional(v.unknown()),
            }),
          ),
          domain: v.optional(v.nullable(v.string())),
          emails: v.optional(v.array(v.unknown())),
          phones: v.optional(v.array(v.unknown())),
          query: v.optional(v.nullable(v.string())),
          site_data: v.optional(
            v.looseObject({
              description: v.optional(v.unknown()),
              generator: v.optional(v.unknown()),
              has_fb_pixel: v.optional(v.unknown()),
              has_google_tag: v.optional(v.unknown()),
              keywords: v.optional(v.unknown()),
              title: v.optional(v.unknown()),
            }),
          ),
          socials: v.optional(
            v.looseObject({
              crunchbase: v.optional(v.unknown()),
              discord: v.optional(v.unknown()),
              facebook: v.optional(v.unknown()),
              github: v.optional(v.unknown()),
              linkedin: v.optional(v.unknown()),
              twitter: v.optional(v.unknown()),
              whatsapp: v.optional(v.unknown()),
              youtube: v.optional(v.unknown()),
            }),
          ),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type LeadsAndContactsGetResponse = v.InferOutput<typeof leadsAndContactsGetResponseSchema>
