/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type ScreenshoterGetInput, screenshoterGetInputSchema } from "./screenshoterGetInputSchema.js"
import { type ScreenshoterGetResponse, screenshoterGetResponseSchema } from "./screenshoterGetResponseSchema.js"

export async function screenshoterGet(
  client: OutscraperClient,
  input: ScreenshoterGetInput,
): Promise<Result<ScreenshoterGetResponse>> {
  const op = "screenshoterGet"
  const parsed = v.safeParse(screenshoterGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid screenshoterGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/screenshoter",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: screenshoterGetResponseSchema,
  })
}
