/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type AppstoreReviewsGetInput, appstoreReviewsGetInputSchema } from "./appstoreReviewsGetInputSchema.js"
import {
  type AppstoreReviewsGetResponse,
  appstoreReviewsGetResponseSchema,
} from "./appstoreReviewsGetResponseSchema.js"

export async function appstoreReviewsGet(
  client: OutscraperClient,
  input: AppstoreReviewsGetInput,
): Promise<Result<AppstoreReviewsGetResponse>> {
  const op = "appstoreReviewsGet"
  const parsed = v.safeParse(appstoreReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid appstoreReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/appstore-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: appstoreReviewsGetResponseSchema,
  })
}
