/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type BookingPricesGetInput, bookingPricesGetInputSchema } from "./bookingPricesGetInputSchema.js"
import { type BookingPricesGetResponse, bookingPricesGetResponseSchema } from "./bookingPricesGetResponseSchema.js"

export async function bookingPricesGet(
  client: OutscraperClient,
  input: BookingPricesGetInput,
): Promise<Result<BookingPricesGetResponse>> {
  const op = "bookingPricesGet"
  const parsed = v.safeParse(bookingPricesGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid bookingPricesGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/booking-prices",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: bookingPricesGetResponseSchema,
  })
}
