/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const businessesSimilarDomainGetInputSchema =
  /* businessesSimilarDomainGet input is grouped by HTTP argument location. */
  v.object({
    path: v.looseObject({ domain: v.string() }),
    query: v.optional(v.looseObject({}), {}),
    headers: v.optional(v.looseObject({}), {}),
  })

export type BusinessesSimilarDomainGetInput = v.InferInput<typeof businessesSimilarDomainGetInputSchema>
