/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type BusinessesSimilarDomainGetInput,
  businessesSimilarDomainGetInputSchema,
} from "./businessesSimilarDomainGetInputSchema.js"
import {
  type BusinessesSimilarDomainGetResponse,
  businessesSimilarDomainGetResponseSchema,
} from "./businessesSimilarDomainGetResponseSchema.js"

export async function businessesSimilarDomainGet(
  client: OutscraperClient,
  input: BusinessesSimilarDomainGetInput,
): Promise<Result<BusinessesSimilarDomainGetResponse>> {
  const op = "businessesSimilarDomainGet"
  const parsed = v.safeParse(businessesSimilarDomainGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid businessesSimilarDomainGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/businesses/similar/{domain}",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: businessesSimilarDomainGetResponseSchema,
  })
}
