/* Generated by openApiCatalogGenerate. Do not edit. */
export const businessesSimilarDomainGetDefinition = {
  description:
    "Find similar businesses based on a given domain. This endpoint allows you to discover businesses that are similar to a specified domain, which can be useful for competitive analysis, market research, or finding potential partners.\n\nThe API will analyze the provided domain and return a list of businesses that share similar characteristics, such as industry, size, location, or other relevant attributes.",
  folder: "get-businesses-similar-domain",
  method: "GET",
  operationId: "getBusinesses-Similar-Domain",
  parameters: [
    {
      description: "Domain to find similar businesses for.",
      example: "labaianyc.com",
      in: "path",
      location: "path",
      name: "domain",
      required: true,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/businesses/similar/{domain}",
  responses: [
    {
      content: [
        {
          example: {},
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: {},
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage: "Please close past due invoices or verify your card information is correct.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Past due invoices or a payment method not connected.",
      status: "402",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Invalid query URL parameters.",
      status: "422",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Find Similar Businesses",
  tags: ["Businesses & POI", "Business Data API"],
  "x-codeSamples": [],
} as const
