/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const businessesSimilarDomainGetResponseSchema = v.looseObject({})

export type BusinessesSimilarDomainGetResponse = v.InferOutput<typeof businessesSimilarDomainGetResponseSchema>
