/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type CompanyInsightsGetInput, companyInsightsGetInputSchema } from "./companyInsightsGetInputSchema.js"
import {
  type CompanyInsightsGetResponse,
  companyInsightsGetResponseSchema,
} from "./companyInsightsGetResponseSchema.js"

export async function companyInsightsGet(
  client: OutscraperClient,
  input: CompanyInsightsGetInput,
): Promise<Result<CompanyInsightsGetResponse>> {
  const op = "companyInsightsGet"
  const parsed = v.safeParse(companyInsightsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid companyInsightsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/company-insights",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: companyInsightsGetResponseSchema,
  })
}
