/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const companyInsightsGetInputSchema =
  /* companyInsightsGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      enrichment: v.optional(
        v.array(
          v.union([
            v.literal("leads_n_contacts"),
            v.literal("emails_validator_service"),
            v.literal("company_websites_finder"),
            v.literal("disposable_email_checker"),
            v.literal("company_insights_service"),
            v.literal("phones_enricher_service"),
            v.literal("trustpilot_service"),
            v.literal("whitepages_phones"),
            v.literal("ai_chain_info"),
          ]),
        ),
      ),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      query: v.array(v.string()),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type CompanyInsightsGetInput = v.InferInput<typeof companyInsightsGetInputSchema>
