/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const companyInsightsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          address: v.optional(v.nullable(v.string())),
          city: v.optional(v.nullable(v.string())),
          country: v.optional(v.nullable(v.string())),
          description: v.optional(v.nullable(v.string())),
          employees: v.optional(v.nullable(v.string())),
          facebook_company_page: v.optional(v.nullable(v.string())),
          founded_year: v.optional(v.nullable(v.string())),
          industry: v.optional(v.nullable(v.string())),
          is_public: v.optional(v.nullable(v.string())),
          linkedin_bio: v.optional(v.nullable(v.string())),
          linkedin_company_page: v.optional(v.nullable(v.string())),
          name: v.optional(v.nullable(v.string())),
          phone: v.optional(v.nullable(v.string())),
          query: v.optional(v.nullable(v.string())),
          revenue: v.optional(v.nullable(v.string())),
          state: v.optional(v.nullable(v.string())),
          timezone: v.optional(v.nullable(v.string())),
          total_money_raised: v.optional(v.nullable(v.string())),
          twitter_handle: v.optional(v.nullable(v.string())),
          zip: v.optional(v.nullable(v.string())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type CompanyInsightsGetResponse = v.InferOutput<typeof companyInsightsGetResponseSchema>
