/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type AmazonReviewsGetInput, amazonReviewsGetInputSchema } from "./amazonReviewsGetInputSchema.js"
import { type AmazonReviewsGetResponse, amazonReviewsGetResponseSchema } from "./amazonReviewsGetResponseSchema.js"

export async function amazonReviewsGet(
  client: OutscraperClient,
  input: AmazonReviewsGetInput,
): Promise<Result<AmazonReviewsGetResponse>> {
  const op = "amazonReviewsGet"
  const parsed = v.safeParse(amazonReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid amazonReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/amazon-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: amazonReviewsGetResponseSchema,
  })
}
