/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const amazonReviewsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            author_descriptor: v.optional(v.unknown()),
            author_profile_img: v.optional(v.unknown()),
            author_title: v.optional(v.unknown()),
            author_url: v.optional(v.unknown()),
            bage: v.optional(v.unknown()),
            body: v.optional(v.unknown()),
            comments: v.optional(v.unknown()),
            date: v.optional(v.unknown()),
            helpful: v.optional(v.unknown()),
            id: v.optional(v.unknown()),
            img_url: v.optional(v.unknown()),
            official_comment_banner: v.optional(v.unknown()),
            overall_rating: v.optional(v.unknown()),
            product_asin: v.optional(v.unknown()),
            product_url: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            rating: v.optional(v.unknown()),
            rating_text: v.optional(v.unknown()),
            title: v.optional(v.unknown()),
            total_reviews: v.optional(v.unknown()),
            url: v.optional(v.unknown()),
            variation: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type AmazonReviewsGetResponse = v.InferOutput<typeof amazonReviewsGetResponseSchema>
