/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const amazonReviewsGetInputSchema =
  /* amazonReviewsGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      domain: v.optional(
        v.union([
          v.literal("amazon.com"),
          v.literal("amazon.co.uk"),
          v.literal("amazon.ca"),
          v.literal("amazon.de"),
          v.literal("amazon.es"),
          v.literal("amazon.fr"),
          v.literal("amazon.it"),
          v.literal("amazon.in"),
          v.literal("amazon.nl"),
          v.literal("amazon.se"),
          v.literal("amazon.sa"),
          v.literal("amazon.com.mx"),
          v.literal("amazon.com.br"),
          v.literal("amazon.com.au"),
          v.literal("amazon.co.jp"),
          v.literal("amazon.pl"),
          v.literal("amazon.ae"),
        ]),
        "amazon.com",
      ),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      limit: v.optional(v.pipe(v.number(), v.integer()), 10),
      query: v.array(v.string()),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type AmazonReviewsGetInput = v.InferInput<typeof amazonReviewsGetInputSchema>
