/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TasksValidatePostInput, tasksValidatePostInputSchema } from "./tasksValidatePostInputSchema.js"
import { type TasksValidatePostResponse, tasksValidatePostResponseSchema } from "./tasksValidatePostResponseSchema.js"

export async function tasksValidatePost(
  client: OutscraperClient,
  input: TasksValidatePostInput = {},
): Promise<Result<TasksValidatePostResponse>> {
  const op = "tasksValidatePost"
  const parsed = v.safeParse(tasksValidatePostInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid tasksValidatePost input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/tasks-validate",
    method: "POST",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,
    body: value.body,
    contentType: "application/json",
    schema: tasksValidatePostResponseSchema,
  })
}
