/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksValidatePostResponseSchema = v.looseObject({})

export type TasksValidatePostResponse = v.InferOutput<typeof tasksValidatePostResponseSchema>
