/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksValidatePostInputSchema =
  /* tasksValidatePost input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.optional(v.looseObject({}), {}),
    headers: v.optional(v.looseObject({}), {}),
    body: v.optional(
      v.looseObject({
        enrichments: v.optional(v.array(v.string())),
        queries: v.optional(v.array(v.string())),
        service_name: v.optional(v.string()),
        tags: v.optional(v.array(v.string())),
      }),
    ),
  })

export type TasksValidatePostInput = v.InferInput<typeof tasksValidatePostInputSchema>
