/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GoogleMapsReviewsGetInput, googleMapsReviewsGetInputSchema } from "./googleMapsReviewsGetInputSchema.js"
import {
  type GoogleMapsReviewsGetResponse,
  googleMapsReviewsGetResponseSchema,
} from "./googleMapsReviewsGetResponseSchema.js"

export async function googleMapsReviewsGet(
  client: OutscraperClient,
  input: GoogleMapsReviewsGetInput,
): Promise<Result<GoogleMapsReviewsGetResponse>> {
  const op = "googleMapsReviewsGet"
  const parsed = v.safeParse(googleMapsReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleMapsReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-maps-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleMapsReviewsGetResponseSchema,
  })
}
