/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googleMapsReviewsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          full_address: v.optional(v.nullable(v.string())),
          google_id: v.optional(v.nullable(v.string())),
          location_link: v.optional(v.nullable(v.string())),
          name: v.optional(v.nullable(v.string())),
          place_id: v.optional(v.nullable(v.string())),
          rating: v.optional(v.nullable(v.number())),
          reviews: v.optional(v.nullable(v.number())),
          reviews_data: v.optional(v.array(v.unknown())),
          reviews_id: v.optional(v.nullable(v.string())),
          reviews_link: v.optional(v.nullable(v.string())),
          reviews_per_score: v.optional(
            v.looseObject({
              "1": v.optional(v.unknown()),
              "2": v.optional(v.unknown()),
              "3": v.optional(v.unknown()),
              "4": v.optional(v.unknown()),
              "5": v.optional(v.unknown()),
            }),
          ),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type GoogleMapsReviewsGetResponse = v.InferOutput<typeof googleMapsReviewsGetResponseSchema>
