/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type StatisticsStatusGetInput, statisticsStatusGetInputSchema } from "./statisticsStatusGetInputSchema.js"
import {
  type StatisticsStatusGetResponse,
  statisticsStatusGetResponseSchema,
} from "./statisticsStatusGetResponseSchema.js"

export async function statisticsStatusGet(
  client: OutscraperClient,
  input: StatisticsStatusGetInput = {},
): Promise<Result<StatisticsStatusGetResponse>> {
  const op = "statisticsStatusGet"
  const parsed = v.safeParse(statisticsStatusGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid statisticsStatusGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/statistics/status",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: statisticsStatusGetResponseSchema,
  })
}
