/* Generated by openApiCatalogGenerate. Do not edit. */
export const statisticsStatusGetDefinition = {
  description: "Fetch the current status of services and incidents.",
  folder: "get-statistics-status",
  method: "GET",
  operationId: "getStatistics-Status",
  parameters: [],
  path: "/statistics/status",
  responses: [
    {
      content: [
        {
          example: [
            {
              healthy: true,
              incident: null,
              monitors_down: [],
            },
          ],
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Services Status.",
      status: "200",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Get Services Status",
  tags: ["Platform & Dashboard"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X GET "https://api.outscraper.cloud/statistics/status"',
    },
  ],
} as const
