/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type YelpReviewsGetInput, yelpReviewsGetInputSchema } from "./yelpReviewsGetInputSchema.js"
import { type YelpReviewsGetResponse, yelpReviewsGetResponseSchema } from "./yelpReviewsGetResponseSchema.js"

export async function yelpReviewsGet(
  client: OutscraperClient,
  input: YelpReviewsGetInput,
): Promise<Result<YelpReviewsGetResponse>> {
  const op = "yelpReviewsGet"
  const parsed = v.safeParse(yelpReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid yelpReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/yelp-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: yelpReviewsGetResponseSchema,
  })
}
