/* Generated by openApiCatalogGenerate. Do not edit. */
export const yelpReviewsGetDefinition = {
  description:
    "Returns reviews from Yelp businesses.\n\nIn case no reviews were found by your search criteria, your search request will consume the usage of one review.",
  folder: "get-yelp-reviews",
  method: "GET",
  operationId: "getYelp-Reviews",
  parameters: [
    {
      description:
        "The parameter defines the way you want to submit your task to Outscraper. It can be set to `false` to open an HTTP connection and keep it open until you get your results, or `true` (default) to just submit your requests to Outscraper and retrieve them later (usually within 1-3 minutes) with the [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.\n\nA good practice is to send async requests and start checking the results after the estimated execution time. Check out [this](https://github.com/outscraper/outscraper-python/blob/master/examples/Run%20Async%20Requests.md) Python implementation as an example.\n\nAs most of the requests take some time to be executed the `async=true` option is preferred to avoid HTTP request timeouts.",
      example: false,
      in: "query",
      location: "query",
      name: "async",
      required: true,
      schema: {
        default: true,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter specifies the next page cursor (`next_page_cursor`) from the previous chunk of records (usually `10`). Used for pagination.",
      in: "query",
      location: "query",
      name: "cursor",
      required: false,
      schema: {
        type: "string",
      },
    },
    {
      description:
        "The parameter specifies the oldest timestamp value for items. \n\nUsing the `cutoff` parameter overwrites `sort` parameter`. Therefore, the latest records will be at the beginning (newest first).",
      in: "query",
      location: "query",
      name: "cutoff",
      required: false,
      schema: {
        type: "integer",
      },
    },
    {
      description:
        "The parameter defines which fields you want to include with each item returned in the response. By default, it returns all fields. Use `&fields=query,name` to return only the specific ones.",
      in: "query",
      location: "query",
      name: "fields",
      required: false,
      schema: {
        type: "string",
      },
    },
    {
      description:
        "The parameter defines the format of the output data. Using this parameter overwrites the `ui` parameter to `true`.",
      in: "query",
      location: "query",
      name: "format",
      required: false,
      schema: {
        collectionFormat: "csv",
        items: {
          default: "xlsx",
          enum: ["xlsx", "csv", "json", "parquet"],
          type: "string",
        },
        type: "array",
      },
    },
    {
      description: "The parameter specifies the limit of reviews to get from one query.",
      in: "query",
      location: "query",
      name: "limit",
      required: false,
      schema: {
        default: 100,
        type: "integer",
      },
    },
    {
      description:
        "You can use direct links, and IDs of any Yelp business (e.g., `https://www.yelp.com/biz/cancha-boutique-gastrobar-san-francisco`, `eggcellent-waffles-san-francisco`, `iXoLJWjbcXCO43RT-H0uQQ`).\n\nIt supports batching by sending arrays with up to `1000` queries (e.g., `query=text1&query=text2&query=text3`). It allows multiple queries to be sent in one request and to save on network latency time.",
      in: "query",
      location: "query",
      name: "query",
      required: true,
      schema: {
        collectionFormat: "csv",
        items: {
          type: "string",
        },
        type: "array",
      },
    },
    {
      description: "The parameter specifies one of the sorting types.",
      in: "query",
      location: "query",
      name: "sort",
      required: false,
      schema: {
        default: "relevance_desc",
        enum: ["relevance_desc", "date_desc", "date_asc", "rating_desc", "rating_asc", "elites_desc"],
        type: "string",
      },
    },
    {
      description:
        "The parameter defines whether a task will be executed as a UI task. This is commonly used when you want to create a regular platform task with API.\n\nUsing this parameter overwrites the `async` parameter to `true`.",
      in: "query",
      location: "query",
      name: "ui",
      required: false,
      schema: {
        default: false,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines the URL address (callback) to which Outscraper will create a POST request with a JSON body once a task/request is finished.\n\nUsing this parameter overwrites the webhook from integrations.",
      in: "query",
      location: "query",
      name: "webhook",
      required: false,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/yelp-reviews",
  responses: [
    {
      content: [
        {
          example: {
            data: [
              [
                {
                  business_name: "Eggcellent Waffles",
                  owner_replies: [],
                  query: "eggcellent-waffles-san-francisco",
                  review_id: "mMzh-4D_-jNG1zzWGo5SYQ",
                  review_photos: [],
                  review_rating: 5,
                  review_tags: [],
                  review_text:
                    "This place is awesome!! <br><br>You are basically allowed to craft your dream sandwich. The customization is crazy and the portions are so satisfying. I would definitely recommend the savory options. I got a everything waffle with roast beef, ham, and horseradish. What a dream. I will be back.",
                },
                {
                  business_name: "Eggcellent Waffles",
                  owner_replies: [],
                  query: "eggcellent-waffles-san-francisco",
                  review_id: "KKshwKeYC8nxzkOtprq1Mw",
                  review_photos: [],
                  review_rating: 4,
                  review_tags: [],
                  review_text:
                    "Honestly, I went to this place because of the silly name. It was a nice surprise. They have a wide variety of fillings to choose from sweet to savory, which is very nice. I&#39;ve ordered the All Day waffle, which has sausage, avocado, cheese. What an interesting combination, well served and very tasty indeed. The pumpkin spice chai was also very good. <br><br>Nothing out of this world but a good experience no doubt.",
                },
                {
                  business_name: "Eggcellent Waffles",
                  owner_replies: [],
                  query: "eggcellent-waffles-san-francisco",
                  review_id: "xpQACYnoK7WmRSiR-6ObEw",
                  review_photos: ["https://s3-media0.fl.yelpcdn.com/bphoto/LGs0xZDWYS7sWlNV21r66g/300s.jpg"],
                  review_rating: 3,
                  review_tags: ["1 photo", "1 check-in"],
                  review_text:
                    "First time here. I am really excited by the idea of a waffle as the bread to a sandwich. My desire was for a savory breakfast to go. Nothing really struck me as that so I ordered the All Day sandwich. Pork, avacdo, cheese: great. Ranch dressing, yuck! <br>Great portion and there location is just down from the top of Knob Hill. (Nice park to sit in while eating.)<br>I see coming back again for a sweet waffle and there are several waffle flavors I&#39;d like to try. However for the savory selections, I will be more selective. Maybe even building my own sandwich, which is an option.",
                },
              ],
            ],
            id: "your-request-id",
            status: "Success",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: {},
      status: "200",
    },
    {
      content: [
        {
          example: {
            id: "your-request-id",
            results_location: "https://api.outscraper.cloud/requests/your-request-id",
            status: "Pending",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description:
        "The response contains a request ID that can be used to fetch results by using [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.",
      status: "202",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage: "Please close past due invoices or verify your card information is correct.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Past due invoices or a payment method not connected.",
      status: "402",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Invalid query URL parameters.",
      status: "422",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Yelp Reviews",
  tags: ["Yelp", "Reviews & Comments"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source:
        'curl -X GET "https://api.outscraper.cloud/yelp-reviews?query=eggcellent-waffles-san-francisco&limit=3&async=false" -H  "X-API-KEY: YOUR-API-KEY"',
    },
    {
      lang: "cURL (async)",
      source:
        'curl -X GET "https://api.outscraper.cloud/yelp-reviews?query=eggcellent-waffles-san-francisco&limit=3" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
