/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const yelpReviewsGetInputSchema =
  /* yelpReviewsGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      cursor: v.optional(v.string()),
      cutoff: v.optional(v.pipe(v.number(), v.integer())),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      limit: v.optional(v.pipe(v.number(), v.integer()), 100),
      query: v.array(v.string()),
      sort: v.optional(
        v.union([
          v.literal("relevance_desc"),
          v.literal("date_desc"),
          v.literal("date_asc"),
          v.literal("rating_desc"),
          v.literal("rating_asc"),
          v.literal("elites_desc"),
        ]),
        "relevance_desc",
      ),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type YelpReviewsGetInput = v.InferInput<typeof yelpReviewsGetInputSchema>
