/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleMapsDirectoryGetInput,
  googleMapsDirectoryGetInputSchema,
} from "./googleMapsDirectoryGetInputSchema.js"
import {
  type GoogleMapsDirectoryGetResponse,
  googleMapsDirectoryGetResponseSchema,
} from "./googleMapsDirectoryGetResponseSchema.js"

export async function googleMapsDirectoryGet(
  client: OutscraperClient,
  input: GoogleMapsDirectoryGetInput,
): Promise<Result<GoogleMapsDirectoryGetResponse>> {
  const op = "googleMapsDirectoryGet"
  const parsed = v.safeParse(googleMapsDirectoryGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleMapsDirectoryGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-maps-directory",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleMapsDirectoryGetResponseSchema,
  })
}
