/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type BookingReviewsGetInput, bookingReviewsGetInputSchema } from "./bookingReviewsGetInputSchema.js"
import { type BookingReviewsGetResponse, bookingReviewsGetResponseSchema } from "./bookingReviewsGetResponseSchema.js"

export async function bookingReviewsGet(
  client: OutscraperClient,
  input: BookingReviewsGetInput,
): Promise<Result<BookingReviewsGetResponse>> {
  const op = "bookingReviewsGet"
  const parsed = v.safeParse(bookingReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid bookingReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/booking-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: bookingReviewsGetResponseSchema,
  })
}
