/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const profileBalanceGetInputSchema =
  /* profileBalanceGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.optional(v.looseObject({}), {}),
    headers: v.optional(v.looseObject({}), {}),
  })

export type ProfileBalanceGetInput = v.InferInput<typeof profileBalanceGetInputSchema>
