/* Generated by openApiCatalogGenerate. Do not edit. */
export const profileBalanceGetDefinition = {
  description: "Fetch user balance information.",
  folder: "get-profile-balance",
  method: "GET",
  operationId: "getProfile-Balance",
  parameters: [],
  path: "/profile/balance",
  responses: [
    {
      content: [
        {
          example: {
            account_status: "valid",
            balance: 1905.01,
            coupon: {},
            id: "cus_ID",
            upcoming_invoice: {
              amount_due: 0,
              applied_balance: 0,
              collection_method: "charge_automatically",
              currency: "usd",
              period_end: 1657376241,
              period_start: 1654784241,
              products_lines: [
                {
                  amount: 0,
                  lines: [
                    {
                      amount: 0,
                      currency: "usd",
                      quantity: 382,
                      unit_price: "$0.00",
                    },
                  ],
                  product_name: "Google Maps Data",
                  quantity: 382,
                  unit: "place",
                },
                {
                  amount: 0,
                  lines: [
                    {
                      amount: 0,
                      currency: "usd",
                      quantity: 316,
                      unit_price: "$0.00",
                    },
                  ],
                  product_name: "Domains",
                  quantity: 316,
                  unit: "domain",
                },
              ],
              subscription_id: "sub_ID",
              subtotal: 0,
              total: 0,
              total_discount: 0,
            },
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Profile Balance.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Get Balance",
  tags: ["Platform & Dashboard"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X GET "https://api.outscraper.cloud/profile/balance" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
