/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const profileBalanceGetResponseSchema = v.looseObject({
  account_status: v.optional(v.nullable(v.string())),
  balance: v.optional(v.nullable(v.number())),
  coupon: v.optional(v.looseObject({})),
  id: v.optional(v.nullable(v.string())),
  upcoming_invoice: v.optional(
    v.looseObject({
      amount_due: v.optional(v.nullable(v.number())),
      applied_balance: v.optional(v.nullable(v.number())),
      collection_method: v.optional(v.nullable(v.string())),
      currency: v.optional(v.nullable(v.string())),
      period_end: v.optional(v.nullable(v.number())),
      period_start: v.optional(v.nullable(v.number())),
      products_lines: v.optional(
        v.array(
          v.looseObject({
            amount: v.optional(v.unknown()),
            lines: v.optional(v.unknown()),
            product_name: v.optional(v.unknown()),
            quantity: v.optional(v.unknown()),
            unit: v.optional(v.unknown()),
          }),
        ),
      ),
      subscription_id: v.optional(v.nullable(v.string())),
      subtotal: v.optional(v.nullable(v.number())),
      total: v.optional(v.nullable(v.number())),
      total_discount: v.optional(v.nullable(v.number())),
    }),
  ),
})

export type ProfileBalanceGetResponse = v.InferOutput<typeof profileBalanceGetResponseSchema>
