/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type ProfileBalanceGetInput, profileBalanceGetInputSchema } from "./profileBalanceGetInputSchema.js"
import { type ProfileBalanceGetResponse, profileBalanceGetResponseSchema } from "./profileBalanceGetResponseSchema.js"

export async function profileBalanceGet(
  client: OutscraperClient,
  input: ProfileBalanceGetInput = {},
): Promise<Result<ProfileBalanceGetResponse>> {
  const op = "profileBalanceGet"
  const parsed = v.safeParse(profileBalanceGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid profileBalanceGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/profile/balance",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: profileBalanceGetResponseSchema,
  })
}
