/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const zillowSearchGetInputSchema =
  /* zillowSearchGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      limit: v.optional(v.pipe(v.number(), v.integer()), 100),
      mainFilter: v.optional(v.union([v.literal("for_sale"), v.literal("for_rent"), v.literal("sold")]), "for_sale"),
      query: v.array(v.string()),
      skip: v.optional(v.pipe(v.number(), v.integer()), 0),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type ZillowSearchGetInput = v.InferInput<typeof zillowSearchGetInputSchema>
