/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type ZillowSearchGetInput, zillowSearchGetInputSchema } from "./zillowSearchGetInputSchema.js"
import { type ZillowSearchGetResponse, zillowSearchGetResponseSchema } from "./zillowSearchGetResponseSchema.js"

export async function zillowSearchGet(
  client: OutscraperClient,
  input: ZillowSearchGetInput,
): Promise<Result<ZillowSearchGetResponse>> {
  const op = "zillowSearchGet"
  const parsed = v.safeParse(zillowSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid zillowSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/zillow-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: zillowSearchGetResponseSchema,
  })
}
