/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleMapsSuggestionsGetInput,
  googleMapsSuggestionsGetInputSchema,
} from "./googleMapsSuggestionsGetInputSchema.js"
import {
  type GoogleMapsSuggestionsGetResponse,
  googleMapsSuggestionsGetResponseSchema,
} from "./googleMapsSuggestionsGetResponseSchema.js"

export async function googleMapsSuggestionsGet(
  client: OutscraperClient,
  input: GoogleMapsSuggestionsGetInput,
): Promise<Result<GoogleMapsSuggestionsGetResponse>> {
  const op = "googleMapsSuggestionsGet"
  const parsed = v.safeParse(googleMapsSuggestionsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleMapsSuggestionsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-maps-suggestions",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleMapsSuggestionsGetResponseSchema,
  })
}
