/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googleMapsSuggestionsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({ query: v.optional(v.nullable(v.string())), suggestions: v.optional(v.array(v.unknown())) }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type GoogleMapsSuggestionsGetResponse = v.InferOutput<typeof googleMapsSuggestionsGetResponseSchema>
