/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GoogleMapsSearchGetInput, googleMapsSearchGetInputSchema } from "./googleMapsSearchGetInputSchema.js"
import {
  type GoogleMapsSearchGetResponse,
  googleMapsSearchGetResponseSchema,
} from "./googleMapsSearchGetResponseSchema.js"

export async function googleMapsSearchGet(
  client: OutscraperClient,
  input: GoogleMapsSearchGetInput,
): Promise<Result<GoogleMapsSearchGetResponse>> {
  const op = "googleMapsSearchGet"
  const parsed = v.safeParse(googleMapsSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleMapsSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-maps-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleMapsSearchGetResponseSchema,
  })
}
