/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type TripadvisorReviewsGetInput,
  tripadvisorReviewsGetInputSchema,
} from "./tripadvisorReviewsGetInputSchema.js"
import {
  type TripadvisorReviewsGetResponse,
  tripadvisorReviewsGetResponseSchema,
} from "./tripadvisorReviewsGetResponseSchema.js"

export async function tripadvisorReviewsGet(
  client: OutscraperClient,
  input: TripadvisorReviewsGetInput,
): Promise<Result<TripadvisorReviewsGetResponse>> {
  const op = "tripadvisorReviewsGet"
  const parsed = v.safeParse(tripadvisorReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid tripadvisorReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/tripadvisor-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: tripadvisorReviewsGetResponseSchema,
  })
}
