/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tripadvisorReviewsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            author_title: v.optional(v.unknown()),
            owner_response: v.optional(v.unknown()),
            owner_title: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            review_date: v.optional(v.unknown()),
            review_link: v.optional(v.unknown()),
            review_media: v.optional(v.unknown()),
            review_rating: v.optional(v.unknown()),
            review_text: v.optional(v.unknown()),
            review_title: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type TripadvisorReviewsGetResponse = v.InferOutput<typeof tripadvisorReviewsGetResponseSchema>
