/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type YoutubeSearchGetInput, youtubeSearchGetInputSchema } from "./youtubeSearchGetInputSchema.js"
import { type YoutubeSearchGetResponse, youtubeSearchGetResponseSchema } from "./youtubeSearchGetResponseSchema.js"

export async function youtubeSearchGet(
  client: OutscraperClient,
  input: YoutubeSearchGetInput,
): Promise<Result<YoutubeSearchGetResponse>> {
  const op = "youtubeSearchGet"
  const parsed = v.safeParse(youtubeSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid youtubeSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/youtube-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: youtubeSearchGetResponseSchema,
  })
}
