/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const youtubeSearchGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          estimated_results: v.optional(v.nullable(v.string())),
          organic_results: v.optional(v.array(v.unknown())),
          query: v.optional(v.nullable(v.string())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type YoutubeSearchGetResponse = v.InferOutput<typeof youtubeSearchGetResponseSchema>
