/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GoogleMapsPhotosGetInput, googleMapsPhotosGetInputSchema } from "./googleMapsPhotosGetInputSchema.js"
import {
  type GoogleMapsPhotosGetResponse,
  googleMapsPhotosGetResponseSchema,
} from "./googleMapsPhotosGetResponseSchema.js"

export async function googleMapsPhotosGet(
  client: OutscraperClient,
  input: GoogleMapsPhotosGetInput,
): Promise<Result<GoogleMapsPhotosGetResponse>> {
  const op = "googleMapsPhotosGet"
  const parsed = v.safeParse(googleMapsPhotosGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleMapsPhotosGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-maps-photos",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleMapsPhotosGetResponseSchema,
  })
}
