/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googleMapsPhotosGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            full_address: v.optional(v.unknown()),
            google_id: v.optional(v.unknown()),
            location_link: v.optional(v.unknown()),
            name: v.optional(v.unknown()),
            photos_data: v.optional(v.unknown()),
            place_id: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type GoogleMapsPhotosGetResponse = v.InferOutput<typeof googleMapsPhotosGetResponseSchema>
