/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tripadvisorSearchGetInputSchema =
  /* tripadvisorSearchGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      SearchType: v.optional(
        v.union([v.literal("a"), v.literal("h"), v.literal("e"), v.literal("A"), v.literal("v")]),
        "a",
      ),
      async: v.boolean(),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      limit: v.optional(v.pipe(v.number(), v.integer()), 100),
      query: v.array(v.string()),
      skip: v.optional(v.pipe(v.number(), v.integer()), 0),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type TripadvisorSearchGetInput = v.InferInput<typeof tripadvisorSearchGetInputSchema>
