/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const twitterProfilesGetResponseSchema = v.looseObject({
  id: v.optional(v.nullable(v.string())),
  results_location: v.optional(v.nullable(v.string())),
  status: v.optional(v.nullable(v.string())),
})

export type TwitterProfilesGetResponse = v.InferOutput<typeof twitterProfilesGetResponseSchema>
