/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TwitterProfilesGetInput, twitterProfilesGetInputSchema } from "./twitterProfilesGetInputSchema.js"
import {
  type TwitterProfilesGetResponse,
  twitterProfilesGetResponseSchema,
} from "./twitterProfilesGetResponseSchema.js"

export async function twitterProfilesGet(
  client: OutscraperClient,
  input: TwitterProfilesGetInput,
): Promise<Result<TwitterProfilesGetResponse>> {
  const op = "twitterProfilesGet"
  const parsed = v.safeParse(twitterProfilesGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid twitterProfilesGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/twitter-profiles",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: twitterProfilesGetResponseSchema,
  })
}
