/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const redditCommentsGetInputSchema =
  /* redditCommentsGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      fields: v.optional(v.string()),
      query: v.array(v.string()),
      sort: v.optional(
        v.union([
          v.literal("best"),
          v.literal("top"),
          v.literal("new"),
          v.literal("controversial"),
          v.literal("old"),
          v.literal("qa"),
        ]),
        "best",
      ),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type RedditCommentsGetInput = v.InferInput<typeof redditCommentsGetInputSchema>
