/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type RedditCommentsGetInput, redditCommentsGetInputSchema } from "./redditCommentsGetInputSchema.js"
import { type RedditCommentsGetResponse, redditCommentsGetResponseSchema } from "./redditCommentsGetResponseSchema.js"

export async function redditCommentsGet(
  client: OutscraperClient,
  input: RedditCommentsGetInput,
): Promise<Result<RedditCommentsGetResponse>> {
  const op = "redditCommentsGet"
  const parsed = v.safeParse(redditCommentsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid redditCommentsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/reddit-comments",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: redditCommentsGetResponseSchema,
  })
}
