/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const requestsRequestIdDeleteInputSchema =
  /* requestsRequestIdDelete input is grouped by HTTP argument location. */
  v.object({
    path: v.looseObject({ requestId: v.string() }),
    query: v.optional(v.looseObject({}), {}),
    headers: v.optional(v.looseObject({}), {}),
  })

export type RequestsRequestIdDeleteInput = v.InferInput<typeof requestsRequestIdDeleteInputSchema>
