/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type RequestsRequestIdDeleteInput,
  requestsRequestIdDeleteInputSchema,
} from "./requestsRequestIdDeleteInputSchema.js"
import {
  type RequestsRequestIdDeleteResponse,
  requestsRequestIdDeleteResponseSchema,
} from "./requestsRequestIdDeleteResponseSchema.js"

export async function requestsRequestIdDelete(
  client: OutscraperClient,
  input: RequestsRequestIdDeleteInput,
): Promise<Result<RequestsRequestIdDeleteResponse>> {
  const op = "requestsRequestIdDelete"
  const parsed = v.safeParse(requestsRequestIdDeleteInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid requestsRequestIdDelete input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/requests/{requestId}",
    method: "DELETE",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: requestsRequestIdDeleteResponseSchema,
  })
}
