/* Generated by openApiCatalogGenerate. Do not edit. */
export const requestsRequestIdDeleteDefinition = {
  description: "Allows you to terminate created requests.",
  folder: "delete-requests-request-id",
  method: "DELETE",
  operationId: "deleteRequests-RequestId",
  parameters: [
    {
      description: 'Request ID provided by API endpoints at `["id"]`. Example: `32692d16-725c-4e66-b013-95e80e873b7e`',
      in: "path",
      location: "path",
      name: "requestId",
      required: true,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/requests/{requestId}",
  responses: [
    {
      content: [
        {
          example: "Request 17dd74fc-242b-4fdc-b518-009502768cf3 terminated",
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Request terminated.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Terminate Request",
  tags: ["Requests"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X DELETE "https://api.outscraper.cloud/requests/your-request-id"',
    },
  ],
} as const
