/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const requestsRequestIdDeleteResponseSchema = v.string()

export type RequestsRequestIdDeleteResponse = v.InferOutput<typeof requestsRequestIdDeleteResponseSchema>
