/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const etsyProductsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            availability: v.optional(v.unknown()),
            brand: v.optional(v.unknown()),
            category: v.optional(v.unknown()),
            currency: v.optional(v.unknown()),
            description: v.optional(v.unknown()),
            discount: v.optional(v.unknown()),
            image_alt: v.optional(v.unknown()),
            image_url: v.optional(v.unknown()),
            images: v.optional(v.unknown()),
            max_price: v.optional(v.unknown()),
            min_price: v.optional(v.unknown()),
            original_price: v.optional(v.unknown()),
            price: v.optional(v.unknown()),
            rating: v.optional(v.unknown()),
            reviews: v.optional(v.unknown()),
            seller: v.optional(v.unknown()),
            shipping: v.optional(v.unknown()),
            sku_code: v.optional(v.unknown()),
            title: v.optional(v.unknown()),
            url: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type EtsyProductsGetResponse = v.InferOutput<typeof etsyProductsGetResponseSchema>
