/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const shopeeReviewsGetInputSchema =
  /* shopeeReviewsGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      limit: v.optional(v.pipe(v.number(), v.integer()), 100),
      query: v.array(v.string()),
      sort: v.optional(v.union([v.literal(0), v.literal(1), v.literal(3)]), 0),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type ShopeeReviewsGetInput = v.InferInput<typeof shopeeReviewsGetInputSchema>
