/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type ShopeeReviewsGetInput, shopeeReviewsGetInputSchema } from "./shopeeReviewsGetInputSchema.js"
import { type ShopeeReviewsGetResponse, shopeeReviewsGetResponseSchema } from "./shopeeReviewsGetResponseSchema.js"

export async function shopeeReviewsGet(
  client: OutscraperClient,
  input: ShopeeReviewsGetInput,
): Promise<Result<ShopeeReviewsGetResponse>> {
  const op = "shopeeReviewsGet"
  const parsed = v.safeParse(shopeeReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid shopeeReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/shopee-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: shopeeReviewsGetResponseSchema,
  })
}
