/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type IndeedReviewsGetInput, indeedReviewsGetInputSchema } from "./indeedReviewsGetInputSchema.js"
import { type IndeedReviewsGetResponse, indeedReviewsGetResponseSchema } from "./indeedReviewsGetResponseSchema.js"

export async function indeedReviewsGet(
  client: OutscraperClient,
  input: IndeedReviewsGetInput,
): Promise<Result<IndeedReviewsGetResponse>> {
  const op = "indeedReviewsGet"
  const parsed = v.safeParse(indeedReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid indeedReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/indeed-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: indeedReviewsGetResponseSchema,
  })
}
