/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const emailsAndContactsGetInputSchema =
  /* emailsAndContactsGet input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.looseObject({
      async: v.boolean(),
      fields: v.optional(v.string()),
      format: v.optional(
        v.array(v.union([v.literal("xlsx"), v.literal("csv"), v.literal("json"), v.literal("parquet")])),
      ),
      preferredContacts: v.optional(
        v.array(
          v.union([
            v.literal("decision makers"),
            v.literal("influencers"),
            v.literal("procurement/purchasing"),
            v.literal("technical"),
            v.literal("finance"),
            v.literal("operations"),
            v.literal("marketing"),
            v.literal("sales"),
            v.literal("maintenance"),
            v.literal("human resources"),
            v.literal("legal and compliance"),
            v.literal("supply chain/logistics"),
            v.literal("education/training"),
          ]),
        ),
      ),
      query: v.array(v.string()),
      ui: v.optional(v.boolean(), false),
      webhook: v.optional(v.string()),
    }),
    headers: v.optional(v.looseObject({}), {}),
  })

export type EmailsAndContactsGetInput = v.InferInput<typeof emailsAndContactsGetInputSchema>
