/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const emailsAndContactsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          domain: v.optional(v.nullable(v.string())),
          emails: v.optional(v.array(v.unknown())),
          query: v.optional(v.nullable(v.string())),
          site_data: v.optional(v.looseObject({ generator: v.optional(v.unknown()), title: v.optional(v.unknown()) })),
          socials: v.optional(
            v.looseObject({
              facebook: v.optional(v.unknown()),
              github: v.optional(v.unknown()),
              linkedin: v.optional(v.unknown()),
              twitter: v.optional(v.unknown()),
              youtube: v.optional(v.unknown()),
            }),
          ),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type EmailsAndContactsGetResponse = v.InferOutput<typeof emailsAndContactsGetResponseSchema>
