/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type EmailsAndContactsGetInput, emailsAndContactsGetInputSchema } from "./emailsAndContactsGetInputSchema.js"
import {
  type EmailsAndContactsGetResponse,
  emailsAndContactsGetResponseSchema,
} from "./emailsAndContactsGetResponseSchema.js"

export async function emailsAndContactsGet(
  client: OutscraperClient,
  input: EmailsAndContactsGetInput,
): Promise<Result<EmailsAndContactsGetResponse>> {
  const op = "emailsAndContactsGet"
  const parsed = v.safeParse(emailsAndContactsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid emailsAndContactsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/emails-and-contacts",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: emailsAndContactsGetResponseSchema,
  })
}
