/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type AirbnbSearchGetInput, airbnbSearchGetInputSchema } from "./airbnbSearchGetInputSchema.js"
import { type AirbnbSearchGetResponse, airbnbSearchGetResponseSchema } from "./airbnbSearchGetResponseSchema.js"

export async function airbnbSearchGet(
  client: OutscraperClient,
  input: AirbnbSearchGetInput,
): Promise<Result<AirbnbSearchGetResponse>> {
  const op = "airbnbSearchGet"
  const parsed = v.safeParse(airbnbSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid airbnbSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/airbnb-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: airbnbSearchGetResponseSchema,
  })
}
