/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type LinkedinCompaniesGetInput, linkedinCompaniesGetInputSchema } from "./linkedinCompaniesGetInputSchema.js"
import {
  type LinkedinCompaniesGetResponse,
  linkedinCompaniesGetResponseSchema,
} from "./linkedinCompaniesGetResponseSchema.js"

export async function linkedinCompaniesGet(
  client: OutscraperClient,
  input: LinkedinCompaniesGetInput,
): Promise<Result<LinkedinCompaniesGetResponse>> {
  const op = "linkedinCompaniesGet"
  const parsed = v.safeParse(linkedinCompaniesGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid linkedinCompaniesGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/linkedin-companies",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: linkedinCompaniesGetResponseSchema,
  })
}
