/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleSearchVideosGetInput,
  googleSearchVideosGetInputSchema,
} from "./googleSearchVideosGetInputSchema.js"
import {
  type GoogleSearchVideosGetResponse,
  googleSearchVideosGetResponseSchema,
} from "./googleSearchVideosGetResponseSchema.js"

export async function googleSearchVideosGet(
  client: OutscraperClient,
  input: GoogleSearchVideosGetInput,
): Promise<Result<GoogleSearchVideosGetResponse>> {
  const op = "googleSearchVideosGet"
  const parsed = v.safeParse(googleSearchVideosGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleSearchVideosGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-search-videos",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleSearchVideosGetResponseSchema,
  })
}
