/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type BookingSearchGetInput, bookingSearchGetInputSchema } from "./bookingSearchGetInputSchema.js"
import { type BookingSearchGetResponse, bookingSearchGetResponseSchema } from "./bookingSearchGetResponseSchema.js"

export async function bookingSearchGet(
  client: OutscraperClient,
  input: BookingSearchGetInput,
): Promise<Result<BookingSearchGetResponse>> {
  const op = "bookingSearchGet"
  const parsed = v.safeParse(bookingSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid bookingSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/booking-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: bookingSearchGetResponseSchema,
  })
}
