/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type YoutubeTranscriptsGetInput,
  youtubeTranscriptsGetInputSchema,
} from "./youtubeTranscriptsGetInputSchema.js"
import {
  type YoutubeTranscriptsGetResponse,
  youtubeTranscriptsGetResponseSchema,
} from "./youtubeTranscriptsGetResponseSchema.js"

export async function youtubeTranscriptsGet(
  client: OutscraperClient,
  input: YoutubeTranscriptsGetInput,
): Promise<Result<YoutubeTranscriptsGetResponse>> {
  const op = "youtubeTranscriptsGet"
  const parsed = v.safeParse(youtubeTranscriptsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid youtubeTranscriptsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/youtube-transcripts",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: youtubeTranscriptsGetResponseSchema,
  })
}
