/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type BingMapsGetInput, bingMapsGetInputSchema } from "./bingMapsGetInputSchema.js"
import { type BingMapsGetResponse, bingMapsGetResponseSchema } from "./bingMapsGetResponseSchema.js"

export async function bingMapsGet(
  client: OutscraperClient,
  input: BingMapsGetInput,
): Promise<Result<BingMapsGetResponse>> {
  const op = "bingMapsGet"
  const parsed = v.safeParse(bingMapsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid bingMapsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/bing-maps",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: bingMapsGetResponseSchema,
  })
}
