/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type GeocodingGetInput, geocodingGetInputSchema } from "./geocodingGetInputSchema.js"
import { type GeocodingGetResponse, geocodingGetResponseSchema } from "./geocodingGetResponseSchema.js"

export async function geocodingGet(
  client: OutscraperClient,
  input: GeocodingGetInput,
): Promise<Result<GeocodingGetResponse>> {
  const op = "geocodingGet"
  const parsed = v.safeParse(geocodingGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid geocodingGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/geocoding",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: geocodingGetResponseSchema,
  })
}
