/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GooglePlacesByDomainGetInput,
  googlePlacesByDomainGetInputSchema,
} from "./googlePlacesByDomainGetInputSchema.js"
import {
  type GooglePlacesByDomainGetResponse,
  googlePlacesByDomainGetResponseSchema,
} from "./googlePlacesByDomainGetResponseSchema.js"

export async function googlePlacesByDomainGet(
  client: OutscraperClient,
  input: GooglePlacesByDomainGetInput,
): Promise<Result<GooglePlacesByDomainGetResponse>> {
  const op = "googlePlacesByDomainGet"
  const parsed = v.safeParse(googlePlacesByDomainGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googlePlacesByDomainGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-places-by-domain",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googlePlacesByDomainGetResponseSchema,
  })
}
