/* Generated by openApiCatalogGenerate. Do not edit. */
import { buildRouteMap } from "@stricli/core"
import { outscraperCliCommandBuild } from "./cli/outscraperCliCommandBuild.js"
import { requestsRequestIdDelete } from "./delete-requests-request-id/requestsRequestIdDelete.js"
import { requestsRequestIdDeleteDefinition } from "./delete-requests-request-id/requestsRequestIdDeleteDefinition.js"
import { tasksTaskIdDelete } from "./delete-tasks-task-id/tasksTaskIdDelete.js"
import { tasksTaskIdDeleteDefinition } from "./delete-tasks-task-id/tasksTaskIdDeleteDefinition.js"
import { aiScraperGet } from "./get-ai-scraper/aiScraperGet.js"
import { aiScraperGetDefinition } from "./get-ai-scraper/aiScraperGetDefinition.js"
import { airbnbReviewsGet } from "./get-airbnb-reviews/airbnbReviewsGet.js"
import { airbnbReviewsGetDefinition } from "./get-airbnb-reviews/airbnbReviewsGetDefinition.js"
import { airbnbSearchGet } from "./get-airbnb-search/airbnbSearchGet.js"
import { airbnbSearchGetDefinition } from "./get-airbnb-search/airbnbSearchGetDefinition.js"
import { amazonProductsGet } from "./get-amazon-products/amazonProductsGet.js"
import { amazonProductsGetDefinition } from "./get-amazon-products/amazonProductsGetDefinition.js"
import { amazonReviewsGet } from "./get-amazon-reviews/amazonReviewsGet.js"
import { amazonReviewsGetDefinition } from "./get-amazon-reviews/amazonReviewsGetDefinition.js"
import { appstoreReviewsGet } from "./get-appstore-reviews/appstoreReviewsGet.js"
import { appstoreReviewsGetDefinition } from "./get-appstore-reviews/appstoreReviewsGetDefinition.js"
import { bingMapsGet } from "./get-bing-maps/bingMapsGet.js"
import { bingMapsGetDefinition } from "./get-bing-maps/bingMapsGetDefinition.js"
import { bookingPricesGet } from "./get-booking-prices/bookingPricesGet.js"
import { bookingPricesGetDefinition } from "./get-booking-prices/bookingPricesGetDefinition.js"
import { bookingReviewsGet } from "./get-booking-reviews/bookingReviewsGet.js"
import { bookingReviewsGetDefinition } from "./get-booking-reviews/bookingReviewsGetDefinition.js"
import { bookingSearchGet } from "./get-booking-search/bookingSearchGet.js"
import { bookingSearchGetDefinition } from "./get-booking-search/bookingSearchGetDefinition.js"
import { businessesBusinessIdGet } from "./get-businesses-business-id/businessesBusinessIdGet.js"
import { businessesBusinessIdGetDefinition } from "./get-businesses-business-id/businessesBusinessIdGetDefinition.js"
import { businessesSimilarDomainGet } from "./get-businesses-similar-domain/businessesSimilarDomainGet.js"
import { businessesSimilarDomainGetDefinition } from "./get-businesses-similar-domain/businessesSimilarDomainGetDefinition.js"
import { capterraReviewsGet } from "./get-capterra-reviews/capterraReviewsGet.js"
import { capterraReviewsGetDefinition } from "./get-capterra-reviews/capterraReviewsGetDefinition.js"
import { companyInsightsGet } from "./get-company-insights/companyInsightsGet.js"
import { companyInsightsGetDefinition } from "./get-company-insights/companyInsightsGetDefinition.js"
import { companyWebsiteFinderGet } from "./get-company-website-finder/companyWebsiteFinderGet.js"
import { companyWebsiteFinderGetDefinition } from "./get-company-website-finder/companyWebsiteFinderGetDefinition.js"
import { deliverooGet } from "./get-deliveroo/deliverooGet.js"
import { deliverooGetDefinition } from "./get-deliveroo/deliverooGetDefinition.js"
import { deliverooReviewsGet } from "./get-deliveroo-reviews/deliverooReviewsGet.js"
import { deliverooReviewsGetDefinition } from "./get-deliveroo-reviews/deliverooReviewsGetDefinition.js"
import { disposableEmailCheckerGet } from "./get-disposable-email-checker/disposableEmailCheckerGet.js"
import { disposableEmailCheckerGetDefinition } from "./get-disposable-email-checker/disposableEmailCheckerGetDefinition.js"
import { emailValidatorGet } from "./get-email-validator/emailValidatorGet.js"
import { emailValidatorGetDefinition } from "./get-email-validator/emailValidatorGetDefinition.js"
import { emailsAndContactsGet } from "./get-emails-and-contacts/emailsAndContactsGet.js"
import { emailsAndContactsGetDefinition } from "./get-emails-and-contacts/emailsAndContactsGetDefinition.js"
import { emailsFinderGet } from "./get-emails-finder/emailsFinderGet.js"
import { emailsFinderGetDefinition } from "./get-emails-finder/emailsFinderGetDefinition.js"
import { etsyProductsGet } from "./get-etsy-products/etsyProductsGet.js"
import { etsyProductsGetDefinition } from "./get-etsy-products/etsyProductsGetDefinition.js"
import { etsyReviewsGet } from "./get-etsy-reviews/etsyReviewsGet.js"
import { etsyReviewsGetDefinition } from "./get-etsy-reviews/etsyReviewsGetDefinition.js"
import { expediaReviewsGet } from "./get-expedia-reviews/expediaReviewsGet.js"
import { expediaReviewsGetDefinition } from "./get-expedia-reviews/expediaReviewsGetDefinition.js"
import { expediaSearchGet } from "./get-expedia-search/expediaSearchGet.js"
import { expediaSearchGetDefinition } from "./get-expedia-search/expediaSearchGetDefinition.js"
import { g2ReviewsGet } from "./get-g2-reviews/g2ReviewsGet.js"
import { g2ReviewsGetDefinition } from "./get-g2-reviews/g2ReviewsGetDefinition.js"
import { geocodingGet } from "./get-geocoding/geocodingGet.js"
import { geocodingGetDefinition } from "./get-geocoding/geocodingGetDefinition.js"
import { getappReviewsGet } from "./get-getapp-reviews/getappReviewsGet.js"
import { getappReviewsGetDefinition } from "./get-getapp-reviews/getappReviewsGetDefinition.js"
import { glassdoorReviewsGet } from "./get-glassdoor-reviews/glassdoorReviewsGet.js"
import { glassdoorReviewsGetDefinition } from "./get-glassdoor-reviews/glassdoorReviewsGetDefinition.js"
import { googleMapsAutocompleteGet } from "./get-google-maps-autocomplete/googleMapsAutocompleteGet.js"
import { googleMapsAutocompleteGetDefinition } from "./get-google-maps-autocomplete/googleMapsAutocompleteGetDefinition.js"
import { googleMapsDirectionsGet } from "./get-google-maps-directions/googleMapsDirectionsGet.js"
import { googleMapsDirectionsGetDefinition } from "./get-google-maps-directions/googleMapsDirectionsGetDefinition.js"
import { googleMapsDirectoryGet } from "./get-google-maps-directory/googleMapsDirectoryGet.js"
import { googleMapsDirectoryGetDefinition } from "./get-google-maps-directory/googleMapsDirectoryGetDefinition.js"
import { googleMapsPhotosGet } from "./get-google-maps-photos/googleMapsPhotosGet.js"
import { googleMapsPhotosGetDefinition } from "./get-google-maps-photos/googleMapsPhotosGetDefinition.js"
import { googleMapsReviewsGet } from "./get-google-maps-reviews/googleMapsReviewsGet.js"
import { googleMapsReviewsGetDefinition } from "./get-google-maps-reviews/googleMapsReviewsGetDefinition.js"
import { googleMapsSearchGet } from "./get-google-maps-search/googleMapsSearchGet.js"
import { googleMapsSearchGetDefinition } from "./get-google-maps-search/googleMapsSearchGetDefinition.js"
import { googleMapsSuggestionsGet } from "./get-google-maps-suggestions/googleMapsSuggestionsGet.js"
import { googleMapsSuggestionsGetDefinition } from "./get-google-maps-suggestions/googleMapsSuggestionsGetDefinition.js"
import { googlePlacesByDomainGet } from "./get-google-places-by-domain/googlePlacesByDomainGet.js"
import { googlePlacesByDomainGetDefinition } from "./get-google-places-by-domain/googlePlacesByDomainGetDefinition.js"
import { googlePlayReviewsGet } from "./get-google-play-reviews/googlePlayReviewsGet.js"
import { googlePlayReviewsGetDefinition } from "./get-google-play-reviews/googlePlayReviewsGetDefinition.js"
import { googleSearchGet } from "./get-google-search/googleSearchGet.js"
import { googleSearchGetDefinition } from "./get-google-search/googleSearchGetDefinition.js"
import { googleSearchAutocompleteGet } from "./get-google-search-autocomplete/googleSearchAutocompleteGet.js"
import { googleSearchAutocompleteGetDefinition } from "./get-google-search-autocomplete/googleSearchAutocompleteGetDefinition.js"
import { googleSearchCareersGet } from "./get-google-search-careers/googleSearchCareersGet.js"
import { googleSearchCareersGetDefinition } from "./get-google-search-careers/googleSearchCareersGetDefinition.js"
import { googleSearchEventsGet } from "./get-google-search-events/googleSearchEventsGet.js"
import { googleSearchEventsGetDefinition } from "./get-google-search-events/googleSearchEventsGetDefinition.js"
import { googleSearchFlightsGet } from "./get-google-search-flights/googleSearchFlightsGet.js"
import { googleSearchFlightsGetDefinition } from "./get-google-search-flights/googleSearchFlightsGetDefinition.js"
import { googleSearchImagesGet } from "./get-google-search-images/googleSearchImagesGet.js"
import { googleSearchImagesGetDefinition } from "./get-google-search-images/googleSearchImagesGetDefinition.js"
import { googleSearchJobsGet } from "./get-google-search-jobs/googleSearchJobsGet.js"
import { googleSearchJobsGetDefinition } from "./get-google-search-jobs/googleSearchJobsGetDefinition.js"
import { googleSearchNewsGet } from "./get-google-search-news/googleSearchNewsGet.js"
import { googleSearchNewsGetDefinition } from "./get-google-search-news/googleSearchNewsGetDefinition.js"
import { googleSearchShoppingGet } from "./get-google-search-shopping/googleSearchShoppingGet.js"
import { googleSearchShoppingGetDefinition } from "./get-google-search-shopping/googleSearchShoppingGetDefinition.js"
import { googleSearchVideosGet } from "./get-google-search-videos/googleSearchVideosGet.js"
import { googleSearchVideosGetDefinition } from "./get-google-search-videos/googleSearchVideosGetDefinition.js"
import { googleShoppingReviewsGet } from "./get-google-shopping-reviews/googleShoppingReviewsGet.js"
import { googleShoppingReviewsGetDefinition } from "./get-google-shopping-reviews/googleShoppingReviewsGetDefinition.js"
import { googleTrendsGet } from "./get-google-trends/googleTrendsGet.js"
import { googleTrendsGetDefinition } from "./get-google-trends/googleTrendsGetDefinition.js"
import { hotelsSearchGet } from "./get-hotels-search/hotelsSearchGet.js"
import { hotelsSearchGetDefinition } from "./get-hotels-search/hotelsSearchGetDefinition.js"
import { indeedReviewsGet } from "./get-indeed-reviews/indeedReviewsGet.js"
import { indeedReviewsGetDefinition } from "./get-indeed-reviews/indeedReviewsGetDefinition.js"
import { indeedSearchGet } from "./get-indeed-search/indeedSearchGet.js"
import { indeedSearchGetDefinition } from "./get-indeed-search/indeedSearchGetDefinition.js"
import { invoicesGet } from "./get-invoices/invoicesGet.js"
import { invoicesGetDefinition } from "./get-invoices/invoicesGetDefinition.js"
import { leadsAndContactsGet } from "./get-leads-and-contacts/leadsAndContactsGet.js"
import { leadsAndContactsGetDefinition } from "./get-leads-and-contacts/leadsAndContactsGetDefinition.js"
import { linkedinCompaniesGet } from "./get-linkedin-companies/linkedinCompaniesGet.js"
import { linkedinCompaniesGetDefinition } from "./get-linkedin-companies/linkedinCompaniesGetDefinition.js"
import { linkedinPostsGet } from "./get-linkedin-posts/linkedinPostsGet.js"
import { linkedinPostsGetDefinition } from "./get-linkedin-posts/linkedinPostsGetDefinition.js"
import { linkedinProfilesGet } from "./get-linkedin-profiles/linkedinProfilesGet.js"
import { linkedinProfilesGetDefinition } from "./get-linkedin-profiles/linkedinProfilesGetDefinition.js"
import { locationsGet } from "./get-locations/locationsGet.js"
import { locationsGetDefinition } from "./get-locations/locationsGetDefinition.js"
import { mapsSearchGet } from "./get-maps-search/mapsSearchGet.js"
import { mapsSearchGetDefinition } from "./get-maps-search/mapsSearchGetDefinition.js"
import { phonesEnricherGet } from "./get-phones-enricher/phonesEnricherGet.js"
import { phonesEnricherGetDefinition } from "./get-phones-enricher/phonesEnricherGetDefinition.js"
import { phonesOwnersGet } from "./get-phones-owners/phonesOwnersGet.js"
import { phonesOwnersGetDefinition } from "./get-phones-owners/phonesOwnersGetDefinition.js"
import { producthuntReviewsGet } from "./get-producthunt-reviews/producthuntReviewsGet.js"
import { producthuntReviewsGetDefinition } from "./get-producthunt-reviews/producthuntReviewsGetDefinition.js"
import { profileBalanceGet } from "./get-profile-balance/profileBalanceGet.js"
import { profileBalanceGetDefinition } from "./get-profile-balance/profileBalanceGetDefinition.js"
import { redditCommentsGet } from "./get-reddit-comments/redditCommentsGet.js"
import { redditCommentsGetDefinition } from "./get-reddit-comments/redditCommentsGetDefinition.js"
import { requestsGet } from "./get-requests/requestsGet.js"
import { requestsGetDefinition } from "./get-requests/requestsGetDefinition.js"
import { requestsRequestIdGet } from "./get-requests-request-id/requestsRequestIdGet.js"
import { requestsRequestIdGetDefinition } from "./get-requests-request-id/requestsRequestIdGetDefinition.js"
import { reverseGeocodingGet } from "./get-reverse-geocoding/reverseGeocodingGet.js"
import { reverseGeocodingGetDefinition } from "./get-reverse-geocoding/reverseGeocodingGetDefinition.js"
import { screenshoterGet } from "./get-screenshoter/screenshoterGet.js"
import { screenshoterGetDefinition } from "./get-screenshoter/screenshoterGetDefinition.js"
import { shopeeReviewsGet } from "./get-shopee-reviews/shopeeReviewsGet.js"
import { shopeeReviewsGetDefinition } from "./get-shopee-reviews/shopeeReviewsGetDefinition.js"
import { similarwebGet } from "./get-similarweb/similarwebGet.js"
import { similarwebGetDefinition } from "./get-similarweb/similarwebGetDefinition.js"
import { statisticsStatusGet } from "./get-statistics-status/statisticsStatusGet.js"
import { statisticsStatusGetDefinition } from "./get-statistics-status/statisticsStatusGetDefinition.js"
import { targetReviewsGet } from "./get-target-reviews/targetReviewsGet.js"
import { targetReviewsGetDefinition } from "./get-target-reviews/targetReviewsGetDefinition.js"
import { tasksGet } from "./get-tasks/tasksGet.js"
import { tasksGetDefinition } from "./get-tasks/tasksGetDefinition.js"
import { tasksTaskIdGet } from "./get-tasks-task-id/tasksTaskIdGet.js"
import { tasksTaskIdGetDefinition } from "./get-tasks-task-id/tasksTaskIdGetDefinition.js"
import { tiktokCommentsGet } from "./get-tiktok-comments/tiktokCommentsGet.js"
import { tiktokCommentsGetDefinition } from "./get-tiktok-comments/tiktokCommentsGetDefinition.js"
import { tiktokProfilesGet } from "./get-tiktok-profiles/tiktokProfilesGet.js"
import { tiktokProfilesGetDefinition } from "./get-tiktok-profiles/tiktokProfilesGetDefinition.js"
import { tripadvisorReviewsGet } from "./get-tripadvisor-reviews/tripadvisorReviewsGet.js"
import { tripadvisorReviewsGetDefinition } from "./get-tripadvisor-reviews/tripadvisorReviewsGetDefinition.js"
import { tripadvisorSearchGet } from "./get-tripadvisor-search/tripadvisorSearchGet.js"
import { tripadvisorSearchGetDefinition } from "./get-tripadvisor-search/tripadvisorSearchGetDefinition.js"
import { trustpilotGet } from "./get-trustpilot/trustpilotGet.js"
import { trustpilotGetDefinition } from "./get-trustpilot/trustpilotGetDefinition.js"
import { trustpilotReviewsGet } from "./get-trustpilot-reviews/trustpilotReviewsGet.js"
import { trustpilotReviewsGetDefinition } from "./get-trustpilot-reviews/trustpilotReviewsGetDefinition.js"
import { trustpilotSearchGet } from "./get-trustpilot-search/trustpilotSearchGet.js"
import { trustpilotSearchGetDefinition } from "./get-trustpilot-search/trustpilotSearchGetDefinition.js"
import { twitterProfilesGet } from "./get-twitter-profiles/twitterProfilesGet.js"
import { twitterProfilesGetDefinition } from "./get-twitter-profiles/twitterProfilesGetDefinition.js"
import { universalScraperGet } from "./get-universal-scraper/universalScraperGet.js"
import { universalScraperGetDefinition } from "./get-universal-scraper/universalScraperGetDefinition.js"
import { walmartReviewsGet } from "./get-walmart-reviews/walmartReviewsGet.js"
import { walmartReviewsGetDefinition } from "./get-walmart-reviews/walmartReviewsGetDefinition.js"
import { webhookCallsGet } from "./get-webhook-calls/webhookCallsGet.js"
import { webhookCallsGetDefinition } from "./get-webhook-calls/webhookCallsGetDefinition.js"
import { whataspCheckerGet } from "./get-whatasp-checker/whataspCheckerGet.js"
import { whataspCheckerGetDefinition } from "./get-whatasp-checker/whataspCheckerGetDefinition.js"
import { whitepagesAddressesGet } from "./get-whitepages-addresses/whitepagesAddressesGet.js"
import { whitepagesAddressesGetDefinition } from "./get-whitepages-addresses/whitepagesAddressesGetDefinition.js"
import { whitepagesPhonesGet } from "./get-whitepages-phones/whitepagesPhonesGet.js"
import { whitepagesPhonesGetDefinition } from "./get-whitepages-phones/whitepagesPhonesGetDefinition.js"
import { yahooSearchGet } from "./get-yahoo-search/yahooSearchGet.js"
import { yahooSearchGetDefinition } from "./get-yahoo-search/yahooSearchGetDefinition.js"
import { yellowpagesSearchGet } from "./get-yellowpages-search/yellowpagesSearchGet.js"
import { yellowpagesSearchGetDefinition } from "./get-yellowpages-search/yellowpagesSearchGetDefinition.js"
import { yelpBizGet } from "./get-yelp-biz/yelpBizGet.js"
import { yelpBizGetDefinition } from "./get-yelp-biz/yelpBizGetDefinition.js"
import { yelpReviewsGet } from "./get-yelp-reviews/yelpReviewsGet.js"
import { yelpReviewsGetDefinition } from "./get-yelp-reviews/yelpReviewsGetDefinition.js"
import { yelpSearchGet } from "./get-yelp-search/yelpSearchGet.js"
import { yelpSearchGetDefinition } from "./get-yelp-search/yelpSearchGetDefinition.js"
import { youtubeChannelGet } from "./get-youtube-channel/youtubeChannelGet.js"
import { youtubeChannelGetDefinition } from "./get-youtube-channel/youtubeChannelGetDefinition.js"
import { youtubeCommentsGet } from "./get-youtube-comments/youtubeCommentsGet.js"
import { youtubeCommentsGetDefinition } from "./get-youtube-comments/youtubeCommentsGetDefinition.js"
import { youtubeSearchGet } from "./get-youtube-search/youtubeSearchGet.js"
import { youtubeSearchGetDefinition } from "./get-youtube-search/youtubeSearchGetDefinition.js"
import { youtubeTranscriptsGet } from "./get-youtube-transcripts/youtubeTranscriptsGet.js"
import { youtubeTranscriptsGetDefinition } from "./get-youtube-transcripts/youtubeTranscriptsGetDefinition.js"
import { youtubeVideosGet } from "./get-youtube-videos/youtubeVideosGet.js"
import { youtubeVideosGetDefinition } from "./get-youtube-videos/youtubeVideosGetDefinition.js"
import { zillowSearchGet } from "./get-zillow-search/zillowSearchGet.js"
import { zillowSearchGetDefinition } from "./get-zillow-search/zillowSearchGetDefinition.js"
import { businessesPost } from "./post-businesses/businessesPost.js"
import { businessesPostDefinition } from "./post-businesses/businessesPostDefinition.js"
import { googleMapsSearchPost } from "./post-google-maps-search/googleMapsSearchPost.js"
import { googleMapsSearchPostDefinition } from "./post-google-maps-search/googleMapsSearchPostDefinition.js"
import { tasksPost } from "./post-tasks/tasksPost.js"
import { tasksPostDefinition } from "./post-tasks/tasksPostDefinition.js"
import { tasksValidatePost } from "./post-tasks-validate/tasksValidatePost.js"
import { tasksValidatePostDefinition } from "./post-tasks-validate/tasksValidatePostDefinition.js"
import { tasksTaskIdPut } from "./put-tasks-task-id/tasksTaskIdPut.js"
import { tasksTaskIdPutDefinition } from "./put-tasks-task-id/tasksTaskIdPutDefinition.js"

const requestsRequestIdDeleteCliCommand = outscraperCliCommandBuild({
  definition: requestsRequestIdDeleteDefinition,
  execute: requestsRequestIdDelete,
})
const tasksTaskIdDeleteCliCommand = outscraperCliCommandBuild({
  definition: tasksTaskIdDeleteDefinition,
  execute: tasksTaskIdDelete,
})
const aiScraperGetCliCommand = outscraperCliCommandBuild({
  definition: aiScraperGetDefinition,
  execute: aiScraperGet,
})
const airbnbReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: airbnbReviewsGetDefinition,
  execute: airbnbReviewsGet,
})
const airbnbSearchGetCliCommand = outscraperCliCommandBuild({
  definition: airbnbSearchGetDefinition,
  execute: airbnbSearchGet,
})
const amazonProductsGetCliCommand = outscraperCliCommandBuild({
  definition: amazonProductsGetDefinition,
  execute: amazonProductsGet,
})
const amazonReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: amazonReviewsGetDefinition,
  execute: amazonReviewsGet,
})
const appstoreReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: appstoreReviewsGetDefinition,
  execute: appstoreReviewsGet,
})
const bingMapsGetCliCommand = outscraperCliCommandBuild({
  definition: bingMapsGetDefinition,
  execute: bingMapsGet,
})
const bookingPricesGetCliCommand = outscraperCliCommandBuild({
  definition: bookingPricesGetDefinition,
  execute: bookingPricesGet,
})
const bookingReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: bookingReviewsGetDefinition,
  execute: bookingReviewsGet,
})
const bookingSearchGetCliCommand = outscraperCliCommandBuild({
  definition: bookingSearchGetDefinition,
  execute: bookingSearchGet,
})
const businessesBusinessIdGetCliCommand = outscraperCliCommandBuild({
  definition: businessesBusinessIdGetDefinition,
  execute: businessesBusinessIdGet,
})
const businessesSimilarDomainGetCliCommand = outscraperCliCommandBuild({
  definition: businessesSimilarDomainGetDefinition,
  execute: businessesSimilarDomainGet,
})
const capterraReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: capterraReviewsGetDefinition,
  execute: capterraReviewsGet,
})
const companyInsightsGetCliCommand = outscraperCliCommandBuild({
  definition: companyInsightsGetDefinition,
  execute: companyInsightsGet,
})
const companyWebsiteFinderGetCliCommand = outscraperCliCommandBuild({
  definition: companyWebsiteFinderGetDefinition,
  execute: companyWebsiteFinderGet,
})
const deliverooGetCliCommand = outscraperCliCommandBuild({
  definition: deliverooGetDefinition,
  execute: deliverooGet,
})
const deliverooReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: deliverooReviewsGetDefinition,
  execute: deliverooReviewsGet,
})
const disposableEmailCheckerGetCliCommand = outscraperCliCommandBuild({
  definition: disposableEmailCheckerGetDefinition,
  execute: disposableEmailCheckerGet,
})
const emailValidatorGetCliCommand = outscraperCliCommandBuild({
  definition: emailValidatorGetDefinition,
  execute: emailValidatorGet,
})
const emailsAndContactsGetCliCommand = outscraperCliCommandBuild({
  definition: emailsAndContactsGetDefinition,
  execute: emailsAndContactsGet,
})
const emailsFinderGetCliCommand = outscraperCliCommandBuild({
  definition: emailsFinderGetDefinition,
  execute: emailsFinderGet,
})
const etsyProductsGetCliCommand = outscraperCliCommandBuild({
  definition: etsyProductsGetDefinition,
  execute: etsyProductsGet,
})
const etsyReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: etsyReviewsGetDefinition,
  execute: etsyReviewsGet,
})
const expediaReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: expediaReviewsGetDefinition,
  execute: expediaReviewsGet,
})
const expediaSearchGetCliCommand = outscraperCliCommandBuild({
  definition: expediaSearchGetDefinition,
  execute: expediaSearchGet,
})
const g2ReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: g2ReviewsGetDefinition,
  execute: g2ReviewsGet,
})
const geocodingGetCliCommand = outscraperCliCommandBuild({
  definition: geocodingGetDefinition,
  execute: geocodingGet,
})
const getappReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: getappReviewsGetDefinition,
  execute: getappReviewsGet,
})
const glassdoorReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: glassdoorReviewsGetDefinition,
  execute: glassdoorReviewsGet,
})
const googleMapsAutocompleteGetCliCommand = outscraperCliCommandBuild({
  definition: googleMapsAutocompleteGetDefinition,
  execute: googleMapsAutocompleteGet,
})
const googleMapsDirectionsGetCliCommand = outscraperCliCommandBuild({
  definition: googleMapsDirectionsGetDefinition,
  execute: googleMapsDirectionsGet,
})
const googleMapsDirectoryGetCliCommand = outscraperCliCommandBuild({
  definition: googleMapsDirectoryGetDefinition,
  execute: googleMapsDirectoryGet,
})
const googleMapsPhotosGetCliCommand = outscraperCliCommandBuild({
  definition: googleMapsPhotosGetDefinition,
  execute: googleMapsPhotosGet,
})
const googleMapsReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: googleMapsReviewsGetDefinition,
  execute: googleMapsReviewsGet,
})
const googleMapsSearchGetCliCommand = outscraperCliCommandBuild({
  definition: googleMapsSearchGetDefinition,
  execute: googleMapsSearchGet,
})
const googleMapsSuggestionsGetCliCommand = outscraperCliCommandBuild({
  definition: googleMapsSuggestionsGetDefinition,
  execute: googleMapsSuggestionsGet,
})
const googlePlacesByDomainGetCliCommand = outscraperCliCommandBuild({
  definition: googlePlacesByDomainGetDefinition,
  execute: googlePlacesByDomainGet,
})
const googlePlayReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: googlePlayReviewsGetDefinition,
  execute: googlePlayReviewsGet,
})
const googleSearchGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchGetDefinition,
  execute: googleSearchGet,
})
const googleSearchAutocompleteGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchAutocompleteGetDefinition,
  execute: googleSearchAutocompleteGet,
})
const googleSearchCareersGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchCareersGetDefinition,
  execute: googleSearchCareersGet,
})
const googleSearchEventsGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchEventsGetDefinition,
  execute: googleSearchEventsGet,
})
const googleSearchFlightsGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchFlightsGetDefinition,
  execute: googleSearchFlightsGet,
})
const googleSearchImagesGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchImagesGetDefinition,
  execute: googleSearchImagesGet,
})
const googleSearchJobsGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchJobsGetDefinition,
  execute: googleSearchJobsGet,
})
const googleSearchNewsGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchNewsGetDefinition,
  execute: googleSearchNewsGet,
})
const googleSearchShoppingGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchShoppingGetDefinition,
  execute: googleSearchShoppingGet,
})
const googleSearchVideosGetCliCommand = outscraperCliCommandBuild({
  definition: googleSearchVideosGetDefinition,
  execute: googleSearchVideosGet,
})
const googleShoppingReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: googleShoppingReviewsGetDefinition,
  execute: googleShoppingReviewsGet,
})
const googleTrendsGetCliCommand = outscraperCliCommandBuild({
  definition: googleTrendsGetDefinition,
  execute: googleTrendsGet,
})
const hotelsSearchGetCliCommand = outscraperCliCommandBuild({
  definition: hotelsSearchGetDefinition,
  execute: hotelsSearchGet,
})
const indeedReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: indeedReviewsGetDefinition,
  execute: indeedReviewsGet,
})
const indeedSearchGetCliCommand = outscraperCliCommandBuild({
  definition: indeedSearchGetDefinition,
  execute: indeedSearchGet,
})
const invoicesGetCliCommand = outscraperCliCommandBuild({
  definition: invoicesGetDefinition,
  execute: invoicesGet,
})
const leadsAndContactsGetCliCommand = outscraperCliCommandBuild({
  definition: leadsAndContactsGetDefinition,
  execute: leadsAndContactsGet,
})
const linkedinCompaniesGetCliCommand = outscraperCliCommandBuild({
  definition: linkedinCompaniesGetDefinition,
  execute: linkedinCompaniesGet,
})
const linkedinPostsGetCliCommand = outscraperCliCommandBuild({
  definition: linkedinPostsGetDefinition,
  execute: linkedinPostsGet,
})
const linkedinProfilesGetCliCommand = outscraperCliCommandBuild({
  definition: linkedinProfilesGetDefinition,
  execute: linkedinProfilesGet,
})
const locationsGetCliCommand = outscraperCliCommandBuild({
  definition: locationsGetDefinition,
  execute: locationsGet,
})
const mapsSearchGetCliCommand = outscraperCliCommandBuild({
  definition: mapsSearchGetDefinition,
  execute: mapsSearchGet,
})
const phonesEnricherGetCliCommand = outscraperCliCommandBuild({
  definition: phonesEnricherGetDefinition,
  execute: phonesEnricherGet,
})
const phonesOwnersGetCliCommand = outscraperCliCommandBuild({
  definition: phonesOwnersGetDefinition,
  execute: phonesOwnersGet,
})
const producthuntReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: producthuntReviewsGetDefinition,
  execute: producthuntReviewsGet,
})
const profileBalanceGetCliCommand = outscraperCliCommandBuild({
  definition: profileBalanceGetDefinition,
  execute: profileBalanceGet,
})
const redditCommentsGetCliCommand = outscraperCliCommandBuild({
  definition: redditCommentsGetDefinition,
  execute: redditCommentsGet,
})
const requestsGetCliCommand = outscraperCliCommandBuild({
  definition: requestsGetDefinition,
  execute: requestsGet,
})
const requestsRequestIdGetCliCommand = outscraperCliCommandBuild({
  definition: requestsRequestIdGetDefinition,
  execute: requestsRequestIdGet,
})
const reverseGeocodingGetCliCommand = outscraperCliCommandBuild({
  definition: reverseGeocodingGetDefinition,
  execute: reverseGeocodingGet,
})
const screenshoterGetCliCommand = outscraperCliCommandBuild({
  definition: screenshoterGetDefinition,
  execute: screenshoterGet,
})
const shopeeReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: shopeeReviewsGetDefinition,
  execute: shopeeReviewsGet,
})
const similarwebGetCliCommand = outscraperCliCommandBuild({
  definition: similarwebGetDefinition,
  execute: similarwebGet,
})
const statisticsStatusGetCliCommand = outscraperCliCommandBuild({
  definition: statisticsStatusGetDefinition,
  execute: statisticsStatusGet,
})
const targetReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: targetReviewsGetDefinition,
  execute: targetReviewsGet,
})
const tasksGetCliCommand = outscraperCliCommandBuild({
  definition: tasksGetDefinition,
  execute: tasksGet,
})
const tasksTaskIdGetCliCommand = outscraperCliCommandBuild({
  definition: tasksTaskIdGetDefinition,
  execute: tasksTaskIdGet,
})
const tiktokCommentsGetCliCommand = outscraperCliCommandBuild({
  definition: tiktokCommentsGetDefinition,
  execute: tiktokCommentsGet,
})
const tiktokProfilesGetCliCommand = outscraperCliCommandBuild({
  definition: tiktokProfilesGetDefinition,
  execute: tiktokProfilesGet,
})
const tripadvisorReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: tripadvisorReviewsGetDefinition,
  execute: tripadvisorReviewsGet,
})
const tripadvisorSearchGetCliCommand = outscraperCliCommandBuild({
  definition: tripadvisorSearchGetDefinition,
  execute: tripadvisorSearchGet,
})
const trustpilotGetCliCommand = outscraperCliCommandBuild({
  definition: trustpilotGetDefinition,
  execute: trustpilotGet,
})
const trustpilotReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: trustpilotReviewsGetDefinition,
  execute: trustpilotReviewsGet,
})
const trustpilotSearchGetCliCommand = outscraperCliCommandBuild({
  definition: trustpilotSearchGetDefinition,
  execute: trustpilotSearchGet,
})
const twitterProfilesGetCliCommand = outscraperCliCommandBuild({
  definition: twitterProfilesGetDefinition,
  execute: twitterProfilesGet,
})
const universalScraperGetCliCommand = outscraperCliCommandBuild({
  definition: universalScraperGetDefinition,
  execute: universalScraperGet,
})
const walmartReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: walmartReviewsGetDefinition,
  execute: walmartReviewsGet,
})
const webhookCallsGetCliCommand = outscraperCliCommandBuild({
  definition: webhookCallsGetDefinition,
  execute: webhookCallsGet,
})
const whataspCheckerGetCliCommand = outscraperCliCommandBuild({
  definition: whataspCheckerGetDefinition,
  execute: whataspCheckerGet,
})
const whitepagesAddressesGetCliCommand = outscraperCliCommandBuild({
  definition: whitepagesAddressesGetDefinition,
  execute: whitepagesAddressesGet,
})
const whitepagesPhonesGetCliCommand = outscraperCliCommandBuild({
  definition: whitepagesPhonesGetDefinition,
  execute: whitepagesPhonesGet,
})
const yahooSearchGetCliCommand = outscraperCliCommandBuild({
  definition: yahooSearchGetDefinition,
  execute: yahooSearchGet,
})
const yellowpagesSearchGetCliCommand = outscraperCliCommandBuild({
  definition: yellowpagesSearchGetDefinition,
  execute: yellowpagesSearchGet,
})
const yelpBizGetCliCommand = outscraperCliCommandBuild({
  definition: yelpBizGetDefinition,
  execute: yelpBizGet,
})
const yelpReviewsGetCliCommand = outscraperCliCommandBuild({
  definition: yelpReviewsGetDefinition,
  execute: yelpReviewsGet,
})
const yelpSearchGetCliCommand = outscraperCliCommandBuild({
  definition: yelpSearchGetDefinition,
  execute: yelpSearchGet,
})
const youtubeChannelGetCliCommand = outscraperCliCommandBuild({
  definition: youtubeChannelGetDefinition,
  execute: youtubeChannelGet,
})
const youtubeCommentsGetCliCommand = outscraperCliCommandBuild({
  definition: youtubeCommentsGetDefinition,
  execute: youtubeCommentsGet,
})
const youtubeSearchGetCliCommand = outscraperCliCommandBuild({
  definition: youtubeSearchGetDefinition,
  execute: youtubeSearchGet,
})
const youtubeTranscriptsGetCliCommand = outscraperCliCommandBuild({
  definition: youtubeTranscriptsGetDefinition,
  execute: youtubeTranscriptsGet,
})
const youtubeVideosGetCliCommand = outscraperCliCommandBuild({
  definition: youtubeVideosGetDefinition,
  execute: youtubeVideosGet,
})
const zillowSearchGetCliCommand = outscraperCliCommandBuild({
  definition: zillowSearchGetDefinition,
  execute: zillowSearchGet,
})
const businessesPostCliCommand = outscraperCliCommandBuild({
  definition: businessesPostDefinition,
  execute: businessesPost,
})
const googleMapsSearchPostCliCommand = outscraperCliCommandBuild({
  definition: googleMapsSearchPostDefinition,
  execute: googleMapsSearchPost,
})
const tasksPostCliCommand = outscraperCliCommandBuild({
  definition: tasksPostDefinition,
  execute: tasksPost,
})
const tasksValidatePostCliCommand = outscraperCliCommandBuild({
  definition: tasksValidatePostDefinition,
  execute: tasksValidatePost,
})
const tasksTaskIdPutCliCommand = outscraperCliCommandBuild({
  definition: tasksTaskIdPutDefinition,
  execute: tasksTaskIdPut,
})

const deleteCliCommands = buildRouteMap({
  routes: {
    "requests-request-id": requestsRequestIdDeleteCliCommand,
    "tasks-task-id": tasksTaskIdDeleteCliCommand,
  },
  docs: { brief: "DELETE endpoint operations" },
})
const getCliCommands = buildRouteMap({
  routes: {
    "ai-scraper": aiScraperGetCliCommand,
    "airbnb-reviews": airbnbReviewsGetCliCommand,
    "airbnb-search": airbnbSearchGetCliCommand,
    "amazon-products": amazonProductsGetCliCommand,
    "amazon-reviews": amazonReviewsGetCliCommand,
    "appstore-reviews": appstoreReviewsGetCliCommand,
    "bing-maps": bingMapsGetCliCommand,
    "booking-prices": bookingPricesGetCliCommand,
    "booking-reviews": bookingReviewsGetCliCommand,
    "booking-search": bookingSearchGetCliCommand,
    "businesses-business-id": businessesBusinessIdGetCliCommand,
    "businesses-similar-domain": businessesSimilarDomainGetCliCommand,
    "capterra-reviews": capterraReviewsGetCliCommand,
    "company-insights": companyInsightsGetCliCommand,
    "company-website-finder": companyWebsiteFinderGetCliCommand,
    deliveroo: deliverooGetCliCommand,
    "deliveroo-reviews": deliverooReviewsGetCliCommand,
    "disposable-email-checker": disposableEmailCheckerGetCliCommand,
    "email-validator": emailValidatorGetCliCommand,
    "emails-and-contacts": emailsAndContactsGetCliCommand,
    "emails-finder": emailsFinderGetCliCommand,
    "etsy-products": etsyProductsGetCliCommand,
    "etsy-reviews": etsyReviewsGetCliCommand,
    "expedia-reviews": expediaReviewsGetCliCommand,
    "expedia-search": expediaSearchGetCliCommand,
    "g2-reviews": g2ReviewsGetCliCommand,
    geocoding: geocodingGetCliCommand,
    "getapp-reviews": getappReviewsGetCliCommand,
    "glassdoor-reviews": glassdoorReviewsGetCliCommand,
    "google-maps-autocomplete": googleMapsAutocompleteGetCliCommand,
    "google-maps-directions": googleMapsDirectionsGetCliCommand,
    "google-maps-directory": googleMapsDirectoryGetCliCommand,
    "google-maps-photos": googleMapsPhotosGetCliCommand,
    "google-maps-reviews": googleMapsReviewsGetCliCommand,
    "google-maps-search": googleMapsSearchGetCliCommand,
    "google-maps-suggestions": googleMapsSuggestionsGetCliCommand,
    "google-places-by-domain": googlePlacesByDomainGetCliCommand,
    "google-play-reviews": googlePlayReviewsGetCliCommand,
    "google-search": googleSearchGetCliCommand,
    "google-search-autocomplete": googleSearchAutocompleteGetCliCommand,
    "google-search-careers": googleSearchCareersGetCliCommand,
    "google-search-events": googleSearchEventsGetCliCommand,
    "google-search-flights": googleSearchFlightsGetCliCommand,
    "google-search-images": googleSearchImagesGetCliCommand,
    "google-search-jobs": googleSearchJobsGetCliCommand,
    "google-search-news": googleSearchNewsGetCliCommand,
    "google-search-shopping": googleSearchShoppingGetCliCommand,
    "google-search-videos": googleSearchVideosGetCliCommand,
    "google-shopping-reviews": googleShoppingReviewsGetCliCommand,
    "google-trends": googleTrendsGetCliCommand,
    "hotels-search": hotelsSearchGetCliCommand,
    "indeed-reviews": indeedReviewsGetCliCommand,
    "indeed-search": indeedSearchGetCliCommand,
    invoices: invoicesGetCliCommand,
    "leads-and-contacts": leadsAndContactsGetCliCommand,
    "linkedin-companies": linkedinCompaniesGetCliCommand,
    "linkedin-posts": linkedinPostsGetCliCommand,
    "linkedin-profiles": linkedinProfilesGetCliCommand,
    locations: locationsGetCliCommand,
    "maps-search": mapsSearchGetCliCommand,
    "phones-enricher": phonesEnricherGetCliCommand,
    "phones-owners": phonesOwnersGetCliCommand,
    "producthunt-reviews": producthuntReviewsGetCliCommand,
    "profile-balance": profileBalanceGetCliCommand,
    "reddit-comments": redditCommentsGetCliCommand,
    requests: requestsGetCliCommand,
    "requests-request-id": requestsRequestIdGetCliCommand,
    "reverse-geocoding": reverseGeocodingGetCliCommand,
    screenshoter: screenshoterGetCliCommand,
    "shopee-reviews": shopeeReviewsGetCliCommand,
    similarweb: similarwebGetCliCommand,
    "statistics-status": statisticsStatusGetCliCommand,
    "target-reviews": targetReviewsGetCliCommand,
    tasks: tasksGetCliCommand,
    "tasks-task-id": tasksTaskIdGetCliCommand,
    "tiktok-comments": tiktokCommentsGetCliCommand,
    "tiktok-profiles": tiktokProfilesGetCliCommand,
    "tripadvisor-reviews": tripadvisorReviewsGetCliCommand,
    "tripadvisor-search": tripadvisorSearchGetCliCommand,
    trustpilot: trustpilotGetCliCommand,
    "trustpilot-reviews": trustpilotReviewsGetCliCommand,
    "trustpilot-search": trustpilotSearchGetCliCommand,
    "twitter-profiles": twitterProfilesGetCliCommand,
    "universal-scraper": universalScraperGetCliCommand,
    "walmart-reviews": walmartReviewsGetCliCommand,
    "webhook-calls": webhookCallsGetCliCommand,
    "whatasp-checker": whataspCheckerGetCliCommand,
    "whitepages-addresses": whitepagesAddressesGetCliCommand,
    "whitepages-phones": whitepagesPhonesGetCliCommand,
    "yahoo-search": yahooSearchGetCliCommand,
    "yellowpages-search": yellowpagesSearchGetCliCommand,
    "yelp-biz": yelpBizGetCliCommand,
    "yelp-reviews": yelpReviewsGetCliCommand,
    "yelp-search": yelpSearchGetCliCommand,
    "youtube-channel": youtubeChannelGetCliCommand,
    "youtube-comments": youtubeCommentsGetCliCommand,
    "youtube-search": youtubeSearchGetCliCommand,
    "youtube-transcripts": youtubeTranscriptsGetCliCommand,
    "youtube-videos": youtubeVideosGetCliCommand,
    "zillow-search": zillowSearchGetCliCommand,
  },
  docs: { brief: "GET endpoint operations" },
})
const postCliCommands = buildRouteMap({
  routes: {
    businesses: businessesPostCliCommand,
    "google-maps-search": googleMapsSearchPostCliCommand,
    tasks: tasksPostCliCommand,
    "tasks-validate": tasksValidatePostCliCommand,
  },
  docs: { brief: "POST endpoint operations" },
})
const putCliCommands = buildRouteMap({
  routes: {
    "tasks-task-id": tasksTaskIdPutCliCommand,
  },
  docs: { brief: "PUT endpoint operations" },
})

export const outscraperGeneratedCliCommands = buildRouteMap({
  routes: {
    delete: deleteCliCommands,
    get: getCliCommands,
    post: postCliCommands,
    put: putCliCommands,
  },
  docs: { brief: "Outscraper API endpoint operations" },
})
