/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const etsyReviewsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            author_title: v.optional(v.unknown()),
            author_url: v.optional(v.unknown()),
            product_name: v.optional(v.unknown()),
            product_url: v.optional(v.unknown()),
            review_date: v.optional(v.unknown()),
            review_rating: v.optional(v.unknown()),
            review_text: v.optional(v.unknown()),
            review_timestamp: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type EtsyReviewsGetResponse = v.InferOutput<typeof etsyReviewsGetResponseSchema>
