/* Generated by openApiCatalogGenerate. Do not edit. */
export const etsyReviewsGetDefinition = {
  description: "Returns reviews from a list of Etsy products.",
  folder: "get-etsy-reviews",
  method: "GET",
  operationId: "getEtsy-Reviews",
  parameters: [
    {
      description:
        "The parameter defines the way you want to submit your task to Outscraper. It can be set to `false` to open an HTTP connection and keep it open until you get your results, or `true` (default) to just submit your requests to Outscraper and retrieve them later (usually within 1-3 minutes) with the [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.\n\nA good practice is to send async requests and start checking the results after the estimated execution time. Check out [this](https://github.com/outscraper/outscraper-python/blob/master/examples/Run%20Async%20Requests.md) Python implementation as an example.\n\nAs most of the requests take some time to be executed the `async=true` option is preferred to avoid HTTP request timeouts.",
      example: false,
      in: "query",
      location: "query",
      name: "async",
      required: true,
      schema: {
        default: true,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter specifies the oldest timestamp value for items. \n\nUsing the `cutoff` parameter overwrites `sort` parameter`. Therefore, the latest records will be at the beginning (newest first).",
      in: "query",
      location: "query",
      name: "cutoff",
      required: false,
      schema: {
        type: "integer",
      },
    },
    {
      description:
        "The parameter defines which fields you want to include with each item returned in the response. By default, it returns all fields. Use `&fields=query,name` to return only the specific ones.",
      in: "query",
      location: "query",
      name: "fields",
      required: false,
      schema: {
        type: "string",
      },
    },
    {
      description:
        "The parameter defines the format of the output data. Using this parameter overwrites the `ui` parameter to `true`.",
      in: "query",
      location: "query",
      name: "format",
      required: false,
      schema: {
        collectionFormat: "csv",
        items: {
          default: "xlsx",
          enum: ["xlsx", "csv", "json", "parquet"],
          type: "string",
        },
        type: "array",
      },
    },
    {
      description: "The parameter specifies the limit of reviews to get from one query.",
      in: "query",
      location: "query",
      name: "limit",
      required: false,
      schema: {
        default: 100,
        type: "integer",
      },
    },
    {
      description:
        "You can use Etsy listing review URLs or shop review URLs (e.g., `https://www.etsy.com/listing/1234567890/reviews`, `https://www.etsy.com/shop/ExampleShop/reviews`). \n\nIt supports batching by sending arrays with up to `1000` queries (e.g., `query=text1&query=text2&query=text3`). It allows multiple queries to be sent in one request and to save on network latency time.",
      in: "query",
      location: "query",
      name: "query",
      required: true,
      schema: {
        collectionFormat: "csv",
        items: {
          type: "string",
        },
        type: "array",
      },
    },
    {
      description: "The parameter specifies one of the sorting types.",
      in: "query",
      location: "query",
      name: "sort",
      required: false,
      schema: {
        default: "Relevancy",
        enum: ["Relevancy", "Recency", "Highest", "Lowest"],
        type: "string",
      },
    },
    {
      description:
        "The parameter defines whether a task will be executed as a UI task. This is commonly used when you want to create a regular platform task with API.\n\nUsing this parameter overwrites the `async` parameter to `true`.",
      in: "query",
      location: "query",
      name: "ui",
      required: false,
      schema: {
        default: false,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines the URL address (callback) to which Outscraper will create a POST request with a JSON body once a task/request is finished.\n\nUsing this parameter overwrites the webhook from integrations.",
      in: "query",
      location: "query",
      name: "webhook",
      required: false,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/etsy-reviews",
  responses: [
    {
      content: [
        {
          example: {
            data: [
              [
                {
                  author_title: "Emma",
                  author_url: "https://www.etsy.com/people/examplebuyer",
                  product_name: "Personalized Leather Tote Bag",
                  product_url: "https://www.etsy.com/listing/1234567890/personalized-leather-tote-bag",
                  review_date: "Jan 15, 2024",
                  review_rating: 5,
                  review_text: "Beautiful quality and fast shipping.",
                  review_timestamp: 1705276800,
                },
              ],
            ],
            id: "your-request-id",
            status: "Success",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: {},
      status: "200",
    },
    {
      content: [
        {
          example: {
            id: "your-request-id",
            results_location: "https://api.outscraper.cloud/requests/your-request-id",
            status: "Pending",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description:
        "The response contains a request ID that can be used to fetch results by using [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.",
      status: "202",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage: "Please close past due invoices or verify your card information is correct.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Past due invoices or a payment method not connected.",
      status: "402",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Invalid query URL parameters.",
      status: "422",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Etsy Reviews",
  tags: ["Etsy", "Reviews & Comments"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source:
        'curl -X GET "https://api.outscraper.cloud/etsy-reviews?query=https://www.etsy.com/listing/1234567890/reviews&limit=3&sort=Recency&async=false" -H  "X-API-KEY: YOUR-API-KEY"',
    },
    {
      lang: "cURL (async)",
      source:
        'curl -X GET "https://api.outscraper.cloud/etsy-reviews?query=https://www.etsy.com/listing/1234567890/reviews&limit=3&sort=Recency" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
