/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import {
  type GoogleSearchImagesGetInput,
  googleSearchImagesGetInputSchema,
} from "./googleSearchImagesGetInputSchema.js"
import {
  type GoogleSearchImagesGetResponse,
  googleSearchImagesGetResponseSchema,
} from "./googleSearchImagesGetResponseSchema.js"

export async function googleSearchImagesGet(
  client: OutscraperClient,
  input: GoogleSearchImagesGetInput,
): Promise<Result<GoogleSearchImagesGetResponse>> {
  const op = "googleSearchImagesGet"
  const parsed = v.safeParse(googleSearchImagesGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid googleSearchImagesGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/google-search-images",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: googleSearchImagesGetResponseSchema,
  })
}
