/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const googleSearchImagesGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            original_image: v.optional(v.unknown()),
            position: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            source: v.optional(v.unknown()),
            source_link: v.optional(v.unknown()),
            title: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type GoogleSearchImagesGetResponse = v.InferOutput<typeof googleSearchImagesGetResponseSchema>
