/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type IndeedSearchGetInput, indeedSearchGetInputSchema } from "./indeedSearchGetInputSchema.js"
import { type IndeedSearchGetResponse, indeedSearchGetResponseSchema } from "./indeedSearchGetResponseSchema.js"

export async function indeedSearchGet(
  client: OutscraperClient,
  input: IndeedSearchGetInput,
): Promise<Result<IndeedSearchGetResponse>> {
  const op = "indeedSearchGet"
  const parsed = v.safeParse(indeedSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid indeedSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/indeed-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: indeedSearchGetResponseSchema,
  })
}
