/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const indeedSearchGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            company: v.optional(v.unknown()),
            createDate: v.optional(v.unknown()),
            displayTitle: v.optional(v.unknown()),
            formattedLocation: v.optional(v.unknown()),
            jobLocationCity: v.optional(v.unknown()),
            jobLocationState: v.optional(v.unknown()),
            normTitle: v.optional(v.unknown()),
            pubDate: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            remoteLocation: v.optional(v.unknown()),
            salarySnippet: v.optional(v.unknown()),
            showJobType: v.optional(v.unknown()),
            snippet: v.optional(v.unknown()),
            title: v.optional(v.unknown()),
            viewJobLink: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type IndeedSearchGetResponse = v.InferOutput<typeof indeedSearchGetResponseSchema>
