/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksTaskIdGetResponseSchema = v.looseObject({
  created: v.optional(v.nullable(v.string())),
  id: v.optional(v.nullable(v.string())),
  metadata: v.optional(
    v.looseObject({
      queries: v.optional(v.array(v.nullable(v.string()))),
      service_name: v.optional(v.nullable(v.string())),
    }),
  ),
  queue_task_id: v.optional(v.nullable(v.string())),
  results: v.optional(
    v.array(
      v.looseObject({
        file_url: v.optional(v.nullable(v.string())),
        product_name: v.optional(v.nullable(v.string())),
        quantity: v.optional(v.nullable(v.number())),
      }),
    ),
  ),
  status: v.optional(v.nullable(v.string())),
  updated: v.optional(v.nullable(v.string())),
  user_id: v.optional(v.nullable(v.string())),
})

export type TasksTaskIdGetResponse = v.InferOutput<typeof tasksTaskIdGetResponseSchema>
