/* Generated by openApiCatalogGenerate. Do not edit. */
export const tasksTaskIdGetDefinition = {
  description: "Fetch user task.",
  folder: "get-tasks-task-id",
  method: "GET",
  operationId: "getTasks-TaskId",
  parameters: [
    {
      description: "Task ID. Example: `20211211132758c8e9`",
      in: "path",
      location: "path",
      name: "taskId",
      required: true,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/tasks/{taskId}",
  responses: [
    {
      content: [
        {
          example: {
            created: "2022-02-08T20:49:06.879078",
            id: "YOUR_TASK_ID",
            metadata: {
              queries: ["bars ny usa", "restaurants ny usa"],
              service_name: "google_maps_service_v2",
            },
            queue_task_id: "2b9aa187-281a-4d4e-a4c6-fbe941aaac34",
            results: [
              {
                file_url: "LINK_TO_RESULTS",
                product_name: "Google Maps Data",
                quantity: 509,
              },
              {
                product_name: "Domains",
                quantity: 509,
              },
            ],
            status: "SUCCESS",
            updated: "2022-02-08T20:51:17.402668",
            user_id: "YOUR_USER_ID",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "User task.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Get Task",
  tags: ["Platform & Dashboard"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X GET "https://api.outscraper.cloud/tasks/YOUR_TASK_ID" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
