/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TasksTaskIdGetInput, tasksTaskIdGetInputSchema } from "./tasksTaskIdGetInputSchema.js"
import { type TasksTaskIdGetResponse, tasksTaskIdGetResponseSchema } from "./tasksTaskIdGetResponseSchema.js"

export async function tasksTaskIdGet(
  client: OutscraperClient,
  input: TasksTaskIdGetInput,
): Promise<Result<TasksTaskIdGetResponse>> {
  const op = "tasksTaskIdGet"
  const parsed = v.safeParse(tasksTaskIdGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid tasksTaskIdGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/tasks/{taskId}",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: tasksTaskIdGetResponseSchema,
  })
}
