/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const tasksTaskIdGetInputSchema =
  /* tasksTaskIdGet input is grouped by HTTP argument location. */
  v.object({
    path: v.looseObject({ taskId: v.string() }),
    query: v.optional(v.looseObject({}), {}),
    headers: v.optional(v.looseObject({}), {}),
  })

export type TasksTaskIdGetInput = v.InferInput<typeof tasksTaskIdGetInputSchema>
