/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type EmailValidatorGetInput, emailValidatorGetInputSchema } from "./emailValidatorGetInputSchema.js"
import { type EmailValidatorGetResponse, emailValidatorGetResponseSchema } from "./emailValidatorGetResponseSchema.js"

export async function emailValidatorGet(
  client: OutscraperClient,
  input: EmailValidatorGetInput,
): Promise<Result<EmailValidatorGetResponse>> {
  const op = "emailValidatorGet"
  const parsed = v.safeParse(emailValidatorGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid emailValidatorGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/email-validator",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: emailValidatorGetResponseSchema,
  })
}
