/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type LinkedinPostsGetInput, linkedinPostsGetInputSchema } from "./linkedinPostsGetInputSchema.js"
import { type LinkedinPostsGetResponse, linkedinPostsGetResponseSchema } from "./linkedinPostsGetResponseSchema.js"

export async function linkedinPostsGet(
  client: OutscraperClient,
  input: LinkedinPostsGetInput,
): Promise<Result<LinkedinPostsGetResponse>> {
  const op = "linkedinPostsGet"
  const parsed = v.safeParse(linkedinPostsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid linkedinPostsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/linkedin-posts",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: linkedinPostsGetResponseSchema,
  })
}
