/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type AmazonProductsGetInput, amazonProductsGetInputSchema } from "./amazonProductsGetInputSchema.js"
import { type AmazonProductsGetResponse, amazonProductsGetResponseSchema } from "./amazonProductsGetResponseSchema.js"

export async function amazonProductsGet(
  client: OutscraperClient,
  input: AmazonProductsGetInput,
): Promise<Result<AmazonProductsGetResponse>> {
  const op = "amazonProductsGet"
  const parsed = v.safeParse(amazonProductsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid amazonProductsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/amazon-products",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: amazonProductsGetResponseSchema,
  })
}
