/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const amazonProductsGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            about: v.optional(v.unknown()),
            answered_questions: v.optional(v.unknown()),
            asin: v.optional(v.unknown()),
            availability: v.optional(v.unknown()),
            bage: v.optional(v.unknown()),
            categories: v.optional(v.unknown()),
            currency: v.optional(v.unknown()),
            description: v.optional(v.unknown()),
            details: v.optional(v.unknown()),
            fast_track_message: v.optional(v.unknown()),
            image_1: v.optional(v.unknown()),
            image_2: v.optional(v.unknown()),
            image_3: v.optional(v.unknown()),
            image_4: v.optional(v.unknown()),
            image_5: v.optional(v.unknown()),
            merchant_info: v.optional(v.unknown()),
            name: v.optional(v.unknown()),
            overview: v.optional(v.unknown()),
            price: v.optional(v.unknown()),
            price_saving: v.optional(v.unknown()),
            rating: v.optional(v.unknown()),
            reviews: v.optional(v.unknown()),
            shipping: v.optional(v.unknown()),
            short_url: v.optional(v.unknown()),
            store_title: v.optional(v.unknown()),
            store_url: v.optional(v.unknown()),
            strike_price: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type AmazonProductsGetResponse = v.InferOutput<typeof amazonProductsGetResponseSchema>
