/* Generated by openApiCatalogGenerate. Do not edit. */
export const yelpSearchGetDefinition = {
  description: "Returns search results from Yelp.",
  folder: "get-yelp-search",
  method: "GET",
  operationId: "getYelp-Search",
  parameters: [
    {
      description:
        "The parameter defines the way you want to submit your task to Outscraper. It can be set to `false` to open an HTTP connection and keep it open until you get your results, or `true` (default) to just submit your requests to Outscraper and retrieve them later (usually within 1-3 minutes) with the [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.\n\nA good practice is to send async requests and start checking the results after the estimated execution time. Check out [this](https://github.com/outscraper/outscraper-python/blob/master/examples/Run%20Async%20Requests.md) Python implementation as an example.\n\nAs most of the requests take some time to be executed the `async=true` option is preferred to avoid HTTP request timeouts.",
      example: false,
      in: "query",
      location: "query",
      name: "async",
      required: true,
      schema: {
        default: true,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines one or more enrichments you want to apply to the results (e.g., `enrichment=enrichment1&enrichment=enrichment2&enrichment=enrichment3`).\n\nAvailable values:\n\n `leads_n_contacts` — **Leads & Contacts Enrichment**: finds emails, social links, phones, and other contacts from websites;\n\n `emails_validator_service` — **Email Address Verifier**: validates emails, checks deliverability, filters out blacklists, spam traps, and complainers, while significantly reducing your bounce rate;\n\n `company_websites_finder` - **Company Website Finder**: finds company websites based on business names;\n\n `disposable_email_checker` — **Disposable Emails Checker**: checks origins of email addresses (disposable, free, or corporate);\n\n `company_insights_service` — **Company Insights**: Finds company firmographics such as revenue, size, founding year, public status, etc.;\n\n `phones_enricher_service` — **Phone Numbers Enricher**: returns phones carrier data (name/type), validates phones, ensures message deliverability, \n\n `trustpilot_service` — **Trustpilot Scraper**: returns data from a list of businesses, \n\n `whitepages_phones` - **Phone Identity Finder**: returns insights about phone number owners (name, address, etc.);\n\n `ai_chain_info` - **Chain Info**: identifies if a business is part of a chain, adding a true/false indication to your data for smarter targeting. \n\nUsing enrichments increases the time of the response. You might want to use the `async=true` parameter to avoid getting timeouts.",
      explode: false,
      in: "query",
      location: "query",
      name: "enrichment",
      required: false,
      schema: {
        collectionFormat: "csv",
        items: {
          enum: [
            "leads_n_contacts",
            "emails_validator_service",
            "company_websites_finder",
            "disposable_email_checker",
            "company_insights_service",
            "phones_enricher_service",
            "trustpilot_service",
            "whitepages_phones",
            "ai_chain_info",
          ],
          type: "string",
        },
        type: "array",
      },
      style: "form",
    },
    {
      description:
        "The parameter defines which fields you want to include with each item returned in the response. By default, it returns all fields. Use `&fields=query,name` to return only the specific ones.",
      in: "query",
      location: "query",
      name: "fields",
      required: false,
      schema: {
        type: "string",
      },
    },
    {
      description:
        "The parameter defines the format of the output data. Using this parameter overwrites the `ui` parameter to `true`.",
      in: "query",
      location: "query",
      name: "format",
      required: false,
      schema: {
        collectionFormat: "csv",
        items: {
          default: "xlsx",
          enum: ["xlsx", "csv", "json", "parquet"],
          type: "string",
        },
        type: "array",
      },
    },
    {
      description: "The parameter specifies the limit of items to get from one query.",
      in: "query",
      location: "query",
      name: "limit",
      required: false,
      schema: {
        default: 100,
        type: "integer",
      },
    },
    {
      description:
        "Search links with search parameters (e.g., `https://www.yelp.com/search?find_desc=Restaurants&find_loc=San+Francisco%2C+CA`).\n\nIt supports batching by sending arrays with up to `1000` queries (e.g., `query=text1&query=text2&query=text3`). It allows multiple queries to be sent in one request and to save on network latency time.",
      in: "query",
      location: "query",
      name: "query",
      required: true,
      schema: {
        collectionFormat: "csv",
        items: {
          type: "string",
        },
        type: "array",
      },
    },
    {
      description:
        "The parameter defines whether a task will be executed as a UI task. This is commonly used when you want to create a regular platform task with API.\n\nUsing this parameter overwrites the `async` parameter to `true`.",
      in: "query",
      location: "query",
      name: "ui",
      required: false,
      schema: {
        default: false,
        type: "boolean",
      },
    },
    {
      description:
        "The parameter defines the URL address (callback) to which Outscraper will create a POST request with a JSON body once a task/request is finished.\n\nUsing this parameter overwrites the webhook from integrations.",
      in: "query",
      location: "query",
      name: "webhook",
      required: false,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/yelp-search",
  responses: [
    {
      content: [
        {
          example: {
            data: [
              [
                {
                  biz_id: "HHtpR0RslupSQ99GIIwW5A",
                  business_url: "https://www.yelp.com/biz/marufuku-ramen-san-francisco-5?osq=Restaurants",
                  categories: ["Ramen"],
                  formatted_dddress: "",
                  name: "Marufuku Ramen",
                  neighborhoods: ["Lower Pacific Heights"],
                  phone: "(415) 872-9786",
                  photo: "https://s3-media0.fl.yelpcdn.com/bphoto/ouK2VmW0SrI70jsJpTxJhw/348s.jpg",
                  price_range: "$$",
                  query: "https://www.yelp.com/search?find_desc=Restaurants&find_loc=San+Francisco%2C+CA",
                  rating: 4.4,
                  reviews: 4109,
                  services: ["Outdoor seating", "Delivery", "Takeout"],
                  snippet:
                    "Long long overdue review, but I loved this place. The line was literally booty, so me and my friends went half an hour before opening, and sat by a nearby…",
                  tags: ["Waitlist is closed"],
                },
                {
                  biz_id: "8VurRDEj1RpimenhgTmyFQ",
                  business_url: "https://www.yelp.com/biz/kaiy%C5%8D-rooftop-san-francisco-5?osq=Restaurants",
                  categories: ["Peruvian", "Cocktail Bars", "Sushi Bars"],
                  formatted_dddress: "",
                  name: "KAIYŌ Rooftop",
                  neighborhoods: ["South Beach"],
                  phone: "",
                  photo: "https://s3-media0.fl.yelpcdn.com/bphoto/IpnkGDpsm94wGzTAdFekPg/348s.jpg",
                  price_range: "",
                  query: "https://www.yelp.com/search?find_desc=Restaurants&find_loc=San+Francisco%2C+CA",
                  rating: 3.8,
                  reviews: 334,
                  services: ["Outdoor seating", "Delivery", "Takeout"],
                  snippet: null,
                  tags: [],
                },
                {
                  biz_id: "J7_-faNq_Ag9qTOlDn81Pw",
                  business_url: "https://www.yelp.com/biz/starbelly-san-francisco?osq=Restaurants",
                  categories: ["Comfort Food", "Cocktail Bars", "Wine Bars"],
                  formatted_dddress: "",
                  name: "Starbelly",
                  neighborhoods: ["Castro"],
                  phone: "(415) 252-7500",
                  photo: "https://s3-media0.fl.yelpcdn.com/bphoto/G1SweY3VbKx_BqAws9RytA/348s.jpg",
                  price_range: "$$",
                  query: "https://www.yelp.com/search?find_desc=Restaurants&find_loc=San+Francisco%2C+CA",
                  rating: 3.8,
                  reviews: 2112,
                  services: ["Outdoor seating", "Delivery", "Takeout"],
                  snippet:
                    "Starbelly has been one of my go to comfort restaurants since I moved to this city. The menu is always fresh and new but the atmosphere and service always makes…",
                  tags: ["Live wait time: 0 mins"],
                },
              ],
            ],
            id: "your-request-id",
            status: "Success",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: {},
      status: "200",
    },
    {
      content: [
        {
          example: {
            id: "your-request-id",
            results_location: "https://api.outscraper.cloud/requests/your-request-id",
            status: "Pending",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description:
        "The response contains a request ID that can be used to fetch results by using [Request Results](#tag/requests/GET/requests/{requestId}) endpoint. Each response is available for `4` hours after a request has been completed.",
      status: "202",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage: "Please close past due invoices or verify your card information is correct.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Past due invoices or a payment method not connected.",
      status: "402",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Invalid query URL parameters.",
      status: "422",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Yelp Search",
  tags: ["Others", "Businesses & POI"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source:
        'curl -X GET "https://api.outscraper.cloud/yelp-search?query=https%3A%2F%2Fwww.yelp.com%2Fsearch%3Ffind_desc%3DRestaurants%26find_loc%3DSan%2BFrancisco%252C%2BCA&limit=3&async=false" -H  "X-API-KEY: YOUR-API-KEY"',
    },
    {
      lang: "cURL (async)",
      source:
        'curl -X GET "https://api.outscraper.cloud/yelp-search?query=https%3A%2F%2Fwww.yelp.com%2Fsearch%3Ffind_desc%3DRestaurants%26find_loc%3DSan%2BFrancisco%252C%2BCA&limit=3" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
