/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const yelpSearchGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.array(
          v.looseObject({
            biz_id: v.optional(v.unknown()),
            business_url: v.optional(v.unknown()),
            categories: v.optional(v.unknown()),
            formatted_dddress: v.optional(v.unknown()),
            name: v.optional(v.unknown()),
            neighborhoods: v.optional(v.unknown()),
            phone: v.optional(v.unknown()),
            photo: v.optional(v.unknown()),
            price_range: v.optional(v.unknown()),
            query: v.optional(v.unknown()),
            rating: v.optional(v.unknown()),
            reviews: v.optional(v.unknown()),
            services: v.optional(v.unknown()),
            snippet: v.optional(v.unknown()),
            tags: v.optional(v.unknown()),
          }),
        ),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type YelpSearchGetResponse = v.InferOutput<typeof yelpSearchGetResponseSchema>
