/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type YelpSearchGetInput, yelpSearchGetInputSchema } from "./yelpSearchGetInputSchema.js"
import { type YelpSearchGetResponse, yelpSearchGetResponseSchema } from "./yelpSearchGetResponseSchema.js"

export async function yelpSearchGet(
  client: OutscraperClient,
  input: YelpSearchGetInput,
): Promise<Result<YelpSearchGetResponse>> {
  const op = "yelpSearchGet"
  const parsed = v.safeParse(yelpSearchGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid yelpSearchGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/yelp-search",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: yelpSearchGetResponseSchema,
  })
}
