/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type PhonesOwnersGetInput, phonesOwnersGetInputSchema } from "./phonesOwnersGetInputSchema.js"
import { type PhonesOwnersGetResponse, phonesOwnersGetResponseSchema } from "./phonesOwnersGetResponseSchema.js"

export async function phonesOwnersGet(
  client: OutscraperClient,
  input: PhonesOwnersGetInput,
): Promise<Result<PhonesOwnersGetResponse>> {
  const op = "phonesOwnersGet"
  const parsed = v.safeParse(phonesOwnersGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid phonesOwnersGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/phones-owners",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: phonesOwnersGetResponseSchema,
  })
}
