/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type YoutubeVideosGetInput, youtubeVideosGetInputSchema } from "./youtubeVideosGetInputSchema.js"
import { type YoutubeVideosGetResponse, youtubeVideosGetResponseSchema } from "./youtubeVideosGetResponseSchema.js"

export async function youtubeVideosGet(
  client: OutscraperClient,
  input: YoutubeVideosGetInput,
): Promise<Result<YoutubeVideosGetResponse>> {
  const op = "youtubeVideosGet"
  const parsed = v.safeParse(youtubeVideosGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid youtubeVideosGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/youtube-videos",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: youtubeVideosGetResponseSchema,
  })
}
