/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const youtubeVideosGetResponseSchema = v.union([
  v.looseObject({}),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.undefined(),
])

export type YoutubeVideosGetResponse = v.InferOutput<typeof youtubeVideosGetResponseSchema>
