/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type BusinessesPostInput, businessesPostInputSchema } from "./businessesPostInputSchema.js"
import { type BusinessesPostResponse, businessesPostResponseSchema } from "./businessesPostResponseSchema.js"

export async function businessesPost(
  client: OutscraperClient,
  input: BusinessesPostInput = {},
): Promise<Result<BusinessesPostResponse>> {
  const op = "businessesPost"
  const parsed = v.safeParse(businessesPostInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid businessesPost input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/businesses",
    method: "POST",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,
    body: value.body,
    contentType: "application/json",
    schema: businessesPostResponseSchema,
  })
}
