/* Generated by openApiCatalogGenerate. Do not edit. */
export const businessesPostDefinition = {
  description:
    "Retrieve business records with optional enrichment data.\n\nThis endpoint provides access to millions of business listings with support for pagination and selective data enrichment. Choose which enrichments to include (contacts, emails, phone numbers, company insights, email verification, etc.) to optimize response size and cost.\n\nPerfect for building lead lists, market research, or populating your CRM with verified business data.",
  folder: "post-businesses",
  method: "POST",
  operationId: "postBusinesses",
  parameters: [],
  path: "/businesses",
  requestBody: {
    content: [
      {
        mediaType: "application/json",
        schema: {
          example: {
            cursor: null,
            enrichments: {
              company_insights: {},
              leads_n_contacts: {
                contacts_per_company: 3,
                emails_per_contact: 1,
              },
            },
            filters: {
              business_statuses: ["operational"],
              cities: ["New York", "Buffalo"],
              country_code: "US",
              email_and_phone: "with_phone",
              has_website: true,
              states: ["NY"],
              types: ["restaurant", "cafe"],
            },
            include_total: false,
            limit: 10,
          },
          properties: {
            cursor: {
              description: "Cursor for pagination to retrieve the next set of results.",
              nullable: true,
              type: "string",
            },
            enrichments: {
              description: "Enrichments to apply to business records.",
              properties: {
                company_insights: {
                  description:
                    "Whether to include company insights in the response. Company insights may include information such as estimated revenue, employee count, industry classification, and other relevant business metrics.",
                  example: true,
                  type: "boolean",
                },
                leads_n_contacts: {
                  description:
                    "Whether to include contacts and leads information in the response. This may include email addresses, phone numbers, and other contact details associated with the business.",
                  example: [
                    {
                      contacts_per_company: 5,
                      emails_per_contact: 3,
                    },
                  ],
                  properties: {
                    contacts_per_company: {
                      default: 3,
                      description:
                        "Number of contacts to return per company when `leads_n_contacts` enrichment is enabled.",
                      minimum: 1,
                      type: "integer",
                    },
                    emails_per_contact: {
                      default: 1,
                      description:
                        "Number of email addresses to return per contact when `leads_n_contacts` enrichment is enabled.",
                      minimum: 1,
                      type: "integer",
                    },
                  },
                  type: "object",
                },
              },
              type: "object",
            },
            fields: {
              description: "List of fields to include in the response. If not specified, all fields will be returned.",
              example: ["name", "address", "website", "phone", "rating"],
              items: {
                type: "string",
              },
              type: "array",
            },
            filters: {
              description: "Filtering criteria to narrow down business records.",
              properties: {
                added_from: {
                  description: "Unix timestamp in seconds. Filters businesses added at or after this time.",
                  example: 1717200000,
                  type: "integer",
                },
                added_to: {
                  description: "Unix timestamp in seconds. Filters businesses added at or before this time.",
                  example: 1719791999,
                  type: "integer",
                },
                area_service: {
                  description: "Whether the business is marked as an area service business.",
                  example: false,
                  type: "boolean",
                },
                attributes: {
                  description: "List of business attributes to filter by.",
                  example: ["wheelchair_accessible", "takes_reservations"],
                  items: {
                    type: "string",
                  },
                  type: "array",
                },
                broad_match: {
                  description: "Whether to use broader matching for text/category filters.",
                  example: false,
                  type: "boolean",
                },
                business_only: {
                  description: "Whether to return only businesses (exclude other entity types).",
                  example: true,
                  type: "boolean",
                },
                business_statuses: {
                  description: "Business status filter.",
                  example: ["operational"],
                  items: {
                    enum: ["operational", "closed_temporarily", "closed_permanently"],
                    type: "string",
                  },
                  type: "array",
                },
                cities: {
                  description: "List of cities to filter businesses by.",
                  example: ["Los Angeles", "New York"],
                  items: {
                    type: "string",
                  },
                  type: "array",
                },
                counties: {
                  description: "List of counties/boroughs to filter businesses by.",
                  example: ["Kings County", "Queens County"],
                  items: {
                    type: "string",
                  },
                  type: "array",
                },
                country_code: {
                  description: "Two-letter country code to filter businesses by country (e.g., 'US', 'GB', 'CA').",
                  example: "US",
                  type: "string",
                },
                domain: {
                  description: "Website domain to filter businesses by (e.g., 'example.com').",
                  example: "example.com",
                  type: "string",
                },
                email_and_phone: {
                  description:
                    "Filter by email and phone availability. Use `enter_phone` together with the `phone` field to match a specific phone number.",
                  enum: [
                    "with_email",
                    "without_email",
                    "with_phone",
                    "without_phone",
                    "enter_phone",
                    "email_and_phone",
                    "email_or_phone",
                  ],
                  example: "with_phone",
                  type: "string",
                },
                geo_filters: {
                  description: "List of geo filter objects (e.g., polygons, circles, bounding boxes).",
                  example: [
                    {
                      lat: 34.0522,
                      lng: -118.2437,
                      radius_m: 2000,
                      type: "circle",
                    },
                  ],
                  items: {
                    type: "object",
                  },
                  type: "array",
                },
                has_website: {
                  description: "Whether the business has a website (`true`) or not (`false`).",
                  example: true,
                  type: "boolean",
                },
                ignore_types: {
                  description: "List of business categories to exclude from results.",
                  example: ["bar", "night_club"],
                  items: {
                    type: "string",
                  },
                  type: "array",
                },
                located_os_id: {
                  description: "Location reference Outscraper ID used to filter nearby/related businesses.",
                  example: "b3c1f2a0d9e84f0a6c3b9d2f4e7a1c90",
                  type: "string",
                },
                name: {
                  description: "Business name filter (partial or full match).",
                  example: "Starbucks",
                  type: "string",
                },
                name_exclude: {
                  description:
                    "Whether to exclude businesses matching the `name` filter (`true`) or include them (`false`).",
                  example: true,
                  type: "boolean",
                },
                os_ids: {
                  description: "List of Outscraper business IDs (os_id) to include.",
                  example: ["b3c1f2a0d9e84f0a6c3b9d2f4e7a1c90", "9f1a2b3c4d5e6f708192a3b4c5d6e7f8"],
                  items: {
                    type: "string",
                  },
                  type: "array",
                },
                phone: {
                  description: "Phone number suffix to match when `email_and_phone` is `enter_phone`.",
                  example: "14155550123",
                  type: "string",
                },
                postal_codes: {
                  description: "List of postal/ZIP codes to filter businesses by (full or partial).",
                  example: ["10001", "90"],
                  items: {
                    type: "string",
                  },
                  type: "array",
                },
                rating: {
                  description: "Rating filter expression.",
                  example: "4.5+",
                  type: "string",
                },
                reviews: {
                  description: "Reviews count filter expression.",
                  example: "100+",
                  type: "string",
                },
                states: {
                  description: "List of states or provinces to filter businesses by.",
                  example: ["CA", "NY"],
                  items: {
                    type: "string",
                  },
                  type: "array",
                },
                types: {
                  description: "List of business categories to include (e.g., 'restaurant', 'dentist', 'hotel').",
                  example: ["restaurant", "cafe"],
                  items: {
                    type: "string",
                  },
                  type: "array",
                },
                updated_from: {
                  description:
                    "Unix timestamp in seconds. Filters businesses whose customer-visible data changed at or after this time.",
                  example: 1717200000,
                  type: "integer",
                },
                updated_to: {
                  description:
                    "Unix timestamp in seconds. Filters businesses whose customer-visible data changed at or before this time.",
                  example: 1719791999,
                  type: "integer",
                },
                verified: {
                  description: "Whether the business is verified.",
                  example: true,
                  type: "boolean",
                },
              },
              type: "object",
            },
            include_total: {
              default: false,
              description:
                "Whether to include the total count of matching records in the response. This could increase response time.",
              type: "boolean",
            },
            limit: {
              default: 10,
              description: "Maximum number of business records to return.",
              maximum: 1000,
              minimum: 1,
              type: "integer",
            },
            query: {
              description:
                "Natural language query to search for businesses (e.g., `restaurants in New York`). This is an alternative to using structured filters and can be used in combination with them. The API will attempt to parse the query and apply relevant filters based on the content.",
              nullable: true,
              type: "string",
            },
          },
          type: "object",
        },
      },
    ],
    required: false,
  },
  responses: [
    {
      content: [
        {
          example: {},
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: {},
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage: "Please close past due invoices or verify your card information is correct.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Past due invoices or a payment method not connected.",
      status: "402",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "422 Unprocessable Entity: The request was well-formed but was unable to be followed due to semantic errors.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Invalid query URL parameters.",
      status: "422",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "List Business Records",
  tags: ["Businesses & POI", "Business Data API"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source:
        'curl -X GET "https://api.outscraper.cloud/businesses/similar/outscraper.com" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
