/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const businessesPostInputSchema =
  /* businessesPost input is grouped by HTTP argument location. */
  v.object({
    path: v.optional(v.looseObject({}), {}),
    query: v.optional(v.looseObject({}), {}),
    headers: v.optional(v.looseObject({}), {}),
    body: v.optional(
      v.looseObject({
        cursor: v.optional(v.nullable(v.string())),
        enrichments: v.optional(
          v.looseObject({
            company_insights: v.optional(v.boolean()),
            leads_n_contacts: v.optional(
              v.looseObject({
                contacts_per_company: v.optional(v.pipe(v.number(), v.integer(), v.minValue(1)), 3),
                emails_per_contact: v.optional(v.pipe(v.number(), v.integer(), v.minValue(1)), 1),
              }),
            ),
          }),
        ),
        fields: v.optional(v.array(v.string())),
        filters: v.optional(
          v.looseObject({
            added_from: v.optional(v.pipe(v.number(), v.integer())),
            added_to: v.optional(v.pipe(v.number(), v.integer())),
            area_service: v.optional(v.boolean()),
            attributes: v.optional(v.array(v.string())),
            broad_match: v.optional(v.boolean()),
            business_only: v.optional(v.boolean()),
            business_statuses: v.optional(
              v.array(
                v.union([v.literal("operational"), v.literal("closed_temporarily"), v.literal("closed_permanently")]),
              ),
            ),
            cities: v.optional(v.array(v.string())),
            counties: v.optional(v.array(v.string())),
            country_code: v.optional(v.string()),
            domain: v.optional(v.string()),
            email_and_phone: v.optional(
              v.union([
                v.literal("with_email"),
                v.literal("without_email"),
                v.literal("with_phone"),
                v.literal("without_phone"),
                v.literal("enter_phone"),
                v.literal("email_and_phone"),
                v.literal("email_or_phone"),
              ]),
            ),
            geo_filters: v.optional(v.array(v.looseObject({}))),
            has_website: v.optional(v.boolean()),
            ignore_types: v.optional(v.array(v.string())),
            located_os_id: v.optional(v.string()),
            name: v.optional(v.string()),
            name_exclude: v.optional(v.boolean()),
            os_ids: v.optional(v.array(v.string())),
            phone: v.optional(v.string()),
            postal_codes: v.optional(v.array(v.string())),
            rating: v.optional(v.string()),
            reviews: v.optional(v.string()),
            states: v.optional(v.array(v.string())),
            types: v.optional(v.array(v.string())),
            updated_from: v.optional(v.pipe(v.number(), v.integer())),
            updated_to: v.optional(v.pipe(v.number(), v.integer())),
            verified: v.optional(v.boolean()),
          }),
        ),
        include_total: v.optional(v.boolean(), false),
        limit: v.optional(v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(1000)), 10),
        query: v.optional(v.nullable(v.string())),
      }),
    ),
  })

export type BusinessesPostInput = v.InferInput<typeof businessesPostInputSchema>
