/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const businessesPostResponseSchema = v.looseObject({})

export type BusinessesPostResponse = v.InferOutput<typeof businessesPostResponseSchema>
