/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type UniversalScraperGetInput, universalScraperGetInputSchema } from "./universalScraperGetInputSchema.js"
import {
  type UniversalScraperGetResponse,
  universalScraperGetResponseSchema,
} from "./universalScraperGetResponseSchema.js"

export async function universalScraperGet(
  client: OutscraperClient,
  input: UniversalScraperGetInput,
): Promise<Result<UniversalScraperGetResponse>> {
  const op = "universalScraperGet"
  const parsed = v.safeParse(universalScraperGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid universalScraperGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/universal-scraper",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: universalScraperGetResponseSchema,
  })
}
