/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const yelpBizGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          biz_id: v.optional(v.nullable(v.string())),
          business_url: v.optional(v.nullable(v.string())),
          city: v.optional(v.nullable(v.string())),
          closed: v.optional(v.nullable(v.boolean())),
          country: v.optional(v.nullable(v.string())),
          image: v.optional(v.nullable(v.string())),
          name: v.optional(v.nullable(v.string())),
          phone: v.optional(v.nullable(v.string())),
          postal_code: v.optional(v.nullable(v.string())),
          price_range: v.optional(v.nullable(v.string())),
          query: v.optional(v.nullable(v.string())),
          rating: v.optional(v.nullable(v.number())),
          reviews: v.optional(v.nullable(v.number())),
          state: v.optional(v.nullable(v.string())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type YelpBizGetResponse = v.InferOutput<typeof yelpBizGetResponseSchema>
