/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type ExpediaReviewsGetInput, expediaReviewsGetInputSchema } from "./expediaReviewsGetInputSchema.js"
import { type ExpediaReviewsGetResponse, expediaReviewsGetResponseSchema } from "./expediaReviewsGetResponseSchema.js"

export async function expediaReviewsGet(
  client: OutscraperClient,
  input: ExpediaReviewsGetInput,
): Promise<Result<ExpediaReviewsGetResponse>> {
  const op = "expediaReviewsGet"
  const parsed = v.safeParse(expediaReviewsGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid expediaReviewsGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/expedia-reviews",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: expediaReviewsGetResponseSchema,
  })
}
