/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const invoicesGetResponseSchema = v.looseObject({
  has_more: v.optional(v.nullable(v.boolean())),
  items: v.optional(v.array(v.unknown())),
})

export type InvoicesGetResponse = v.InferOutput<typeof invoicesGetResponseSchema>
