/* Generated by openApiCatalogGenerate. Do not edit. */
export const invoicesGetDefinition = {
  description: "Fetch user invoices.",
  folder: "get-invoices",
  method: "GET",
  operationId: "getInvoices",
  parameters: [
    {
      description: "Last invoice ID. Used for pagination.",
      in: "path",
      location: "path",
      name: "lastId",
      required: false,
      schema: {
        type: "string",
      },
    },
  ],
  path: "/invoices",
  responses: [
    {
      content: [
        {
          example: {
            has_more: false,
            items: [],
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "User invoices.",
      status: "200",
    },
    {
      content: [
        {
          example: {
            error: true,
            errorMessage:
              "401 Unauthorized: The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.",
          },
          mediaType: "application/json",
          schema: {},
        },
      ],
      description: "Wrong or missing API Key (token).",
      status: "401",
    },
  ],
  security: [
    {
      ApiKeyAuth: [],
    },
  ],
  summary: "Get Invoices",
  tags: ["Platform & Dashboard"],
  "x-codeSamples": [
    {
      lang: "cURL",
      source: 'curl -X GET "https://api.outscraper.cloud/invoices" -H  "X-API-KEY: YOUR-API-KEY"',
    },
  ],
} as const
