/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type InvoicesGetInput, invoicesGetInputSchema } from "./invoicesGetInputSchema.js"
import { type InvoicesGetResponse, invoicesGetResponseSchema } from "./invoicesGetResponseSchema.js"

export async function invoicesGet(
  client: OutscraperClient,
  input: InvoicesGetInput = {},
): Promise<Result<InvoicesGetResponse>> {
  const op = "invoicesGet"
  const parsed = v.safeParse(invoicesGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid invoicesGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/invoices",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: invoicesGetResponseSchema,
  })
}
