/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"
import { type Result } from "#result"
import type { OutscraperClient } from "../outscraperClientCreate.js"
import { outscraperRequest } from "../outscraperRequest.js"
import { outscraperResultErrorCreate } from "../outscraperResultErrorCreate.js"
import { type TrustpilotGetInput, trustpilotGetInputSchema } from "./trustpilotGetInputSchema.js"
import { type TrustpilotGetResponse, trustpilotGetResponseSchema } from "./trustpilotGetResponseSchema.js"

export async function trustpilotGet(
  client: OutscraperClient,
  input: TrustpilotGetInput,
): Promise<Result<TrustpilotGetResponse>> {
  const op = "trustpilotGet"
  const parsed = v.safeParse(trustpilotGetInputSchema, input)
  if (!parsed.success) {
    return outscraperResultErrorCreate(op, `Invalid trustpilotGet input: ${v.summarize(parsed.issues)}`)
  }

  const value = parsed.output
  return outscraperRequest(client, {
    op,
    path: "/trustpilot",
    method: "GET",
    pathParams: value.path as Record<string, string | number | boolean>,
    params: value.query as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | null | undefined
    >,
    headers: value.headers as Record<
      string,
      string | number | boolean | readonly (string | number | boolean)[] | undefined
    >,

    schema: trustpilotGetResponseSchema,
  })
}
