/* Generated by openApiCatalogGenerate. Do not edit. */
import * as v from "valibot"

export const trustpilotGetResponseSchema = v.union([
  v.looseObject({
    data: v.optional(
      v.array(
        v.looseObject({
          address: v.optional(v.nullable(v.string())),
          categories: v.optional(v.array(v.unknown())),
          city: v.optional(v.nullable(v.string())),
          claimed: v.optional(v.nullable(v.boolean())),
          closed: v.optional(v.nullable(v.boolean())),
          country: v.optional(v.nullable(v.string())),
          email: v.optional(v.nullable(v.string())),
          name: v.optional(v.nullable(v.string())),
          page_url: v.optional(v.unknown()),
          phone: v.optional(v.nullable(v.string())),
          profile_image: v.optional(v.nullable(v.string())),
          query: v.optional(v.nullable(v.string())),
          rating: v.optional(v.nullable(v.number())),
          reviews: v.optional(v.nullable(v.number())),
          site: v.optional(v.nullable(v.string())),
          temporarily_closed: v.optional(v.nullable(v.boolean())),
          zip_code: v.optional(v.nullable(v.string())),
        }),
      ),
    ),
    id: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
  v.looseObject({
    id: v.optional(v.nullable(v.string())),
    results_location: v.optional(v.nullable(v.string())),
    status: v.optional(v.nullable(v.string())),
  }),
])

export type TrustpilotGetResponse = v.InferOutput<typeof trustpilotGetResponseSchema>
